# -*- coding: utf-8 -*-

def get_24_to_27():
    # 24. Sports & Fitness
    t24 = [
        ("Playing sports regularly keeps both body and mind sharp.", "باقاعدگی سے کھیل کھیلنا جسم اور دماغ دونوں کو چست رکھتا ہے۔", "Baqaidgi se khel khelna jism aur dimagh dono ko chust rakhta hai."),
        ("Who is your favorite international cricket batsman?", "آپ کا پسندیدہ بین الاقوامی کرکٹ بلے باز کون ہے؟", "Aap ka pasandeeda bain-ul-aqwami cricket ballebaz kaun hai?"),
        ("I go to the gymnasium for strength training four days a week.", "میں ہفتے میں چار دن ورزش کے لیے جم جاتا ہوں۔", "Mein haftay mein chaar din warzish ke liye gym jaata hoon."),
        ("Drinking enough water during intense workouts is essential.", "سخت ورزش کے دوران مناسب پانی پینا انتہائی ضروری ہے۔", "Sakht warzish ke dauran munasib paani peena intehai zaroori hai."),
        ("Pakistan won the thrilling cricket match in the final over.", "پاکستان نے آخری اوور میں سنسنی خیز کرکٹ میچ جیت لیا۔", "Pakistan ne aakhri over mein sansani khez cricket match jeet liya."),
        ("Jogging in the morning fresh air boosts your stamina.", "صبح کی تازہ ہوا میں جاگنگ کرنا جسمانی توانائی بڑھاتا ہے۔", "Subah ki taaza hawa mein jogging karna jismani tawanaai barhata hai."),
        ("Make sure you stretch your muscles thoroughly before running.", "دوڑنے سے پہلے اپنے پٹھوں کو اچھی طرح کھینچ کر گرم کریں۔", "Dorrnay se pehle apne patthon ko achi tarah kheench kar garam karein."),
        ("He scored an incredible goal from outside the penalty box.", "اس نے پنالٹی باکس کے باہر سے شاندار گول کیا۔", "Us ne penalty box ke bahar se shandar goal kiya."),
        ("Swimming is one of the best full-body cardiovascular workouts.", "تیراکی پورے جسم کی ورزش کے لیے بہترین ثابت ہوتی ہے۔", "Tairaki pooray jism ki warzish ke liye behtareen sabit hoti hai."),
        ("Consistency and balanced nutrition are the keys to true fitness.", "مسلسل کوشش اور متوازن غذا ہی اصل فٹنس کا راز ہیں۔", "Musalsal koshish aur mutawazin ghiza hi asal fitness ka raaz hain."),
        ("What is your current bench press and squat personal record?", "آپ کا بینچ پریس اور اسکواٹ کا ذاتی ریکارڈ کیا ہے؟", "Aap ka bench press aur squat ka zaati record kya hai?"),
        ("I aim to complete ten thousand steps every single day.", "میرا مقصد روزانہ دس ہزار قدم چلنے کا ہدف پورا کرنا ہے۔", "Mera maqsad rozana das hazar qadam chalnay ka hadaf poora karna hai."),
        ("Table tennis requires lightning-fast reflexes and focus.", "ٹیبل ٹینس کے لیے بجلی جیسی تیز رفتاری اور توجہ درکار ہے۔", "Table tennis ke liye bijli jaisi taiz-raftari aur tawajjo darkaar hai."),
        ("Our local football club reached the tournament finals.", "ہمارا مقامی فٹ بال کلب ٹورنامنٹ کے فائنل میں پہنچ گیا۔", "Hamara maqami football club tournament ke final mein pohanch gaya."),
        ("Proper breathing technique prevents workout fatigue.", "سانس لینے کا درست طریقہ ورزش میں جلد تھکنے سے بچاتا ہے۔", "Saans lenay ka durust tareeqa warzish mein jald thaknay se bachata hai."),
        ("I am training hard to run a half marathon next winter.", "میں اگلی سردیوں میں ہاف میراتھن دوڑنے کی سخت تیاری کر رہا ہوں۔", "Mein agli sardiyon mein half marathon dorrnay ki sakht tayari kar raha hoon."),
        ("Badminton is a fantastic sport for agility and endurance.", "بیڈمنٹن چستی اور قوت مدافعت کے لیے ایک زبردست کھیل ہے۔", "Badminton chusti aur quwwat-e-mudafe'at ke liye aik zabardast khel hai."),
        ("Eat protein-rich wholesome food to repair tired muscles.", "تھکے ہوئے پٹھوں کی بحالی کے لیے پروٹین سے بھرپور غذا لیں۔", "Thakay hue patthon ki bahali ke liye protein se bharpoor ghiza lein."),
        ("Warm-up exercises protect your joints from sudden injuries.", "وارم اپ ورزشیں آپ کے جوڑوں کو اچانک چوٹوں سے محفوظ رکھتی ہیں۔", "Warm-up warzishein aap ke jorron ko achanak choton se mahfooz rakhti hain."),
        ("The cricket umpire raised his finger for an LBW decision.", "امپائر نے ایل بی ڈبلیو پر انگلی اٹھا کر آؤٹ قرار دیا۔", "Umpire ne LBW par ungli utha kar out qarar diya."),
        ("Cycling improves cardiovascular health and leg strength.", "سائیکل چلانا دل کی صحت اور ٹانگوں کی طاقت کو بہتر بناتا ہے۔", "Cycle chalana dil ki sehat aur taangon ki taaqat ko behtar banata hai."),
        ("He practices martial arts and holds a black belt in Karate.", "وہ مارشل آرٹس کی مشق کرتا ہے اور کراٹے میں بلیک بیلٹ ہے۔", "Woh martial arts ki mashq karta hai aur karate mein black belt hai."),
        ("Yoga enhances body flexibility, balance, and inner calm.", "یوگا جسم کی لچک، توازن اور اندرونی سکون کو بڑھاتا ہے۔", "Yoga jism ki lachak, tawazun aur androoni sukoon ko barhata hai."),
        ("Always wear supportive athletic running shoes for jogging.", "جاگنگ کے لیے ہمیشہ معیاری اسپورٹس جوتے استعمال کریں۔", "Jogging ke liye hamesha meyaari sports jootay istemal karein."),
        ("The stadium was packed with fifty thousand cheering fans.", "اسٹیڈیم پچاس ہزار پرجوش شائقین سے کھچا کھچ بھرا ہوا تھا۔", "Stadium 50 hazar purjosh shayiqeen se khacha-khach bhara hua tha."),
        ("Discipline in daily training beats raw talent every time.", "روزانہ کی باقاعدہ محنت بغیر محنت کے ہنر کو مات دے دیتی ہے۔", "Rozana ki baqaida mehnat baghair mehnat ke hunar ko maat de deti hai."),
        ("Drink an electrolyte drink on hot summer match days.", "گرمی کے دنوں میں میچ کے دوران نمکیات والا مشروب پئیں۔", "Garmi ke dinon mein match ke dauran namkiyaat wala mashroob piyein."),
        ("Taking rest days is vital for muscle growth and recovery.", "پٹھوں کی مضبوطی اور بحالی کے لیے آرام کے دن ضروری ہیں۔", "Patthon ki mazbooti aur bahali ke liye aaram ke din zaroori hain."),
        ("He bowled a fierce yorker that shattered the stumps.", "اس نے تیز یارکر پھینکی جس نے وکٹیں اکھاڑ دیں۔", "Us ne taiz yorker phainki jis ne wicketein ukhaar dein."),
        ("Fitness is not a temporary trend; it is a lifelong lifestyle.", "فٹنس کوئی عارضی شوق نہیں بلکہ زندگی بھر کا طرزِ حیات ہے۔", "Fitness koi aarzi shauq nahi balkay zindagi bhar ka tarz-e-hayat hai."),
        ("How many pushups and pullups can you do consecutively?", "آپ مسلسل کتنے پش اپس اور پل اپس لگا سکتے ہیں؟", "Aap musalsal kitnay pushups aur pullups laga saktay hain?"),
        ("A thirty-minute brisk walk daily reduces heart risks.", "روزانہ تیس منٹ تیز قدموں کی واک دل کی بیماریوں سے بچاتی ہے۔", "Rozana 30 minute taiz qadmon ki walk dil ki bimariyon se bachati hai."),
        ("Squats build powerful legs and improve core stability.", "اسکواٹس ٹانگوں کو طاقتور اور جسمانی توازن کو بہتر بناتے ہیں۔", "Squats taangon ko taqatwar aur jismani tawazun ko behtar banatay hain."),
        ("Our school cricket team won the inter-city championship cup.", "ہماری اسکول کرکٹ ٹیم نے انٹر سٹی چیمپئن شپ ٹرافی جیت لی۔", "Hamari school cricket team ne inter-city championship trophy jeet li."),
        ("Avoid overtraining to prevent burnout and muscle strains.", "تھکن اور پٹھوں کے کھنچاؤ سے بچنے کے لیے حد سے زیادہ ورزش نہ کریں۔", "Thakan aur patthon ke khinchao se bachnay ke liye hadd se zyada warzish na karein."),
        ("He made a breathtaking catch diving near the boundary line.", "اس نے باؤنڈری لائن کے قریب ہوا میں غوطہ لگا کر شاندار کیچ پکڑا۔", "Us ne boundary line ke qareeb hawa mein ghota laga kar shandar catch pakrra."),
        ("Eat wholesome fruits and almonds before your workout session.", "ورزش شروع کرنے سے پہلے تازہ پھل اور بادام کھائیں۔", "Warzish shuru karne se pehle taaza phal aur badaam khayein."),
        ("Maintain a straight spine when lifting heavy weights.", "وزن اٹھاتے وقت اپنی کمر کو ہمیشہ بالکل سیدھا رکھیں۔", "Wazan uthaatay waqt apni kamar ko hamesha bilkul seedha rakhein."),
        ("The referee blew the whistle to signal the end of the game.", "ریفری نے میچ کے اختتام کی سیٹی بجا دی۔", "Referee ne match ke ikhtitaam ki seeti baja di."),
        ("Sportsmanship teaches us how to win with grace and lose with dignity.", "کھلاڑی کا جذبہ جیت میں عاجزی اور ہار میں وقار سکھاتا ہے۔", "Khilari ka jazba jeet mein aajzi aur haar mein waqaar sikhata hai."),
        ("I love hiking up mountain trails on cool autumn mornings.", "خوشگوار صبح میں پہاڑی راستوں پر چڑھنا میرا پسندیدہ کھیل ہے۔", "Khushgawar subah mein pahari raston par charrhna mera pasandeeda khel hai."),
        ("Staying active keeps your energy levels high all day long.", "متحرک رہنا سارا دن جسم میں چستی اور توانائی برقرار رکھتا ہے۔", "Mutaharrik rehna sara din jism mein chusti aur tawanaai barqarar rakhta hai."),
        ("He won the gold medal in the hundred-meter sprint.", "اس نے سو میٹر کی دوڑ میں گولڈ میڈل جیتا۔", "Us ne 100 meter ki dorr mein gold medal jeeta."),
        ("Team chemistry is essential to win tough tournaments.", "مشکل مقابلے جیتنے کے لیے ٹیم کا باہمی تال میل لازمی ہے۔", "Mushkil muqablay jeetnay ke liye team ka baahmi taal-mail laazmi hai."),
        ("A healthy outside starts from healthy nutrition from the inside.", "خوبصورت اور مضبوط جسم اندرونی اچھی خوراک سے بنتا ہے۔", "Khubsurat aur mazboot jism androoni achi khorak se banta hai."),
        ("Track your physical progress weekly instead of daily.", "روزانہ کے بجائے ہر ہفتے اپنی جسمانی ترقی کا معائنہ کریں۔", "Rozana ke bajaye har haftay apni jismani taraqi ka muaina karein."),
        ("He is a phenomenal captain who leads his team by example.", "وہ ایک زبردست کپتان ہے جو خود مثال بن کر ٹیم کی رہنمائی کرتا ہے۔", "Woh aik zabardast kaptaan hai jo khud misaal ban kar team ki rehnumai karta hai."),
        ("Never underestimate the power of consistent daily effort.", "روزانہ کی مستقل محنت کی طاقت کو کبھی کم مت سمجھیں۔", "Rozana ki mustaqil mehnat ki taaqat ko kabhi kam mat samjhein."),
        ("Physical health and spiritual peace go hand in hand.", "جسمانی صحت اور روحانی سکون ایک دوسرے کے ساتھ جڑے ہیں۔", "Jismani sehat aur roohani sukoon aik doosray ke sath jurray hain."),
        ("Keep training with heart, dedication, and unwavering focus!", "لگن، محنت اور غیر متزلزل توجہ کے ساتھ اپنی مشق جاری رکھیں!", "Lagan, mehnat aur ghair mutazalzil tawajjo ke sath apni mashq jaari rakhein!")
    ]

    # 25. Movies & Entertainment
    t25 = [
        ("Have you watched the latest historical movie release?", "کیا آپ نے حال ہی میں ریلیز ہونے والی تاریخی فلم دیکھی ہے؟", "Kya aap ne haal hi mein release honay wali tareekhi film dekhi hai?"),
        ("The plot twist at the climax of the film left me stunned.", "فلم کے کلائمیکس پر آنے والے موڑ نے مجھے حیران کر دیا۔", "Film ke climax par aanay walay morr ne mujhe heran kar diya."),
        ("Who is your all-time favorite dramatic actor?", "آپ کا اب تک کا سب سے پسندیدہ ڈرامائی اداکار کون ہے؟", "Aap ka ab tak ka sab se pasandeeda dramaee adakaar kaun hai?"),
        ("We reserved front-row cinema tickets for the evening show.", "ہم نے شام کے شو کے لیے سنیما کی اگلی نشستیں بک کروائیں۔", "Hum ne shaam ke show ke liye cinema ki agli nishastein book karwayein."),
        ("The visual special effects and CGI were truly world class.", "فلم کے بصری اثرات (اسپیشل ایفیکٹس) واقعی بین الاقوامی معیار کے تھے۔", "Film ke basri asraat (special effects) waqai bain-ul-aqwami meyaar ke thay."),
        ("That family comedy series had us laughing non-stop.", "اس خاندانی مزاحیہ ڈرامے نے ہمیں مسلسل ہنسنے پر مجبور کیا۔", "Is khandani mizahiya drame ne humein musalsal hansnay par majboor kiya."),
        ("The movie soundtrack and orchestral background score were sublime.", "فلم کا بیک گراؤنڈ میوزک اور گانے لاجواب تھے۔", "Film ka background music aur gaanay la-jawab thay."),
        ("Is this animated film suitable for young kids to watch?", "کیا یہ اینیمیٹڈ فلم چھوٹے بچوں کے دیکھنے کے لیے مناسب ہے؟", "Kya yeh animated film chhotay bachon ke dekhnay ke liye munasib hai?"),
        ("I enjoy binge-watching suspenseful thriller mystery series.", "مجھے سسپنس اور سنسنی خیز پراسرار سیریز دیکھنا پسند ہے۔", "Mujhe suspense aur sansani khez pur-asraar series dekhna pasand hai."),
        ("The lead actress delivered an emotionally powerhouse performance.", "مرکزی اداکارہ نے انتہائی پرتاثیر اور جاندار اداکاری کی۔", "Markazi adakaara ne intehai pur-taseer aur jaandaar adakari ki."),
        ("What genre of movies do you enjoy watching most?", "آپ کس قسم (شعبے) کی فلمیں دیکھنا زیادہ پسند کرتے ہیں؟", "Aap kis qism (sho'bay) ki filmein dekhna zyada pasand kartay hain?"),
        ("I prefer science fiction and historical docudramas.", "میں سائنس فکشن اور تاریخی دستاویزی فلمیں ترجیح دیتا ہوں۔", "Mein science fiction aur tareekhi dastaweezi filmein tarjeeh deta hoon."),
        ("The cinema hall was equipped with Dolby Atmos surround sound.", "سنیما ہال ڈولبی ایٹموس ساؤنڈ سسٹم سے لیس تھا۔", "Cinema hall Dolby Atmos sound system se lais tha."),
        ("Let's get a large bucket of salted butter popcorn.", "آئیں مکھن والے پاپ کارن کا ایک بڑا ٹب لے لیتے ہیں۔", "Aayein makkhan walay popcorn ka aik barra tub le letay hain."),
        ("The director captured the scenic landscapes with poetic beauty.", "ہدایت کار نے قدرتی مناظر کو شاعرانہ خوبصورتی کے ساتھ فلمایا۔", "Hidayat-kaar ne qudrati manazir ko shairana khubsurti ke sath filmaya."),
        ("Have you seen the preview trailer for the upcoming sequel?", "کیا آپ نے آنے والے اگلے حصے کا ٹریلر دیکھا ہے؟", "Kya aap ne aanay walay aglay hissay ka trailer dekha hai?"),
        ("The theatre play received a standing ovation from the audience.", "تھیٹر کے کھیل کو تمام ناظرین کی طرف سے کھڑے ہو کر داد ملی۔", "Theater ke khel ko tamam naazireen ki taraf se kharray ho kar daad mili."),
        ("I love watching witty stand-up comedy specials on weekends.", "مجھے ویک اینڈ پر برجستہ مزاحیہ شوز دیکھنا پسند ہے۔", "Mujhe weekend par barjasta mizahiya shows dekhna pasand hai."),
        ("The scriptwriting was exceptionally witty and meaningful.", "فلم کی کہانی اور مکالمے غیر معمولی طور پر بامعنی اور پرمزاح تھے۔", "Film ki kahani aur mukalmay ghair mamooli tor par ba-maani thay."),
        ("The movie adaptation stayed very loyal to the original book.", "فلم کتاب کے اصل متن اور روح کے بالکل قریب رہی۔", "Film kitaab ke asal matan aur rooh ke bilkul qareeb rahi."),
        ("Which online streaming platform do you subscribe to?", "آپ کس آن لائن اسٹریمنگ پلیٹ فارم کے سبسکرائبر ہیں؟", "Aap kis online streaming platform ke subscriber hain?"),
        ("I love watching classic Pakistani television dramas from the 90s.", "مجھے نوے کی دہائی کے کلاسک پاکستانی ڈرامے دیکھنا پسند ہے۔", "Mujhe 90s ki dahai ke classic Pakistani drame dekhna pasand hai."),
        ("The lead protagonist faces intense moral dilemmas throughout.", "مرکزی کردار کو کہانی میں شدید اخلاقی کشمکش کا سامنا رہتا ہے۔", "Markazi kirdaar ko kahani mein shadeed ikhlaaqi kashmakash ka samna rehta hai."),
        ("We should avoid watching violent cinema before bedtime.", "ہمیں سونے سے پہلے پرتشدد فلمیں دیکھنے سے پرہیز کرنا چاہیے۔", "Humein sonay se pehle pur-tashaddud filmein dekhnay se parhez karna chahiye."),
        ("The film won three prestigious international academy awards.", "فلم نے تین معزز بین الاقوامی اکیڈمی ایوارڈز جیتے۔", "Film ne teen moazzaz bain-ul-aqwami academy awards jeetay."),
        ("The dialogue delivery of the villain gave me goosebumps.", "ولن کے مکالموں کی ادائیگی نے رونگٹے کھڑے کر دیے۔", "Villain ke mukalmon ki adayigi ne rongtay kharray kar diye."),
        ("Do you prefer watching movies at the cinema or at home?", "کیا آپ سنیما میں فلم دیکھنا پسند کرتے ہیں یا گھر پر؟", "Kya aap cinema mein film dekhna pasand kartay hain ya ghar par?"),
        ("I love the immersive giant screen experience of IMAX.", "مجھے آئی میکس کی بڑی اسکرین کا سحر انگیز تجربہ پسند ہے۔", "Mujhe IMAX ki barri screen ka sehar-angeez tajruba pasand hai."),
        ("The documentary shed light on pressing environmental issues.", "دستاویزی فلم نے ماحولیات کے اہم مسائل پر روشنی ڈالی۔", "Dastaweezi film ne maholiyaat ke ahem masail par roshni daali."),
        ("A good story reflects human emotions, struggles, and hope.", "ایک اچھی کہانی انسانی جذبات، جدوجہد اور امید کا آئینہ دار ہوتی ہے۔", "Aik achi kahani insani jazbaat, jadd-o-jehad aur umeed ka aaina-daar hoti hai."),
        ("The cinematography in that desert scene was breathtaking.", "اس صحرائی منظر کی فوٹوگرافی دل دہلا دینے کی حد تک خوبصورت تھی۔", "Us sehrai manzar ki photography dil dehla denay ki hadd tak khubsurat thi."),
        ("He is a versatile actor capable of playing any challenging role.", "وہ ایک ہمہ جہت اداکار ہے جو ہر مشکل کردار نبھا سکتا ہے۔", "Woh aik hama-jehat adakaar hai jo har mushkil kirdaar nibha sakta hai."),
        ("The film ended on an ambiguous, thought-provoking note.", "فلم کا اختتام ایک سوچ طلب اور معنی خیز موڑ پر ہوا۔", "Film ka ikhtitaam aik soch-talab aur maani-khez morr par hua."),
        ("We had a lovely family movie night with homemade pizza.", "ہم نے گھر کے پیزا کے ساتھ فیملی مووی نائٹ کا خوب لطف اٹھایا۔", "Hum ne ghar ke pizza ke sath family movie night ka khoob lutf uthaya."),
        ("The comedy actor has an impeccable sense of comic timing.", "مزاحیہ اداکار کا وقت کا چناؤ اور انداز بے مثال ہے۔", "Mizahiya adakaar ka waqt ka chunao aur andaaz be-misaal hai."),
        ("Children loved the colorful magical fantasy adventure.", "بچوں کو رنگ برنگے جادوئی مناظر والی مہم جوئی بہت پسند آئی۔", "Bachon ko rang barange jadooi manazir wali muhim-jooi bohat pasand aayi."),
        ("The costume design perfectly captured the Mughal royal era.", "لباس کے ڈیزائن نے مغل دور کی شاہی جھلکیاں شاندار انداز میں پیش کیں۔", "Libaas ke design ne Mughal daur ki shahi jhalakiyan shandar andaaz mein pesh keen."),
        ("I was on the edge of my seat throughout the thriller.", "سسپنس فلم کے دوران میں تجسس سے اپنی سیٹ کے کونے پر بیٹھا رہا۔", "Suspense film ke dauran mein tajassus se apni seat ke konay par baitha raha."),
        ("Constructive film criticism elevates artistic storytelling.", "تعمیری تنقید کہانی سنانے کے فن کو نکھار دیتی ہے۔", "Tameeri tanqeed kahani sunanay ke fann ko nikhaar deti hai."),
        ("Let's watch a light-hearted romantic comedy tonight.", "آئیں آج رات کوئی ہلکی پھلکی رومانوی مزاحیہ فلم دیکھتے ہیں۔", "Aayein aaj raat koi halki phulki romanwi mizahiya film dekhtay hain."),
        ("The movie set recreated ancient Lahore with stunning accuracy.", "فلم کے سیٹ پر قدیم لاہور کو انتہائی خوبصورتی سے سجایا گیا۔", "Film ke set par qadeem Lahore ko intehai khubsurti se sajaya gaya."),
        ("He wrote, produced, directed, and acted in his own film.", "اس نے اپنی فلم خود لکھی، بنائی، ڈائریکٹ کی اور اس میں اداکاری کی۔", "Us ne apni film khud likhi, banayi, direct ki aur us mein adakari ki."),
        ("The audience clapped enthusiastically during the victory scene.", "کامیابی کے منظر پر ہال میں موجود لوگوں نے پرجوش تالیاں بجائیں۔", "Kamyabi ke manzar par hall mein maujood logon ne purjosh taaliyan bajayein."),
        ("It is inspiring to see young filmmakers produce original work.", "نوجوان فلم سازوں کا نیا کام بناتے دیکھنا دل کو حوصلہ دیتا ہے۔", "Naujawan film saazon ka naya kaam banatay dekhna dil ko hausla deta hai."),
        ("The film highlighted important social issues with dignity.", "فلم نے اہم سماجی مسائل کو وقار اور سلیقے کے ساتھ اجاگر کیا۔", "Film ne ahem samaji masail ko waqaar aur saleeqay ke sath ujagar kiya."),
        ("Cinema bridges cultures by connecting shared human hearts.", "سنیما مختلف تہذیبوں کو دل کے رشتے کے ذریعے قریب لاتا ہے۔", "Cinema mukhtalif tehzeebon ko dil ke rishtay ke zariye qareeb laata hai."),
        ("Don't spoil the thrilling ending for those who haven't watched!", "جنہوں نے نہیں دیکھی ان کے لیے سسپنس والا اختتام مت بتائیں!", "Jinhon ne nahi dekhi un ke liye suspense wala ikhtitaam mat batayein!"),
        ("The movie ticket prices are discounted on Tuesday afternoons.", "منگل کی دوپہر کو فلم کے ٹکٹوں کی قیمتیں کم ہوتی ہیں۔", "Mangal ki dopahar ko film ke ticketon ki qeematein kam hoti hain."),
        ("Great art entertains, enlightens, and inspires the human spirit.", "عظیم فن تفریح بھی دیتا ہے اور انسان کی روح کو بھی جگاتا ہے۔", "Azeem fann tafreeh bhi deta hai aur insaan ki rooh ko bhi jagata hai."),
        ("Wishing you an entertaining and enjoyable cinematic evening!", "آپ کی فلمی شام خوشگوار، پرلطف اور شاندار گزرے!", "Aap ki filmi shaam khushgawar, pur-lutf aur shandar guzray!")
    ]

    # 26. Music & Arts
    t26 = [
        ("Music speaks a universal language that touches every human soul.", "موسیقی ایک ایسی عالمگیر زبان ہے جو ہر روح کو چھو لیتی ہے۔", "Music aik aisi aalamgeer zaban hai jo har rooh ko chhoo leti hai."),
        ("Have you listened to classical Eastern Qawwali performances?", "کیا آپ نے روایتی مشرقی قوالی کی محفلیں سنی ہیں؟", "Kya aap ne riwayati mashriqi qawwali ki mehfilein suni hain?"),
        ("The harmonium and tabla create a mesmerizing musical rhythm.", "ہارمونیم اور طبلہ ایک سحر انگیز لے اور تال پیدا کرتے ہیں۔", "Harmonium aur tabla aik sehar-angeez lay aur taal paida kartay hain."),
        ("He is a gifted painter specializing in oil portrait art.", "وہ آئل پورٹریٹ آرٹ میں غیر معمولی مہارت رکھنے والا مصور ہے۔", "Woh oil portrait art mein ghair mamooli maharat rakhnay wala musawir hai."),
        ("The local art exhibition showcased contemporary Pakistani sculptures.", "مقامی نمائش میں جدید پاکستانی مجسمہ سازی کی نمائش کی گئی۔", "Maqami numaish mein jadeed پاکستانی mujasma saazi ki numaish ki gayi."),
        ("Learning to play the violin requires immense discipline and ear training.", "وائلن بجانا سیکھنے کے لیے سخت محنت اور سروں کی پہچان چاہیے۔", "Violin bajana seekhnay ke liye sakht mehnat aur suron ki pehchan chahiye."),
        ("Traditional hand-woven carpets are true masterpieces of craft.", "ہاتھ سے بنے روایتی قالین دستکاری کا اعلیٰ شاہکار ہیں۔", "Haath se banay riwayati qaleen dastkari ka aala shahkaar hain."),
        ("Her melodious voice echoed beautifully throughout the auditorium.", "اس کی سریلی آواز پورے آڈیٹوریم میں خوبصورتی سے گونج اٹھی۔", "Us ki sureeli aawaz pooray auditorium mein khubsurti se goonj uthi."),
        ("Calligraphic art with verses of wisdom adorns many home walls.", "حکمت سے بھرپور اشعار کی خطاطی گھروں کی دیواروں کو سجاتی ہے۔", "Hikmat se bharpoor ashaar ki khattati gharon ki deewaron ko sajati hai."),
        ("Art allows individuals to express what words fail to capture.", "آرٹ انسان کو وہ جذبات ظاہر کرنے دیتا ہے جو الفاظ نہیں کہہ پاتے۔", "Art insaan ko woh jazbaat zahir karne deta hai jo alfaaz nahi keh paatay."),
        ("The rhythm of the flute brings a sense of serenity to the heart.", "بانسری کی دھن دل کو ایک انوکھا سکون اور قرار بخشتی ہے۔", "Bansuri ki dhun dil ko aik anokha sukoon aur qaraar bakhshti hai."),
        ("Do you prefer acoustic unplugged music or electronic beats?", "کیا آپ قدرتی سازوں والی موسیقی پسند کرتے ہیں یا الیکٹرانک؟", "Kya aap qudrati saazon wali music pasand kartay hain ya electronic?"),
        ("The art gallery features works by emerging national painters.", "آرٹ گیلری میں نئے ابھرتے ہوئے ملکی مصوروں کے فن پارے ہیں۔", "Art gallery mein naye ubhartay hue mulki musawiron ke fann paaray hain."),
        ("Pottery crafting with wet river clay is an ancient tradition.", "دریائی مٹی سے برتن بنانا ایک صدیوں پرانی خوبصورت روایت ہے۔", "Daryai mitti se bartan banana aik sadiyon purani khubsurat riwayat hai."),
        ("The symphony orchestra played a magnificent Beethoven concerto.", "سمفنی آرکسٹرا نے بیتھوون کا شاندار کلاسک نغمہ پیش کیا۔", "Symphony orchestra ne Beethoven ka shandar classic naghma pesh kiya."),
        ("He mastered the complex raags of classical Hindustani music.", "اس نے کلاسیکی موسیقی کے پیچیدہ راگوں پر مکمل مہارت حاصل کی۔", "Us ne classical music ke paicheeda raagon par mukammal maharat haasil ki."),
        ("Geometric mosaic patterns on ancient mosques are awe-inspiring.", "قدیم مساجد پر ہندسی ٹائلوں کے نقوش عقل کو دنگ کر دیتے ہیں۔", "Qadeem masajid par handasi tiles ke nuqoosh aql ko dang kar detay hain."),
        ("Writing lyrical poetry requires acute sensitivity to life.", "نغمگی والی شاعری لکھنے کے لیے زندگی کی گہری سمجھ چاہیے۔", "Naghmagi wali shayari likhnay ke liye zindagi ki gehri samajh chahiye."),
        ("She held her first solo watercolor painting exhibition today.", "آج اس کی پانی کے رنگوں والی مصوری کی پہلی سولو نمائش ہوئی۔", "Aaj us ki water color painting ki pehli solo numaish hui."),
        ("Folk music preserves the cultural heritage of rural villages.", "لوک موسیقی دیہی علاقوں کے ثقافتی ورثے کو زندہ رکھتی ہے۔", "Lok music deehi ilaaqon ke saqafati virsay ko zinda rakhti hai."),
        ("The beat of the Punjabi dhol energizes everyone at celebrations.", "پنجابی ڈھول کی تھاپ تقریب میں موجود ہر شخص کو جھومنے پر مجبور کرتی ہے۔", "Punjabi dhol ki thaap taqreeb mein maujood har shakhs ko jhoomnay par majboor karti hai."),
        ("Art therapy helps individuals process emotional traumas gently.", "آرٹ تھراپی انسان کو جذباتی زخموں سے پرسکون طریقے سے نکالتی ہے۔", "Art therapy insaan ko jazbaati zakhmon se pursukoon tareeqay se nikaalti hai."),
        ("The sculptor spent five years carving this marble statue.", "مجسمہ ساز نے اس سنگ مرمر کے مجسمے کو تراشنے میں پانچ سال لگائے۔", "Mujasma saaz ne is sang-e-marmar ke mujasmay ko tarashnay mein paanch saal lagaye."),
        ("Classical music sharpens mathematical thinking in growing children.", "کلاسیکی موسیقی بڑھتے ہوئے بچوں کی ریاضیاتی سوچ کو تیز کرتی ہے۔", "Classical music barhtay hue bachon ki riyaziyati soch ko taiz karti hai."),
        ("Every brushstroke conveys emotion, light, shadow, and depth.", "برش کا ہر اسٹروک جذبہ، روشنی، سایہ اور گہرائی بیان کرتا ہے۔", "Brush ka har stroke jazba, roshni, saya aur gehrai bayan karta hai."),
        ("The Rubab is a beloved traditional stringed instrument in the north.", "شمالی علاقوں میں رباب ایک انتہائی محبوب روایتی تاروں والا ساز ہے۔", "Shumali ilaaqon mein rubab aik intehai mehboob riwayati saaz hai."),
        ("Creativity flourishes when the mind is granted true freedom.", "جب ذہن کو سچی آزادی ملتی ہے تو تخلیقی صلاحیتیں نکھرتی ہیں۔", "Jab zehan ko sachi azaadi milti hai to takhleeqi salahiyatein nikharti hain."),
        ("The cultural festival celebrated rich folk dances and poetry.", "ثقافتی میلے میں روایتی رقص اور شاعری کی محفلیں سجائی گئیں۔", "Saqafati meelay mein riwayati raqs aur shayari ki mehfilein sajayi gayeen."),
        ("His lyrics capture the longing of wandering human hearts.", "اس کے گیتوں کے بول بھٹکتے ہوئے دلوں کی تڑپ کو بیان کرتے ہیں۔", "Us ke geeton ke bol bhataktay hue dilon ki tarap ko bayan kartay hain."),
        ("A life enriched by art and melody is deeply fulfilled.", "فن اور نغموں سے سجی زندگی حقیقی معنوں میں پرمسرت ہوتی ہے۔", "Fann aur naghmon se saji zindagi haqeeqi maanon mein pur-musarrat hoti hai."),
        ("The singer received thunderous applause from the crowd.", "گلوکار کو محفل میں موجود سامعین کی طرف سے زبردست داد ملی۔", "Gulukaar ko mehfil mein maujood saami'een ki taraf se zabardast daad mili."),
        ("Traditional brass metalwork requires intricate engraving skills.", "پیتل کے برتنوں پر نقش و نگار بنانے کے لیے باریک کاریگری چاہیے۔", "Peetal ke bartanon par naqsh-o-nigaar bananay ke liye bareek kaareegari chahiye."),
        ("Art galleries offer a serene sanctuary away from city rush.", "آرٹ گیلریاں شہر کے شور و غل سے دور ایک پرسکون پناہ گاہ ہیں۔", "Art galleries shehar ke shor-o-ghul se door aik pursukoon panah-gah hain."),
        ("The guitar solo during the acoustic track was soulful.", "گٹار کا اکیلا نغمہ روح کی گہرائیوں میں اتر جانے والا تھا۔", "Guitar ka akela naghma rooh ki gehraiyon mein utar jaanay wala tha."),
        ("Visual storytelling transcends barriers of spoken languages.", "تصویری کہانیاں زبانی زبانوں کی تمام رکاوٹوں کو مٹا دیتی ہیں۔", "Tasveeri kahaniyan zabani zabanon ki tamam rukawaton ko mita deti hain."),
        ("He composes devotional hymns that bring tears to listeners.", "وہ ایسے روحانی کلام ترتیب دیتا ہے جو سننے والوں کو رلا دیتے ہیں۔", "Woh aisay roohani kalaam tarteeb deta hai jo sunnay walon ko rula detay hain."),
        ("Colors on the canvas mirror the artist's deepest feelings.", "کینوس پر رنگ مصور کے گہرے ترین جذبات کا عکس پیش کرتے ہیں۔", "Canvas par rang musawir ke gehray tareen jazbaat ka aks pesh kartay hain."),
        ("She teaches traditional pottery to students on Saturdays.", "وہ ہفتے کے دن طلبہ کو روایتی برتن سازی سکھاتی ہے۔", "Woh haftay ke din talba ko riwayati bartan-saazi sikhati hai."),
        ("The musical concert raised generous funds for flood relief.", "موسیقی کے کنسرٹ سے سیلاب زدگان کے لیے دل کھول کر فنڈز اکٹھے کیے گئے۔", "Music ke concert se sailaab zadgaan ke liye funds ikatthay kiye gaye."),
        ("Authentic craftsmanship carries the living soul of our ancestors.", "اصلی دستکاری میں ہمارے بزرگوں کی زندہ روح دھڑکتی ہے۔", "Asli dastkari mein hamare bazurgon ki zinda rooh dharrakti hai."),
        ("The blend of modern rock and classical eastern sitar is unique.", "جدید راک اور روایتی ستار کا امتزاج انتہائی منفرد ہے۔", "Jadeed rock aur riwayati sitar ka imtizaj intehai munfarid hai."),
        ("Street murals and graffiti have brightened the urban walls.", "شہری دیواروں پر بنی خوبصورت پینٹنگز نے شہر کو رنگین بنا دیا۔", "Shehri deewaron par bani khubsurat paintings ne shehar ko rangeen bana diya."),
        ("Listening to uplifting spiritual melodies elevates personal mood.", "روحانی نغمے سننا انسان کے موڈ کو خوشگوار بنا دیتا ہے۔", "Roohani naghmay sunna insaan ke mood ko khushgawar bana deta hai."),
        ("The art curator explained the historical context of each piece.", "آرٹ کیوریٹر نے ہر فن پارے کا تاریخی پس منظر سمجھایا۔", "Art curator ne har fann paaray ka tareekhi pas-manzar samjhaya."),
        ("Learning to sketch with charcoal trains your perception.", "کوئلے سے اسکیچ بنانا انسان کے مشاہدے کی صلاحیت کو نکھارتا ہے۔", "Koilay se sketch banana insaan ke mushahiday ko nikharta hai."),
        ("Music brings estranged communities together in harmony.", "موسیقی دور ہوئے معاشروں کو محبت کے ساتھ ایک لڑی میں پروتی ہے۔", "Music door hue ma'ashron ko mohabbat ke sath aik larry mein piroti hai."),
        ("Every culture has its own distinctive artistic legacy.", "ہر تہذیب کا اپنا ایک الگ اور منفرد فنی و ثقافتی ورثہ ہے۔", "Har tehzeeb ka apna aik alag aur munfarid saqafati virsa hai."),
        ("Art teaches us to see profound beauty in ordinary daily life.", "فن ہمیں روزمرہ کی عام چیزوں میں بھی گہری خوبصورتی دیکھنا سکھاتا ہے۔", "Fann humein rozmarrah ki aam cheezon mein bhi gehri khubsurti dekhna sikhata hai."),
        ("Cherish the creative talents of poets, singers, and artisans.", "شاعروں، گلوکاروں اور کاریگروں کی تخلیقی صلاحیتوں کی قدر کریں۔", "Shairon, gulukaron aur kareegaron ki takhleeqi salahiyaton ki qadr karein."),
        ("May your journey be accompanied by beauty, harmony, and song!", "آپ کا سفر ہمیشہ خوبصورتی، ہم آہنگی اور سروں سے سجا رہے!", "Aap ka safar hamesha khubsurti aur suron se saja rahay!")
    ]

    # 27. Clothes & Fashion
    t27 = [
        ("What type of fabric is best suited for hot summer days?", "گرمی کے موسم کے لیے کون سا کپڑا سب سے بہترین رہتا ہے؟", "Garmi ke mausam ke liye kaun sa kapra sab se behtareen rehta hai?"),
        ("Pure breathable cotton keeps you cool and comfortable in heat.", "خالص سوتی کپڑا گرمی میں آپ کو ٹھنڈا اور آرام دہ رکھتا ہے۔", "Khalis sooti kapra garmi mein aap ko thanda aur aaram deh rakhta hai."),
        ("This embroidered traditional Shalwar Kameez looks majestic.", "یہ کڑھائی والا روایتی شلوار قمیض بہت شاندار لگ رہا ہے۔", "Yeh karhai wala riwayati shalwar kameez bohat shandar lag raha hai."),
        ("Does this formal tailored suit match with black leather shoes?", "کیا یہ سلائی شدہ سوٹ کالے چمڑے کے جوتوں کے ساتھ جچتا ہے؟", "Kya yeh silai shuda suit kaalay chamrray ke jooton ke sath jachta hai?"),
        ("I need to get these trousers hemmed by a master tailor.", "مجھے یہ پتلون درزی سے نیچے سے چھوٹی کروانی ہے۔", "Mujhe yeh patloon darzi se neechay se chhoti karwani hai."),
        ("Pastel colors are very fashionable during spring and summer.", "بہار اور گرمیوں میں ہلکے رنگ (پاسٹل کلرز) فیشن میں رہتے ہیں۔", "Bahar aur garmiyon mein halkay rang fashion mein rehtay hain."),
        ("Always wash delicate silk garments with mild laundry detergent.", "ریشمی کپڑوں کو ہمیشہ ہلکے اور نرم صابن سے دھوئیں ہے۔", "Reshmi kapron ko hamesha halkay aur narm saban se dhoein."),
        ("A well-fitted leather jacket adds elegance to winter style.", "اچھی فٹنگ والی چمڑے کی جیکٹ سردیوں کے انداز کو پروقار بناتی ہے۔", "Achi fitting wali chamrray ki jacket sardiyon ke andaaz ko pur-waqaar banati hai."),
        ("Simplicity in dressing reflects genuine class and sophistication.", "لباس میں سادگی ہی انسان کے اعلیٰ ذوق اور وقار کا پتہ دیتی ہے۔", "Libaas mein saadgi hi insaan ke aala zauq aur waqaar ka pata deti hai."),
        ("Do you prefer buying ready-to-wear or custom-tailored clothes?", "کیا آپ تیار شدہ کپڑے پسند کرتے ہیں یا خود سلوانا؟", "Kya aap tayar shuda kapray pasand kartay hain ya khud silwana?"),
        ("This matching silk dupatta completes the festive wedding outfit.", "یہ میچنگ ریشمی دوپٹہ شادی کے لباس کو مکمل اور پررونق بناتا ہے۔", "Yeh matching reshmi dupatta shaadi ke libaas ko mukammal banata hai."),
        ("Iron your dress shirts with steam for a crisp, wrinkle-free look.", "قمیضوں کو شکنوں سے پاک کرنے کے لیے بھاپ والی استری کریں۔", "Qameezon ko shikanon se paak karne ke liye bhaap wali istri karein."),
        ("Wear warm woolen thermal layers to protect against harsh winds.", "سرد ہواؤں سے بچنے کے لیے اندر گرم تھرمل ضرور پہنیں۔", "Sard hawaon se bachnay ke liye andar garam thermal zaroor pehnein."),
        ("Dark navy and charcoal suits are standard for corporate meetings.", "دفتری میٹنگز کے لیے نیوی بلیو اور سرمئی سوٹ معیاری سمجھے جاتے ہیں۔", "Daftari meetings ke liye navy blue aur surmayi suit meyaari samjhay jaatay hain."),
        ("Where can I find premium Boski and Karandi fabric in Lahore?", "لاہور میں بوسکی اور کرنڈی کا بہترین کپڑا کہاں سے ملتا ہے؟", "Lahore mein Boski aur Karandi ka behtareen kapra kahan se milta hai?"),
        ("These hand-embroidered Peshawari chappals are very sturdy.", "یہ ہاتھ سے سلی ہوئی پشاوری چپلیں بہت پائیدار اور خوبصورت ہیں۔", "Yeh haath se sili hui Peshawari chappalein bohat payedaar hain."),
        ("Make sure the collar button is fastened comfortably around neck.", "دیکھیں کہ کالر کا بٹن گلے پر آرام سے بند ہو رہا ہو۔", "Dekhein ke collar ka button galay par aaram se band ho raha ho."),
        ("Neutral shades like beige and olive blend gracefully with anything.", "ہلکے بادامی اور زیتونی رنگ ہر لباس کے ساتھ اچھے لگتے ہیں۔", "Halkay baadami aur zaitooni rang har libaas ke sath achay lagtay hain."),
        ("She designed an exclusive bridal couture collection for fashion week.", "اس نے فیشن ویک کے لیے دلہنوں کے ملبوسات کا نیا مجموعہ تیار کیا۔", "Us ne fashion week ke liye dulhanon ke malboosaat ka naya majmooa tayar kiya."),
        ("Comfort should always be your top priority in daily fashion.", "روزمرہ کے فیشن میں آرام دہ ہونا ہمیشہ اولین ترجیح ہونا چاہیے۔", "Rozmarrah ke fashion mein aaram deh hona hamesha awaleen tarjeeh hona chahiye."),
        ("Can you replace the broken zipper on this winter parka?", "کیا آپ اس ونٹر پارک جیکٹ کا ٹوٹا ہوا زپ تبدیل کر سکتے ہیں؟", "Kya aap is winter parka jacket ka toota hua zip tabdeel kar saktay hain?"),
        ("Khadi fabric has an authentic rustic charm and earthy feel.", "کھدر کے کپڑے میں ایک دیسی اور خالص روایتی کشش ہوتی ہے۔", "Khaddar ke kapray mein aik desi aur khalis riwayati kashish hoti hai."),
        ("A neat leather wristwatch complements any formal attire.", "چمڑے کے پٹے والی صاف ستھری گھڑی ہر سوٹ کے ساتھ خوب جچتی ہے۔", "Chamrray ke pattay wali saaf suthri gharri har suit ke sath khoob jachti hai."),
        ("Wash dark colors separately to avoid accidental color bleeding.", "رنگ اترنے سے بچنے کے لیے گہرے رنگ کے کپڑے الگ دھوئیں۔", "Rang utarnay se bachnay ke liye gehray rang ke kapray alag dhoein."),
        ("Traditional Ajrak shawls represent timeless Sindhi heritage.", "روایتی اجرک کی چادریں سندھ کے لازوال ثقافتی ورثے کی عکاسی کرتی ہیں۔", "Riwayati Ajrak ki chaadrein Sindh ke la-zawal saqafati virsay ki akkasi karti hain."),
        ("This waist belt is made of 100% genuine full-grain leather.", "یہ بیلٹ سو فیصد اصلی اور معیاری چمڑے سے تیار کی گئی ہے۔", "Yeh belt sau feesad asli aur meyaari chamrray se tayar ki gayi hai."),
        ("Polishing your formal shoes daily keeps the leather supple.", "روزانہ جوتوں کو پالش کرنا چمڑے کو نرم اور چمکدار رکھتا ہے۔", "Rozana jooton ko polish karna chamrray ko narm aur chamakdaar rakhta hai."),
        ("He wore a classic black Sherwani for his wedding reception.", "اس نے ولیمے کی تقریب پر کلاسک کالی شیروانی زیب تن کی۔", "Us ne walimay ki taqreeb par classic kaali sherwani zaib-e-tan ki."),
        ("Avoid fast fashion trends; invest in durable timeless pieces.", "عارضی فیشن کے بجائے ہمیشہ پائیدار اور کلاسیک لباس خریدیں۔", "Aarzi fashion ke bajaye hamesha payedaar aur classic libaas khareedein."),
        ("Good posture makes any outfit look tenfold more distinguished.", "سیدھے کھڑے ہونے کا سلیقہ ہر لباس کو دس گنا زیادہ باوقار بناتا ہے۔", "Seedhay kharray honay ka saleeqa har libaas ko das guna zyada ba-waqaar banata hai."),
        ("Can I get this cuff altered to fit my wrist properly?", "کیا یہ کف میری کلائی کے سائز کے مطابق ٹھیک ہو سکتا ہے؟", "Kya yeh cuff meri kalai ke size ke mutabiq theek ho sakta hai?"),
        ("This woolen shawl provides warmth during freezing hill station trips.", "یہ اون کی شال مری اور شمالی علاقوں کی شدید سردی میں حرارت دیتی ہے۔", "Yeh oon ki shawl Murree aur shumali ilaaqon ki shadeed sardi mein hararat deti hai."),
        ("Choose shoes that provide excellent arch support for walking.", "ایسے جوتے منتخب کریں جو چلنے کے دوران پاؤں کو مکمل سہارا دیں۔", "Aisay jootay muntakhib karein jo chalnay ke dauran paon ko sahara dein."),
        ("Subtle perfume applied to pulse points lasts all day long.", "کلائی اور گردن پر ہلکا پرفیوم لگانا سارا دن مہکتا رہتا ہے۔", "Kalai aur gardan par halka perfume lagana sara din mehakta rehta hai."),
        ("The tailors in Anarkali bazaar are renowned for bridal embroidery.", "انارکلی بازار کے درزی دلہن کی کڑھائی کے لیے مشہور ہیں۔", "Anarkali bazaar ke darzi dulhan ki karhai ke liye mashhoor hain."),
        ("A navy blazer paired with khaki trousers is a timeless look.", "نیوی بلیو بلیزر کے ساتھ خاکی پتلون ہمیشہ فیشن میں رہتی ہے۔", "Navy blue blazer ke sath khaki patloon hamesha fashion mein rehti hai."),
        ("Hang your heavy winter coats on sturdy wooden hangers.", "سردیوں کے وزنی کوٹ لکڑی کے مضبوط ہینگرز پر لٹکائیں۔", "Sardiyon ke wazni coat lakri ke mazboot hangers par latkayein."),
        ("The lining inside this suit jacket is made of smooth satin.", "کوٹ کے اندر کا استر نرم اور چمکدار ساٹن سے بنا ہے۔", "Coat ke andar ka astar narm aur chamakdaar satin se bana hai."),
        ("Dress respectfully according to the occasion and venue.", "ہمیشہ تقریب اور جگہ کے احترام کو مدنظر رکھ کر لباس پہنیں۔", "Hamesha taqreeb aur jagah ke ihtiram ko madd-e-nazar rakh kar libaas pehnein."),
        ("A bright smile and kind manners are the finest accessories.", "ایک روشن مسکراہٹ اور اچھا اخلاق ہی انسان کا بہترین زیور ہے۔", "Aik roshan muskurahat aur acha ikhlaaq hi insaan ka behtareen zewar hai."),
        ("Do you sell organic cotton shirts without synthetic polyester?", "کیا آپ کے پاس بغیر پولیسٹر کے خالص سوتی شرٹس ہیں؟", "Kya aap ke paas baghair polyester ke khalis sooti shirts hain?"),
        ("This trench coat protects from heavy wind and rain showers.", "یہ ٹرینچ کوٹ تیز ہوا اور بارش کی پھوار سے مکمل بچاتا ہے۔", "Yeh trench coat taiz hawa aur barish ki phuwaar se mukammal bachata hai."),
        ("Ensure your clothes are thoroughly dried before packing away.", "کپڑوں کو سنبھالنے سے پہلے یقینی بنائیں کہ وہ اچھی طرح خشک ہوں۔", "Kapron ko sambhalnay se pehle yaqeeni banayein ke woh achi tarah khushk hon."),
        ("Traditional Kashmiri embroidery is admired around the globe.", "روایتی کشمیری کڑھائی کو پوری دنیا میں قدر کی نگاہ سے دیکھا جاتا ہے۔", "Riwayati Kashmiri karhai ko poori dunya mein qadr ki nigah se dekha jata hai."),
        ("A clean white crisp dress shirt is a staple in every wardrobe.", "ایک صاف ستھری سفید قمیض ہر الماری کی بنیادی ضرورت ہوتی ہے۔", "Aik saaf suthri safaid qameez har almari ki bunyadi zaroorat hoti hai."),
        ("Dress with modesty, elegance, self-respect, and quiet confidence.", "حیا، وقار، خودداری اور اعتماد کے ساتھ لباس زیب تن کریں۔", "Haya, waqaar, khud-daari aur aitemad ke sath libaas zaib-e-tan karein."),
        ("These breathable socks prevent sweat and foot odor.", "یہ معیاری جرابیں پسینے اور پاؤں کی بو سے محفوظ رکھتی ہیں۔", "Yeh meyaari jurrabein paseenay aur paon ki boo se mahfooz rakhti hain."),
        ("He takes great care of his clothing and personal grooming.", "وہ اپنے لباس اور ذاتی بناؤ سنگھار کا بہت خیال رکھتا ہے۔", "Woh apne libaas aur zaati banav-singhar ka bohat khayal rakhta hai."),
        ("Confidence is what truly elevates any outfit you wear.", "آپ کا اعتماد ہی دراصل ہر لباس کو پرکشش اور باوقار بناتا ہے۔", "Aap ka aitemad hi dar-asal har libaas ko pur-kashish banata hai."),
        ("Wishing you a smart, stylish, and dignified appearance always!", "اللہ تعالیٰ آپ کے انداز کو ہمیشہ شاندار، باوقار اور پرکشش رکھے!", "Allah Ta'ala aap ke andaaz ko hamesha shandar aur ba-waqaar rakhay!")
    ]

    return [
        {"id": 24, "name": "Sports & Fitness", "urduName": "کھیل اور ورزش", "icon": "sports_cricket", "desc": "Cricket, football, gym workouts, jogging, and health.", "sentences": t24},
        {"id": 25, "name": "Movies & Entertainment", "urduName": "فلمیں اور تفریح", "icon": "whatshot", "desc": "Watching cinema, comedy shows, dramas, and entertainment.", "sentences": t25},
        {"id": 26, "name": "Music & Arts", "urduName": "موسیقی اور فنون", "icon": "favorite", "desc": "Traditional instruments, singing, classical music, and exhibitions.", "sentences": t26},
        {"id": 27, "name": "Clothes & Fashion", "urduName": "لباس اور فیشن", "icon": "checkroom", "desc": "Dressing style, fabrics, colors, and traditional wear.", "sentences": t27}
    ]
