# -*- coding: utf-8 -*-

def get_36_to_40():
    # 36. Climate, Environment & Nature
    t36 = [
        ("Planting indigenous trees helps combat severe air pollution and smog.", "مقامی درخت لگانا فضائی آلودگی اور اسموگ کے خاتمے میں مدد دیتا ہے۔", "Maqami darakht lagana fazai aaloodgi aur smog ke khatmay mein madad deta hai."),
        ("Global warming is causing Himalayan glaciers to melt at rapid rates.", "عالمی حدت کی وجہ سے ہمالیہ کے گلیشیئرز تیزی سے پگھل رہے ہیں۔", "Aalmi hiddat ki wajah se Himalaya ke glaciers taizi se pighal rahe hain."),
        ("We must reduce single-use plastic bags to protect our water bodies.", "آبی ذخائر کے تحفظ کے لیے یک بارگی پلاسٹک کے تھیلوں کو کم کرنا ہوگا۔", "Aabi zakhair ke tahaffuz ke liye plastic ke thelay kam karne hon ge."),
        ("Conserving tap water while washing dishes and brushing is vital.", "برتن دھوتے اور برش کرتے وقت پانی کی بچت کرنا بے حد ضروری ہے۔", "Bartan dhotay aur brush kartay waqt paani ki bachat zaroori hai."),
        ("Solar renewable energy reduces our dependence on fossil fuels.", "شمسی توانائی کا استعمال ایندھن پر ہمارا انحصار کم کرتا ہے۔", "Shamsi tawanaai ka istemal fuel par hamara inhisar kam karta hai."),
        ("Proper waste segregation allows effective recycling and composting.", "کوڑے کی درست درجہ بندی ری سائیکلنگ کو آسان اور ممکن بناتی ہے۔", "Kooray ki daraja-bandi recycling ko aasan aur mumkin banati hai."),
        ("Protecting endangered wildlife preserves the delicate ecological balance.", "نایاب جنگلی حیات کا تحفظ قدرتی ماحولیاتی توازن کو برقرار رکھتا ہے۔", "Nayaab jungli hayat ka tahaffuz qudrati tawazun ko barqarar rakhta hai."),
        ("The Margalla national park is home to hundreds of bird species.", "مارگلہ نیشنل پارک سینکڑوں اقسام کے پرندوں کا مسکن ہے۔", "Margalla national park sainkaron aqsam ke parindon ka maskan hai."),
        ("Industrial toxic waste must be treated before discharge into rivers.", "صنعتی زہریلے مواد کو دریاؤں میں ڈالنے سے پہلے صاف کرنا لازمی ہے۔", "Sanati zehreelay mawaad ko daryaoon mein daalnay se pehle saaf karein."),
        ("Nature provides enough for human need, but not for human greed.", "قدرت انسانی ضرورت پورا کرتی ہے لیکن لالچ کو نہیں۔", "Qudrat insani zaroorat poori karti hai lekin laalach ko nahi."),
        ("How can local communities implement urban rainwater harvesting?", "مقامی آبادی بارش کے پانی کو محفوظ بنانے کے منصوبے کیسے لگائے؟", "Maqami abaadi barish ke paani ko mahfooz kaisay banaye?"),
        ("Deforestation causes severe soil erosion and devastating floods.", "جنگلات کی کٹائی مٹی کے کٹاؤ اور شدید سیلابوں کا سبب بنتی ہے۔", "Janglaat ki kataai mitti ke katao aur sailaab ka sabab banti hai."),
        ("Switch off electric lights and fans when leaving an empty room.", "خالی کمرے سے نکلتے وقت لائٹس اور پنکھے بند کرنا معمول بنائیں۔", "Khaali kamray se nikaltay waqt lights aur pankhay band karein."),
        ("Composting kitchen vegetable scraps creates nutrient-rich soil.", "سبزیوں کے چھلکوں سے کھاد بنانا پودوں کے لیے بہترین خوراک ہے۔", "Sabziyon ke chilkon se khaad banana paudon ke liye behtareen hai."),
        ("Bicycle commuting reduces greenhouse gas emissions in crowded cities.", "شہروں میں سائیکل چلانا زہریلی گیسوں کے اخراج کو کم کرتا ہے۔", "Shehron mein cycle chalana zehreeli gason ke ikhraj ko kam karta hai."),
        ("Preserving mangrove forests along the coast protects against tsunamis.", "ساحلی تمر کے جنگلات کا تحفظ طوفانوں سے بچاؤ کا قدرتی ذریعہ ہے۔", "Sahili timmar ke janglaat toofanon se bachao ka qudrati zariya hain."),
        ("Clean and green Pakistan campaign encourages nationwide tree plantation.", "کلین اینڈ گرین پاکستان مہم ملک گیر شجرکاری کی حوصلہ افزائی کرتی ہے۔", "Clean and green Pakistan muhim shajar-kaari ki hausla-afzai karti hai."),
        ("Air quality index (AQI) readings reach hazardous levels in winter.", "سردیوں میں ہوا کے معیار کا انڈیکس خطرناک حد تک خراب ہو جاتا ہے۔", "Sardiyon mein hawa ke meyaar ka index khatarnaak hadd tak kharab hota hai."),
        ("Wear N95 protective masks during dense winter smog episodes.", "دھند اور اسموگ کے دنوں میں این 95 حفاظتی ماسک ضرور پہنیں۔", "Dhund aur smog ke dinon mein N95 mask zaroor pehnein."),
        ("Every individual holds a shared responsibility to protect Earth.", "زمین کی حفاظت کرنا ہم میں سے ہر فرد کی مشترکہ ذمہ داری ہے۔", "Zameen ki hifazat karna hum mein se har fard ki zimmedari hai."),
        ("Support local organic farmers who practice sustainable agriculture.", "قدرتی طریقوں سے کاشتکاری کرنے والے کسانوں کی حمایت کریں۔", "Qudrati tareeqon se kashtkari karne walay kisanon ki himayat karein."),
        ("Ocean plastic pollution poses a severe threat to marine turtles.", "سمندر میں پلاسٹک کا کچرا سمندری کچھوؤں کے لیے جان لیوا ہے۔", "Samandar mein plastic ka kachra kachhuwon ke liye jaan-lewa hai."),
        ("Teach school children the immense value of conserving water.", "اسکول کے بچوں کو پانی کی ایک ایک بوند بچانے کی اہمیت سکھائیں۔", "School ke bachon ko paani bachanay ki ahmiyat sikhayein."),
        ("Using energy-efficient LED light bulbs reduces electric power bills.", "بجلی بچانے والے ایل ای ڈی بلب بجلی کا بل کم کرتے ہیں۔", "Bijli bachanay walay LED bulbs bijli ka bill kam kartay hain."),
        ("The crisp autumn breeze signals the changing of the seasons.", "خزاں کی خنک ہوائیں موسم کے بدلنے کا خوبصورت پیغام دیتی ہیں۔", "Khizan ki khunak hawaein mausam ke badalnay ka paigham deti hain."),
        ("Drip irrigation systems optimize water delivery directly to roots.", "ڈرپ اریگیشن کا نظام پودوں کی جڑوں تک ضرورت کے مطابق پانی پہنچاتا ہے۔", "Drip irrigation system jarron tak munasib paani pohanchata hai."),
        ("Avoid burning crop stubble and trash in open public spaces.", "کھلے مقامات پر فصلوں کی باقیات اور کچرا جلانے سے پرہیز کریں۔", "Khulay maqamat par kachra jalanay se parhez karein."),
        ("Public transport infrastructure helps clear clogged urban highways.", "پبلک ٹرانسپورٹ سڑکوں سے ٹریفک کا رش کم کرنے میں مدد دیتی ہے۔", "Public transport sarakon se traffic ka rush kam karti hai."),
        ("Nature walks relieve mental anxiety and ground our spiritual focus.", "قدرت کی گود میں سیر ذہنی پریشانیوں کو مٹا کر سکون بخشتی ہے۔", "Qudrat ki godd mein sair zehni pareshani ko door karti hai."),
        ("Protect the planet today so our children inherit a healthy future.", "آج زمین کی حفاظت کریں تاکہ آنے والی نسلوں کا مستقبل محفوظ ہو۔", "Aaj zameen ki hifazat karein taakay naye bachon ka mustaqbil mahfooz ho."),
        ("The northern valleys of Swat and Hunza showcase breathtaking beauty.", "سوات اور ہنزہ کی شمالی وادیاں قدرت کا بے مثال حسن دکھاتی ہیں۔", "Swat aur Hunza ki shumali wadiyan qudrat ka be-misaal husn dikhati hain."),
        ("Installing rainwater catchment barrels collects gallons of free water.", "چھتوں پر بارش کا پانی جمع کرنے کے ڈرم لگانا پانی کا خرچ بچاتا ہے۔", "Chhaton par barish ka paani jama karne se bachat hoti hai."),
        ("Avoid dumping discarded motor oil down street storm drains.", "گاڑی کا پرانا موبل آئل گلی کی نالیوں میں ہرگز نہ بہائیں۔", "Gaari ka purana mobil oil naaliyon mein hargiz na bahayein."),
        ("Wild honeybees are crucial pollinators for global food supply.", "شہد کی مکھیاں فصلوں کی پیداوار کے لیے قدرت کا اہم ترین نظام ہیں۔", "Shehad ki makhiyan faslon ki paidaawar ke liye laazmi hain."),
        ("Adopt minimalist consumer habits to produce less daily waste.", "کم سے کم سامان خریدنے کی عادت روزانہ کچرے میں کمی لاتی ہے۔", "Kam saman khareednay ki aadat kachray mein kami laati hai."),
        ("The roaring river waters carve dramatic mountain canyons.", "دریا کا تیز پانی بلند و بالا پہاڑوں میں خوبصورت راستے تراشتا ہے۔", "Darya ka taiz paani paharon mein rasta tarashta hai."),
        ("Green rooftop gardens reduce urban heat island temperatures.", "چھتوں پر پودے لگانا عمارتوں کے درجہ حرارت کو ٹھنڈا رکھتا ہے۔", "Chhaton par pauday lagana imaarat ko thanda rakhta hai."),
        ("Say no to plastic straws and disposable plastic cutlery.", "پلاسٹک کے پائپ اور ڈسپوزایبل چمچوں کا استعمال بند کریں۔", "Plastic ke pipes aur disposable chamach band karein."),
        ("Cherish the gentle sound of falling rain on quiet rooftops.", "پرسکون راتوں میں چھت پر برستی بارش کی جھنکار کو محسوس کریں۔", "Pursukoon raaton mein barasti barish ki aawaz ko mehsoos karein."),
        ("A single majestic tree produces oxygen for four healthy adults.", "ایک بڑا درخت چار افراد کے لیے زندگی بخش آکسیجن پیدا کرتا ہے۔", "Aik barra darakht chaar afrad ke liye oxygen paida karta hai."),
        ("Eco-tourism respects local wilderness and traditional communities.", "ماحول دوست سیاحت مقامی جنگلی حیات اور ثقافت کا احترام کرتی ہے۔", "Mahool-dost siyahat maqami saqafat ka ihtiram karti hai."),
        ("Clean up all trash and food wrappers after family picnic outings.", "پکنک منانے کے بعد تمام کچرا تھیلے میں ڈال کر صفائی کا ثبوت دیں۔", "Picnic ke baad tamam kachra thelay mein daal kar saaf karein."),
        ("Rivers are the lifeblood of agricultural civilization.", "دریا زرعی تہذیب کی شہ رگ اور زندگی کی علامت ہیں۔", "Darya zar'ee tehzeeb ki sheh-rag aur zindagi ki alamat hain."),
        ("Embrace natural cotton, jute, and linen instead of synthetics.", "مصنوعی دھاگوں کے بجائے سوتی، پٹ سن اور روئی کے کپڑے چنیں۔", "Masnooi dhagon ke bajaye sooti aur jute ke kapray chunein."),
        ("Teach children to love, respect, and plant flowering saplings.", "بچوں کو پودوں سے محبت اور شجرکاری کی ترغیب دیں۔", "Bachon ko paudon se mohabbat aur shajar-kari ki targheeb dein."),
        ("The sunrise over snow-capped mountain peaks is breathtaking.", "برف پوش پہاڑی چوٹیوں پر طلوعِ آفتاب کا منظر دل موہ لیتا ہے۔", "Barf-posh chotiyaan par tulu-e-aaftaab ka manzar dil moh leta hai."),
        ("Wind power turbines generate clean zero-emission electricity.", "ہوائی پن چکیاں بغیر دھوئیں کے صاف بجلی پیدا کرتی ہیں۔", "Hawai chakkiyan saaf bijli paida karti hain."),
        ("Let us leave behind a greener, purer world for posterity.", "آئیں آنے والی نسلوں کے لیے ایک سرسبز اور صاف دنیا چھوڑ جائیں۔", "Aayein naye daur ke liye aik sarsabz dunya chorr jayein."),
        ("Sustainable living is an act of deep gratitude towards creation.", "ماحول کا خیال رکھنا خالق کی نعمتوں پر شکر گزاری کا عملی اظہار ہے۔", "Mahool ka khayal rakhna shukr-guzari ka amli izhaar hai."),
        ("May the green earth thrive with peace, abundant life, and harmony!", "اللہ تعالیٰ اس سرسبز زمین کو ہمیشہ شاداب اور پرامن رکھے!", "Allah Ta'ala is zameen ko hamesha shaadaab aur pursukoon rakhay!")
    ]

    # 37. Festivals & Celebrations
    t37 = [
        ("Eid Mubarak to you, your beloved family, and all near ones!", "آپ کو اور آپ کے اہل خانہ کو عید کی پرمسرت خوشیاں مبارک ہوں!", "Aap ko aur aap ke ahal-e-khana ko Eid Mubarak ho!"),
        ("May the blessed holy month of Ramadan bring peace and forgiveness.", "اللہ کرے رمضان کا بابرکت مہینہ بخشش اور امن کا پیغام لائے۔", "Allah karay Ramadan ka ba-barkat maheena bakhshish laye."),
        ("We are preparing sweet sheer khurma with milk, vermicelli, and dry fruits.", "ہم دودھ، سوئیوں اور میوہ جات کے ساتھ شیر خورمہ بنا رہے ہیں۔", "Hum doodh, siwaiyon aur mewajat se sheer khurma bana rahe hain."),
        ("Children eagerly wait to receive their Eid gifts and Eidi pocket money.", "بچے عیدی اور تحائف حاصل کرنے کا بے صبری سے انتظار کرتے ہیں۔", "Bachay eidi aur tahaif haasil karne ka intezar kartay hain."),
        ("Wishing you a blissful wedding anniversary full of enduring love.", "آپ کو شادی کی سالگرہ پر دلی مبارکباد اور ڈھیروں دعائیں۔", "Aap ko shadi ki salgirah par dili mubarakbaad aur duaein."),
        ("The colorful mehndi ceremony was filled with traditional songs and dances.", "مہندی کی تقریب روایتی گیتوں اور خوشیوں سے سجی ہوئی تھی۔", "Mehndi ki taqreeb riwayati geeton aur khushiyon se saji thi."),
        ("Happy birthday! May your upcoming year be filled with success.", "سالگرہ مبارک! دعا ہے کہ آپ کا اگلا سال کامیابیوں سے بھرپور ہو۔", "Salgirah mubarak! Dua hai ke agla saal kamyabiyon se bharpoor ho."),
        ("We exchanged delicious festive sweets and savory snacks with neighbors.", "ہم نے پڑوسیوں کے ساتھ مٹھائیاں اور لذیذ کھانے شیئر کیے۔", "Hum ne parosiyon ke sath mithaiyan aur khanay share kiye."),
        ("The whole bazaar is brightly illuminated with colorful fairy lights.", "پورا بازار رنگ برنگی برقی قمقموں کی روشنیوں سے جگمگا رہا ہے۔", "Poora bazaar rang barangi lighton se jagmaga raha hai."),
        ("Festivals provide a joyful opportunity to mend ties and forgive.", "تہوار دلوں کی دوریاں مٹانے اور ایک دوسرے کو معاف کرنے کا موقع ہیں۔", "Tehwaar dilon ki dooriyan mitanay aur maaf karne ka mauqa hain."),
        ("What are your family's special plans for the long Eid holiday?", "عید کی لمبی چھٹیوں پر آپ کے خاندان کا کیا خاص پروگرام ہے؟", "Eid ki chuttiyon par aap ke khandan ka kya khaas program hai?"),
        ("We performed the Eid congregational prayer at the grand mosque.", "ہم نے جامع مسجد میں عید کی باجماعت نماز ادا کی۔", "Hum ne jamia masjid mein Eid ki namaz ada ki."),
        ("Wishing our Christian brothers and sisters a very peaceful Christmas.", "ہمارے مسیحی بھائیوں اور بہنوں کو کرسمس کی خوشیاں مبارک ہوں۔", "Hamare Maseehi bhaiyon aur behnon ko Christmas mubarak ho."),
        ("May the arrival of the Islamic New Year bring unity and prosperity.", "نیا اسلامی سال پوری امت کے لیے اتحاد اور خوشحالی لائے۔", "Naya Islami saal ittehad aur khush-haali laye."),
        ("The wedding reception hall was decorated with fragrant white jasmine flowers.", "شادی کا ہال چنبیلی کے تازہ پھولوں کی خوشبو سے مہک رہا تھا۔", "Shadi ka hall chambeli ke taaza phoolon se mehak raha tha."),
        ("We baked a delicious double chocolate birthday cake for the party.", "ہم نے پارٹی کے لیے لذیذ چاکلیٹ کیک بیک کیا۔", "Hum ne party ke liye lazeez chocolate cake bake kiya."),
        ("Everyone embraced each other warmly with genuine smiles and affection.", "سب نے مسکراتے چہروں کے ساتھ ایک دوسرے کو گلے لگایا۔", "Sab ne muskuratay chehron ke sath aik doosray ko galay lagaya."),
        ("May your table be blessed with sumptuous feast and cherished guests.", "اللہ آپ کے دسترخوان کو لذیذ کھانوں اور پیاروں سے سجائے رکھے۔", "Allah aap ke dastarkhwan ko lazeez khanon se sajaye rakhay."),
        ("The young cousins played fun parlor games until late into the night.", "تمام کزنز نے رات گئے تک دلچسپ کھیل کھیلے اور ہنسی مذاق کیا۔", "Tamam cousins ne raat gaye tak dilchasp khel khailay."),
        ("True joy multiplies when shared with those less privileged around us.", "اصل خوشی ضرورت مندوں اور غریبوں کو شامل کرنے سے دوبالا ہوتی ہے۔", "Asal khushi zaroorat-mandon ko shamil karne se barhti hai."),
        ("We distributed food rations and warm clothes to needy families.", "ہم نے مستحق خاندانوں میں راشن اور گرم کپڑے تقسیم کیے۔", "Hum ne mustahiq khandanun mein rashan aur kapray baantay."),
        ("The Independence Day fireworks lit up the midnight sky in emerald green.", "یوم آزادی پر آتش بازی نے رات کے آسمان کو سبز رنگ میں رنگ دیا۔", "Youm-e-Azadi par aatish-baazi ne aasmaan ko chamka diya."),
        ("Singing the national anthem fills every Pakistani heart with pride.", "قومی ترانہ سنتے ہی ہر پاکستانی کا سر فخر سے بلند ہو جاتا ہے۔", "Qaumi tarana suntay hi har Pakistani ka dil fakhr se bhar jata hai."),
        ("May peace, harmony, and progress shine over our beloved nation.", "اللہ ہمارے پیارے وطن کو ہمیشہ امن، ترقی اور خوشحالی عطا کرے۔", "Allah hamare watan ko hamesha aman aur taraqi ata karay."),
        ("The family gathered for a delicious Iftar feast at sunset.", "غروبِ آفتاب پر پورا خاندان لذیذ افطاری کے لیے اکٹھا ہوا۔", "Ghuroob-e-aaftaab par poora khandan iftari ke liye ikattha hua."),
        ("Crispy vegetable pakoras and fruit chaat are staples of Iftar.", "پکوڑے اور فروٹ چاٹ ہمارے روایتی دسترخوان کی جان ہیں۔", "Pakorray aur fruit chaat hamari iftari ki jaan hain."),
        ("Lighting traditional earthen diyas brings warmth to autumn evenings.", "مٹی کے روایتی دیئے جلانا شام کو ایک خوبصورت روپ دیتا ہے۔", "Mitti ke deeyay jalana shaam ko khubsurat roop deta hai."),
        ("Hearty congratulations on the birth of your newborn baby boy!", "اللہ نے آپ کو چاند سا بیٹا عطا کیا ہے، بہت بہت مبارک ہو!", "Allah ne aap ko beta ata kiya hai, bohat mubarak ho!"),
        ("May the newborn baby grow up in radiant health, faith, and wisdom.", "اللہ بچے کو لمبی عمر، بہترین صحت اور روشن نصیب عطا کرے۔", "Allah bachay ko lambi umar aur roshan naseeb ata karay."),
        ("Gathering around our grandparents for traditional stories is priceless.", "دادا دادی کے گرد بیٹھ کر کہانیاں سننا انمول وقت ہوتا ہے۔", "Dada dadi ke gird baith kar kahaniyan sunna anmol hai."),
        ("We sent lovely customized gift hampers to our corporate clients.", "ہم نے اپنے کلائنٹس کو خوبصورت تحائف کے ٹوکرے بھیجے۔", "Hum ne apne clients ko khubsurat tahaif ke baskets bhejay."),
        ("The groom looked regal in his hand-tailored off-white Sherwani.", "دولہا اپنے کڑھائی والے سفید لباس میں بہت باوقار لگ رہا تھا۔", "Dulha apne safaid libaas mein bohat ba-waqaar lag raha tha."),
        ("The bride's intricate henna tattoo designs were breathtakingly delicate.", "دلہن کے ہاتھوں پر لگی باریک مہندی کے ڈیزائن لاجواب تھے۔", "Dulhan ke haathon par lagi mehndi ke design la-jawab thay."),
        ("May your new matrimonial journey be blessed with endless mutual trust.", "اللہ آپ دونوں کے نئے ازدواجی سفر کو محبت اور اعتماد سے بھر دے۔", "Allah aap dono ke azdawaji safar ko mohabbat se bhar de."),
        ("We held a spiritual Milad gathering with devotional poetry recitations.", "ہم نے گھر میں بابرکت محفلِ میلاد اور نعت خوانی سجائی۔", "Hum ne ghar mein ba-barkat Mehfil-e-Milad sajayi."),
        ("May divine blessings illuminate your heart with tranquility.", "اللہ تعالیٰ کا کرم اور سکون آپ کے دل کو منور رکھے۔", "Allah Ta'ala ka karam aur sukoon aap ke dil ko munawwar rakhay."),
        ("The children put on a colorful drama performance at the school annual day.", "بچوں نے اسکول کے سالانہ فنکشن پر رنگارنگ ٹیبلو پیش کیا۔", "Bachon ne school ke annual function par tableaus pesh kiye."),
        ("Parents applauded proudly as their kids received achievement awards.", "بچوں کے انعامات جیتنے پر والدین نے فخر سے تالیاں بجائیں۔", "Bachon ke inaam jeetnay par walidain ne taaliyan bajayein."),
        ("Celebrating cultural heritage keeps our rich traditions alive.", "اپنی تہذیب اور روایات کا جشن منانا ورثے کو زندہ رکھتا ہے۔", "Apni tehzeeb ka jashan manana virsay ko zinda rakhta hai."),
        ("May the light of joy dispel all shadows of grief from your home.", "اللہ کرے خوشیوں کا اجالا آپ کے گھر سے ہر غم کو دور کر دے۔", "Allah karay khushiyon ka ujala har gham ko door kar de."),
        ("We toasted with fresh pomegranate and peach sparkling juice.", "ہم نے انار اور آڑو کے تازہ شربت سے تقریب کا آغاز کیا۔", "Hum ne anaar aur aarroo ke taaza sharbat se aaghaz kiya."),
        ("The family reunion brought together relatives from three continents.", "خاندانی ملن نے تین مختلف براعظموں سے رشتہ داروں کو جوڑ دیا۔", "Khandani milan ne mukhtalif mulkon se rishtedaron ko jorr diya."),
        ("Old photo albums opened a floodgate of joyful nostalgic memories.", "پرانی تصاویر نے ماضی کی خوبصورت اور حسین یادیں تازہ کر دیں۔", "Purani tasaveer ne maazi ki haseen yaadein taaza kar dein."),
        ("Laughter of happy children is the sweetest music in the universe.", "بچوں کے قہقہے اور مسکراہٹیں دنیا کا سب سے پیارا نغمہ ہیں۔", "Bachon ke qehqahay dunya ka sab se pyara naghma hain."),
        ("Cherish every fleeting milestone with presence, humility, and gratitude.", "ہر خوشی کے موقع پر عاجزی اور شکر گزاری کے ساتھ حاضر رہیں۔", "Har khushi ke mauqa par aajzi aur shukr ke sath rahein."),
        ("We tied green and white balloons across the entrance porch.", "ہم نے داخلی دروازے پر سبز اور سفید غبارے سجائے۔", "Hum ne entrance par sabz aur safaid ghubaray sajaye."),
        ("May your homes always resonate with heartfelt congratulations!", "اللہ کرے آپ کا گھر ہمیشہ مبارکبادوں اور خوشیوں سے گونجتا رہے!", "Allah karay aap ka ghar hamesha mubarakbaadon se goonjay!"),
        ("Sending you warm wishes for a prosperous and jubilant holiday season!", "آپ کے لیے چھٹیوں کے پرمسرت موسم پر نیک تمناؤں کا تحفہ!", "Aap ke liye chuttiyon par naik tamannaon ka tohfa!"),
        ("Festive occasions remind us of what matters most: love and family.", "تہوار ہمیں یاد دلاتے ہیں کہ اصل دولت محبت اور خاندان ہے۔", "Tehwaar yaad dilatay hain ke asal daulat mohabbat aur khandan hai."),
        ("May all your celebrations be crowned with peace, barakah, and bliss!", "اللہ تعالیٰ آپ کی تمام خوشیوں میں برکت، امن اور مسرتیں عطا فرمائے!", "Allah Ta'ala aap ki tamam khushiyon mein barkat ata farmaye!")
    ]

    # 38. Relationships & Family
    t38 = [
        ("Honoring and caring for aging parents is the highest moral virtue.", "بوڑھے والدین کی خدمت اور ادب سب سے بڑی نیکی ہے۔", "Boorhay walidain ki khidmat aur adab sab se barri naiki hai."),
        ("A warm, supportive family is a person's safest refuge in storms.", "ایک پیار کرنے والا خاندان زندگی کے طوفانوں میں سب سے محفوظ پناہ گاہ ہے۔", "Aik pyar karne wala khandan sab se mahfooz panah-gah hai."),
        ("Open, honest communication builds unbreakable trust between siblings.", "کھلی اور سچی بات چیت بہن بھائیوں میں اٹوٹ اعتماد پیدا کرتی ہے۔", "Khuli aur sachi baat cheet behan bhaiyon mein aitemad banati hai."),
        ("Patience and empathy are the pillars of a peaceful marriage.", "صبر اور باہمی احساس ایک پرسکون ازدواجی زندگی کے ستون ہیں۔", "Sabr aur baahmi ehsas pursukoon shadi shuda zindagi ke sutoon hain."),
        ("Spend quality screen-free time talking with your growing children daily.", "اپنے بڑھتے ہوئے بچوں کے ساتھ روزانہ بغیر موبائل کے وقت گزاریں۔", "Apne bachon ke sath rozana mobile ke baghair waqt guzarein."),
        ("Grandparents pass down timeless wisdom, resilience, and heritage.", "دادا دادی بچوں کو حکمت، اخلاق اور خاندانی ورثہ سکھاتے ہیں۔", "Dada dadi bachon ko hikmat aur saqafat sikhatay hain."),
        ("Always forgive family misunderstandings with a generous heart.", "خاندانی غلط فہمیوں کو ہمیشہ بڑے دل کے ساتھ معاف کر دیا کریں۔", "Khandani ghalt-fehmiyon ko hamesha baray dil se maaf karein."),
        ("Express gratitude to your spouse for the little unseen efforts they make.", "اپنے جیون ساتھی کی چھوٹی چھوٹی کوششوں پر ان کا شکریہ ادا کریں۔", "Apne jeevan saathi ki koshishon par un ka shukriya ada karein."),
        ("Childhood memories shared with brothers and sisters stay forever.", "بہن بھائیوں کے ساتھ گزرا بچپن زندگی بھر دل میں زندہ رہتا ہے۔", "Behan bhaiyon ke sath guzra bachpan hamesha yaad rehta hai."),
        ("Love is not merely an emotion; it is an everyday conscious commitment.", "محبت صرف ایک جذبہ نہیں بلکہ روزانہ نبھایا جانے والا وعدہ ہے۔", "Mohabbat sirf aik jazba nahi balkay rozana ka wada hai."),
        ("How do you maintain balance between demanding career and family time?", "آپ اپنے مصروف کیریئر اور خاندانی وقت میں کیسے توازن رکھتے ہیں؟", "Aap career aur family waqt mein kaisay tawazun rakhtay hain?"),
        ("Establish regular family dinners where everyone shares their day.", "روزانہ رات کا کھانا سب اکٹھے کھائیں اور دن کے حالات بتائیں۔", "Rozana raat ka khana sab ikatthay khayein aur baat karein."),
        ("Listen to your teenager without immediately judging or scolding.", "اپنے نوجوان بچوں کی بات بغیر تنقید کیے پہلے غور سے سنیں۔", "Apne naujawan bachon ki baat baghair tanqeed suniye."),
        ("True friendship is a rare treasure nurtured across decades.", "سچی دوستی ایک نایاب موتی ہے جو برسوں کی مخلصانہ وفا سے بنتا ہے۔", "Sachi dosti aik nayaab moti hai jo saalon mein banti hai."),
        ("Support your partner's personal dreams and intellectual pursuits.", "اپنے جیون ساتھی کے خوابوں اور مقاصد کی ہمیشہ حوصلہ افزائی کریں۔", "Apne partner ke khwabon aur maqasid ki himayat karein."),
        ("Never raise your voice in anger when speaking to your mother.", "اپنی والدہ کے سامنے غصے میں آواز کبھی اونچی مت کریں۔", "Apni walida ke samnay ghussay mein aawaz oonchi mat karein."),
        ("A father's quiet sacrifices are the foundation of children's success.", "باپ کی خاموش قربانیاں ہی بچوں کی کامیابی کی بنیاد ہوتی ہیں۔", "Baap ki khamosh qurbaniyan bachon ki bunyad hoti hain."),
        ("Teach boys and girls emotional resilience and mutual respect.", "بیٹوں اور بیٹیوں کو باہمی عزت، برداشت اور خودداری سکھائیں۔", "Beton aur betiyon ko izzat, bardasht aur saleeqa sikhayein."),
        ("Celebrate each other's triumphs as if they were your own.", "اپنوں کی کامیابیوں پر ایسے خوش ہوں جیسے وہ آپ کی اپنی ہوں۔", "Apnon ki kamyabi par dil se khush hon."),
        ("A peaceful home is built on mutual respect and shared responsibilities.", "ایک پرسکون گھر باہمی احترام اور کام بانٹنے سے بنتا ہے۔", "Aik pursukoon ghar baahmi ihtiram se banta hai."),
        ("Help your siblings when they stumble without boasting about it.", "جب بہن بھائی مشکل میں ہوں تو بغیر احسان جتائے مدد کریں۔", "Jab behan bhai mushkil mein hon to baghair ahsan madad karein."),
        ("A mother's prayers can move mountains and alter destinies.", "ماں کی دعائیں تقدیر بدلنے کی طاقت رکھتی ہیں۔", "Maa ki duaein taqdeer badalnay ki taaqat rakhti hain."),
        ("Take your family on peaceful weekend nature walks and outings.", "ویک اینڈ پر خاندان کے ساتھ قدرتی اور پرسکون مقامات پر جائیں۔", "Weekend par family ke sath pursukoon jaghon par jayein."),
        ("Do not let petty financial disputes poison sacred family bonds.", "چھوٹے مالی جھگڑوں کو مقدس خاندانی رشتوں پر حاوی مت ہونے دیں۔", "Chhotay maali jhagron ko rishton par haawi mat honay dein."),
        ("Teach youngsters the beauty of greeting elders with adab and salam.", "نوجوانوں کو بزرگوں کو ادب سے سلام کرنے کا سلیقہ سکھائیں۔", "Naujawanon ko bazurgon ko adab se salam karna sikhayein."),
        ("Kind words within home walls cost nothing but create priceless peace.", "گھر کے اندر کہے گئے میٹھے بول انمول سکون لاتے ہیں۔", "Ghar ke andar bolay gaye meethay bol sukoon laatay hain."),
        ("Cherish the moments you have today with loved ones unconditionally.", "اپنے پیاروں کے ساتھ موجود آج کے ہر لمحے کی دل سے قدر کریں۔", "Apne pyaron ke sath maujood har lamhay ki qadr karein."),
        ("Reaching out to an estranged relative brings profound blessings.", "ناراض رشتہ دار کو منا لینا زندگی میں بے پناہ برکت لاتا ہے۔", "Naraaz rishtedaar ko mana lena barkat laata hai."),
        ("A solid marriage is two imperfect souls refusing to give up on each other.", "کامیاب شادی دو انسانوں کا ایک دوسرے کا ساتھ نبھانے کا عزم ہے۔", "Kamyab shadi aik doosray ka sath nibhanay ka azm hai."),
        ("Children learn far more from what parents do than what they preach.", "بچے والدین کی نصیحتوں سے زیادہ ان کے عمل سے سیکھتے ہیں۔", "Bachay walidain ke amal se zyada seekhtay hain."),
        ("Encourage your children to pursue education with curiosity and joy.", "بچوں کو شوق اور خوشی کے ساتھ علم حاصل کرنے کی ترغیب دیں۔", "Bachon ko shauq ke sath ilm haasil karne ki targheeb dein."),
        ("Express your love verbally; do not leave it unspoken and hidden.", "اپنی محبت کا اظہار الفاظ سے کریں، اسے دل میں چھپا کر نہ رکھیں۔", "Apni mohabbat ka izhaar alfaaz se karein, chhupa kar na rakhein."),
        ("A warm hug and listening ear can heal a child's broken day.", "پیار سے گلے لگانا اور بات سننا بچے کا دکھ دور کر دیتا ہے۔", "Pyar se galay lagana bachay ka dukh door kar deta hai."),
        ("Respect your spouse's privacy and individual personal space.", "اپنے ساتھی کی ذاتی زندگی اور اسپیس کا ہمیشہ احترام کریں۔", "Apne saathi ki zaati zindagi ka ihtiram karein."),
        ("Family traditions create a comforting sense of shared identity.", "خاندانی روایات بچوں میں تحفظ اور تعلق کا احساس پیدا کرتی ہیں۔", "Khandani riwayaat bachon mein tahaffuz ka ehsas banati hain."),
        ("Keep toxic external gossip far away from your family discussions.", "باہر کی منفی باتوں اور غیبت کو اپنے گھر سے دور رکھیں۔", "Bahar ki manfi baton aur gheebat ko ghar se door rakhein."),
        ("Be the first to apologize when an argument escalates at home.", "جب گھر میں تکرار بڑھے تو معافی مانگنے میں پہل کریں۔", "Jab ghar mein takraar barhay to maafi maangnay mein pehal karein."),
        ("True nobility lies in treating your own family with utmost gentleness.", "سب سے بہترین انسان وہ ہے جو اپنے اہل و عیال کے لیے بہترین ہو۔", "Behtareen insaan woh hai jo apne ahal-e-khana ke liye behtareen ho."),
        ("Remember to call relatives living far away in distant cities.", "دور دراز شہروں میں مقیم رشتہ داروں کو فون کر کے خیریت پوچھیں۔", "Door shehron mein muqeem rishtedaron ki khairiyat poochein."),
        ("A united family can weather any economic storm together.", "ایک متحد خاندان ہر قسم کی معاشی تنگی کا مقابلہ کر سکتا ہے۔", "Aik muttahid khandan har mushkil ka muqabla kar sakta hai."),
        ("Create daily tech-free dinner routines to foster eye contact.", "کھانے کے وقت موبائل دور رکھ کر ایک دوسرے سے بات کریں۔", "Khanay ke waqt mobile door rakh kar baat karein."),
        ("Praise your children's moral character more than their grades.", "بچوں کے نمبرز سے زیادہ ان کے اچھے اخلاق اور کردار کی تعریف کریں۔", "Bachon ke achay ikhlaaq aur kirdaar ki tareef karein."),
        ("A peaceful household is the greatest earthly treasure one can possess.", "ایک پرسکون گھر دنیا کی سب سے بڑی دولت اور نعمت ہے۔", "Aik pursukoon ghar dunya ki sab se barri nemat hai."),
        ("Forgiveness is the glue that mends broken relationships over time.", "معاف کرنا وہ مرہم ہے جو ٹوٹے ہوئے رشتوں کو جوڑ دیتا ہے۔", "Maaf karna woh marham hai jo rishton ko jorr deta hai."),
        ("Value elderly family members and consult them on major life decisions.", "بزرگوں کی قدر کریں اور اہم فیصلوں میں ان سے مشورہ لیں۔", "Bazurgon ki qadr karein aur ahem faislon mein mashwara lein."),
        ("The bond between a brother and sister is filled with playful care.", "بہن بھائی کا رشتہ شرارتوں اور سچی فکر کا خوبصورت سنگم ہے۔", "Behan bhai ka rishta shararton aur fikr ka sangam hai."),
        ("Never compare one child unfavorably against another sibling.", "ایک بچے کا دوسرے سے منفی موازنہ کبھی مت کریں۔", "Aik bachay ka doosray se manfi mawazna mat karein."),
        ("Love, laughter, and prayer are the true foundation of a blessed home.", "محبت، خوشی اور دعائیں ہی برکت والے گھر کی اصل بنیاد ہیں۔", "Mohabbat, khushi aur duaein hi ba-barkat ghar ki bunyad hain."),
        ("Cherish every single day with the people you love most dearly.", "جن سے آپ محبت کرتے ہیں ان کے ساتھ ہر دن کو غنیمت جانیں۔", "Jin se aap mohabbat kartay hain un ke sath har din ki qadr karein."),
        ("May your family be forever guarded by mutual affection and peace!", "اللہ تعالیٰ آپ کے خاندان کو باہمی الفت اور دائمی امن عطا فرمائے!", "Allah Ta'ala aap ke khandan ko hamesha pursukoon rakhay!")
    ]

    # 39. Work Ethics & Office Culture
    t39 = [
        ("Punctuality demonstrates professionalism, reliability, and respect.", "وقت کی پابندی پیشہ ورانہ مہارت، اعتماد اور احترام کی علامت ہے۔", "Waqt ki pabandi paishawarana maharat aur aitemad ki alamat hai."),
        ("Clear communication eliminates costly misunderstandings at work.", "کھلی اور واضح بات چیت کام کی جگہ پر غلط فہمیوں کو دور کرتی ہے۔", "Wazeh baat cheet kaam ki jagah par ghalt-fehmiyon ko door karti hai."),
        ("We need to set realistic milestones to meet the project deadline.", "پروجیکٹ کی ڈیڈ لائن پوری کرنے کے لیے قابلِ عمل اہداف بنائیں۔", "Project ki deadline poori karne ke liye ahdaaf banayein."),
        ("Constructive collaboration between departments drives organizational growth.", "محکموں کے درمیان باہمی تعاون ادارے کی ترقی کا ضامن ہے۔", "Sho'bon ke darmiyan baahmi ta'awun idaray ki taraqi ka zamin hai."),
        ("Maintain highest standards of professional integrity and confidentiality.", "پیشہ ورانہ دیانت داری اور معلومات کے راز کو ہمیشہ برقرار رکھیں۔", "Paishawarana dyanat-dari aur raazdaari ko barqarar rakhein."),
        ("Always deliver on commitments made to team members and clients.", "ٹیم کے ارکان اور کلائنٹس سے کیے گئے وعدوں کو ہمیشہ پورا کریں۔", "Team aur clients se kiye gaye wadon ko hamesha poora karein."),
        ("A constructive leader empowers team members to achieve their peak.", "ایک بہترین رہنما ٹیم کے ارکان کی صلاحیتوں کو نکھارتا ہے۔", "Aik behtareen rehnuma team ki salahiyaton ko nikharta hai."),
        ("Active listening in meetings shows respect for colleagues' perspectives.", "میٹنگز میں دوسروں کی بات غور سے سننا احترام کا ثبوت ہے۔", "Meetings mein doosron ki baat ghaur se sunna ihtiram ka saboot hai."),
        ("Embrace healthy feedback as an opportunity for continuous personal growth.", "تعمیری تنقید کو ہمیشہ اپنی اصلاح اور ترقی کا ذریعہ سمجھیں۔", "Tameeri tanqeed ko hamesha apni taraqi ka zariya samjhein."),
        ("A clean and organized work desk promotes razor-sharp mental focus.", "صاف ستھری میز ذہن کو یکسو اور کام پر مرکوز رکھتی ہے۔", "Saaf suthri maiz zehan ko kaam par markooz rakhti hai."),
        ("How do we prioritize incoming critical tasks during high-stress weeks?", "زیادہ دباؤ والے دنوں میں اہم کاموں کو کس طرح ترجیح دی جائے؟", "Zyada dabao walay dinon mein ahem kamon ko kaisay tarjeeh dein?"),
        ("Use the Eisenhower Matrix to categorize urgent versus important work.", "ضروری اور اہم کاموں میں فرق کرنے کے لیے منصوبہ بندی کریں۔", "Zaroori aur ahem kamon mein farq karne ke liye plan banayein."),
        ("Send concise, professional emails with clear action items and deadlines.", "واضح نکات اور ڈیڈ لائنز کے ساتھ جامع اور مختصر ای میلز لکھیں۔", "Wazeh nukat aur deadlines ke sath mukhtasir emails likhein."),
        ("Always proofread reports before submitting them to executive management.", "اعلیٰ انتظامیہ کو بھیجنے سے پہلے رپورٹس کو دوبارہ ضرور پڑھیں۔", "Management ko bhejnay se pehle reports zaroor check karein."),
        ("Take brief five-minute screen breaks to refresh eyes and maintain posture.", "آنکھوں اور کمر کو آرام دینے کے لیے کام کے دوران مختصر وقفے لیں۔", "Aankhon aur kamar ke aaram ke liye mukhtasir waqfay lein."),
        ("Respect workplace diversity and foster an inclusive, fair atmosphere.", "کام کی جگہ پر تمام لوگوں کا احترام کریں اور مساوات قائم رکھیں۔", "Kaam ki jagah par tamam logon ka ihtiram karein."),
        ("Never engage in toxic office politics or spread malicious rumors.", "دفتری سیاست اور منفی سازشوں سے خود کو ہمیشہ دور رکھیں۔", "Daftari siyasat aur manfi saazishon se hamesha door rahein."),
        ("Celebrate team achievements and give genuine credit where it is due.", "ٹیم کی کامیابیوں کا جشن منائیں اور اصل محنت کش کو کریڈٹ دیں۔", "Team ki kamyabi ka jashan manayein aur credit dein."),
        ("Proactive problem solvers are the most valuable assets to any company.", "مسائل کے فوری اور مثبت حل تلاش کرنے والے لوگ ادارے کا سرمایہ ہیں۔", "Masail ka hal dhoondnay walay log idaray ka sarmaya hain."),
        ("Work-life balance prevents burnout and sustains long-term passion.", "کام اور زندگی میں توازن تھکن سے بچاتا ہے اور کارکردگی بڑھاتا ہے۔", "Kaam aur zindagi mein tawazun thakan se bachata hai."),
        ("Prepare the meeting agenda in advance and distribute it to attendees.", "میٹنگ کا ایجنڈا پہلے سے تیار کر کے تمام شرکاء کو بھیجیں۔", "Meeting ka agenda pehle se tayar kar ke sab ko bhejein."),
        ("Keep virtual zoom calls focused, structured, and strictly on time.", "آن لائن ویڈیو میٹنگز کو منظم، بامقصد اور وقت پر ختم کریں۔", "Online video meetings ko munazzam aur waqt par khatam karein."),
        ("Document key decisions and share meeting minutes within twenty-four hours.", "میٹنگ کے اہم فیصلوں اور نوٹس کو چوبیس گھنٹے میں شیئر کریں۔", "Meeting ke ahem faislon ke notes 24 ghantay mein bhejein."),
        ("Address conflicts directly, calmly, and privately with empathy.", "اختلافات کو پرسکون انداز میں اور تنہائی میں بات کر کے سلجھائیں۔", "Ikhtilaafaat ko pursukoon andaaz mein akele mein hal karein."),
        ("Mentoring junior colleagues strengthens the collective team capability.", "نئے عملے کی رہنمائی کرنا پوری ٹیم کی طاقت کو بڑھاتا ہے۔", "Naye amlay ki rehnumai karna poori team ko mazboot karta hai."),
        ("Continuous upskilling ensures relevance in rapidly evolving industries.", "نئی مہارتیں سیکھنا آپ کو جدید دور کی ضروریات سے ہم آہنگ رکھتا ہے۔", "Nayi maharatein seekhna aap ko jadeed daur se jurra rakhta hai."),
        ("Admit mistakes honestly and propose immediate corrective solutions.", "اپنی غلطی کا کھلے دل سے اعتراف کریں اور فوری حل پیش کریں۔", "Apni ghalti ka aiteeraaf karein aur fauri hal pesh karein."),
        ("Honesty builds an unshakeable reputation that outlasts any job title.", "دیانت داری ایسا وقار بناتی ہے جو عہدوں سے زیادہ دیرپا ہوتا ہے۔", "Dyanat-dari aisa waqaar banati hai jo hamesha rehta hai."),
        ("Set clear, measurable quarterly Key Performance Indicators (KPIs).", "تین ماہ کے واضح اور ناپے جانے والے اہداف مقرر کریں۔", "Teen maah ke wazeh aur measurable ahdaaf muqarrar karein."),
        ("A culture of gratitude and psychological safety fuels innovation.", "شکر گزاری اور تحفظ کا ماحول نئی تخلیقات کو جنم دیتا ہے۔", "Shukr-guzari aur tahaffuz ka mahaul nayi soch ko janam deta hai."),
        ("Always dress professionally according to your company's dress code.", "ہمیشہ اپنے ادارے کے ضابطہ لباس کے مطابق باوقار کپڑے پہنیں۔", "Hamesha apne idaray ke dress code ke mutabiq libaas pehnein."),
        ("Protect corporate intellectual property, source code, and client lists.", "کمپنی کے راز، ڈیٹا، کوڈ اور کلائنٹس کی معلومات محفوظ رکھیں۔", "Company ke data, code aur clients ki maloomat mahfooz rakhein."),
        ("Be adaptable and resilient when project requirements shift suddenly.", "جب منصوبے کے تقاضے بدلیں تو لچک اور ہمت کا مظاہرہ کریں۔", "Jab project ke taqazay badlein to lachak aur himmat dikhayein."),
        ("Praise colleagues in public and offer critical suggestions in private.", "تعریف سب کے سامنے کریں اور اصلاحی مشورہ ہمیشہ اکیلے میں دیں۔", "Tareef sab ke samnay karein aur mashwara akele mein dein."),
        ("Maintain emotional composure during challenging corporate crises.", "بحران کے وقت اپنے اعصاب پر قابو رکھیں اور پرسکون رہیں۔", "Bohraan ke waqt apne a'asaab par qaabu rakhein aur pursukoon rahein."),
        ("Delegate tasks effectively according to team members' core strengths.", "ٹیم ارکان کی صلاحیتوں کو دیکھ کر کام تقسیم کریں۔", "Team ki salahiyaton ko dekh kar kaam taqseem karein."),
        ("Respect out-of-office boundaries and avoid sending late-night emails.", "کام کے اوقات کے بعد دیر رات پیغامات بھیجنے سے گریز کریں۔", "Kaam ke auqaat ke baad dair raat messages bhejnay se bachein."),
        ("Keep corporate communication professional, transparent, and courteous.", "دفتری رابطوں کو ہمیشہ پیشہ ورانہ، شفاف اور شائستہ رکھیں۔", "Daftari rabton ko hamesha paishawarana aur shaista rakhein."),
        ("Cultivate a growth mindset where challenges are viewed as lessons.", "ایسی سوچ اپنائیں جہاں ہر مشکل کو سیکھنے کا موقع سمجھا جائے۔", "Aisi soch apnayein jahan har mushkil ko sabaq samjha jaye."),
        ("High standards of work ethic earn lifelong respect from industry peers.", "محنت اور دیانت داری آپ کو انڈسٹری میں ہمیشہ معزز رکھتی ہے۔", "Mehnat aur dyanat-dari aap ko hamesha moazzaz rakhti hai."),
        ("Ensure safety protocols are strictly observed in industrial setups.", "فیکٹریوں میں حفاظتی قوانین کی سختی سے پابندی کروائیں۔", "Factories mein hifazati qawaneen par sakhti se amal karwayein."),
        ("Organize team building workshops to strengthen interpersonal ties.", "ٹیم میں اتحاد اور دوستی بڑھانے کے لیے ورکشاپس کروائیں۔", "Team mein ittehad barhanay ke liye workshops karwayein."),
        ("Keep your corporate LinkedIn profile updated with recent credentials.", "اپنی پروفائل کو تازہ ترین کامیابیوں سے اپ ٹو ڈیٹ رکھیں۔", "Apni profile ko taza tareen kamyabiyon se update rakhein."),
        ("Clear documentation enables smooth knowledge transfer to successors.", "تحریری ریکارڈ کام کو دوسروں کے لیے سنبھالنا آسان بنا دیتا ہے۔", "Tehreeri record kaam ko doosron ke liye aasan banata hai."),
        ("Take pride in the craftsmanship and quality of your daily output.", "اپنے روزمرہ کے کام کے معیار پر ہمیشہ فخر کریں۔", "Apne rozmarrah ke kaam ke meyaar par hamesha fakhr karein."),
        ("Be a solution provider rather than a constant complainer.", "مسلسل شکایات کرنے کے بجائے مسائل کا حل پیش کرنے والے بنیں۔", "Musalsal shikayaat ke bajaye masail ka hal pesh karne walay banein."),
        ("Gratitude for employment fuels enthusiasm and dedicated productivity.", "ملازمت پر شکر گزاری کام میں لگن اور برکت پیدا کرتی ہے۔", "Rozgar par shukr-guzari kaam mein lagan aur barkat laati hai."),
        ("Collaboration always triumphs over selfish cutthroat competition.", "مل جل کر کام کرنا خود غرضانہ مقابلے پر ہمیشہ بھاری رہتا ہے۔", "Mil-jul kar kaam karna muqablay par hamesha bhaari rehta hai."),
        ("Thank you for your exceptional professionalism and dedication.", "آپ کی شاندار محنت اور پیشہ ورانہ لگن کا تہہ دل سے شکریہ۔", "Aap ki shandar mehnat aur paishawarana lagan ka bohat shukriya."),
        ("May your professional career reach stellar heights of excellence!", "اللہ تعالیٰ آپ کے کیریئر کو غیر معمولی بلندیوں اور کامیابیوں سے نوازے!", "Allah Ta'ala aap ke career ko bulandiyon se nawazay!")
    ]

    # 40. Freelancing & Remote Work
    t40 = [
        ("Remote freelancing offers unparalleled location and schedule freedom.", "فری لانسنگ کسی بھی جگہ اور مرضی کے وقت پر کام کی آزادی دیتی ہے۔", "Freelancing kisi bhi jagah aur waqt par kaam ki azaadi deti hai."),
        ("Building a compelling portfolio is essential to attract top clients.", "بہترین کلائنٹس کو متوجہ کرنے کے لیے ایک مضبوط پورٹ فولیو بنائیں۔", "Behtareen clients ke liye aik mazboot portfolio banayein."),
        ("How do I write winning proposals on Upwork and Fiverr platforms?", "میں اپ ورک اور فائیور پر کامیاب پروپوزل کیسے لکھوں؟", "Mein Upwork aur Fiverr par kamyab proposals kaisay likhoon?"),
        ("Personalize every proposal and directly address client pain points.", "ہر پروپوزل کلائنٹ کے مسئلے کے حل کے مطابق الگ لکھیں۔", "Har proposal client ke maslay ke mutabiq alag likhein."),
        ("Always deliver projects before deadlines to exceed client expectations.", "کلائنٹ کی توقعات سے بڑھ کر کام ڈیڈ لائن سے پہلے مکمل کریں۔", "Client ki tawaqqoaat se barh kar kaam waqt se pehle karein."),
        ("Set up a dedicated, quiet home office desk with ergonomic chair.", "گھر میں آرام دہ کرسی اور پرسکون جگہ پر اپنا ورک اسٹیشن بنائیں۔", "Ghar mein aaram deh kursi aur pursukoon jagah par office banayein."),
        ("Reliable high-speed fiber internet and power backup are non-negotiable.", "تیز رفتار انٹرنیٹ اور بجلی کا بیک اپ فری لانسنگ کی بنیادی ضرورت ہے۔", "Taiz internet aur bijli ka backup bunyadi zaroorat hai."),
        ("Track your billable working hours accurately with time-tracking software.", "اپنے کام کے گھنٹوں کا درست ریکارڈ سافٹ ویئر سے رکھیں۔", "Apne kaam ke ghanton ka durust record software se rakhein."),
        ("Send clear, detailed invoices upon successful project milestones.", "ہر مرحلہ مکمل ہونے پر کلائنٹ کو صاف اور تفصیلی انوائس بھیجیں۔", "Har marhala mukammal honay par saaf invoice bhejein."),
        ("Continuous self-discipline is the secret to thriving as a freelancer.", "روزانہ کا ذاتی نظم و ضبط ہی کامیاب فری لانسر بننے کا راز ہے۔", "Rozana ka zaati nazm-o-zabt hi kamyab freelancer ka raaz hai."),
        ("How do I calculate my hourly rate versus fixed-price project quotes?", "میں فی گھنٹہ ریٹ یا فکسڈ پروجیکٹ کی قیمت کا تعین کیسے کروں؟", "Mein fi ghanta rate ya fixed project ki qeemat kaisay tay karoon?"),
        ("Factor in your overhead costs, taxes, software, and desired savings.", "اپنے تمام اخراجات، ٹیکس، سافٹ ویئر اور بچت کو مدنظر رکھیں۔", "Apne tamam ikhrajat, software aur bachat ko madd-e-nazar rakhein."),
        ("Communicate project progress updates proactively through Slack or Teams.", "کام کی پیش رفت کے بارے میں کلائنٹ کو روزانہ آگاہ رکھیں۔", "Kaam ki paish-raft ke baare mein client ko aagah rakhein."),
        ("Never begin substantial work without an escrow funded contract in place.", "ایسکرو میں رقم جمع ہوئے بغیر بڑا کام کبھی شروع نہ کریں۔", "Escrow mein raqam jama hue baghair kaam shuru na karein."),
        ("Maintain clear contract scope boundaries to prevent scope creep.", "پروجیکٹ کے دائرہ کار کی حد مقرر کریں تاکہ اضافی مفت کام سے بچیں۔", "Project ki hadd muqarrar karein taakay muft kaam se bachein."),
        ("Ask satisfied international clients for five-star reviews and testimonials.", "مطمئن کلائنٹس سے اچھے ریویوز اور ریٹنگز کی درخواست کریں۔", "Mutmain clients se achay reviews aur ratings maangein."),
        ("Positive reviews build social proof that attracts high-paying gigs.", "اچھے ریویوز نئے بڑے پروجیکٹس حاصل کرنے کا سب سے بڑا ذریعہ ہیں۔", "Achay reviews naye baray projects laanay ka zariya hain."),
        ("Invest in premium skill courses to stay ahead of international competitors.", "بین الاقوامی مقابلے میں آگے رہنے کے لیے نئی مہارتیں سیکھتے رہیں۔", "Muqablay mein agay rehnay ke liye nayi maharatein seekhein."),
        ("Specializing in a high-demand niche pays significantly higher rates.", "کسی مخصوص شعبے میں مہارت حاصل کرنا زیادہ آمدنی دلاتا ہے۔", "Kisi makhsoos sho'bay mein maharat zyada aamadni dilati hai."),
        ("Remote work allows you to earn foreign currency while living at home.", "ریموٹ ورک آپ کو گھر بیٹھے ڈالرز کمانے کا موقع دیتا ہے۔", "Remote work aap ko ghar baithay dollars kamanay ka mauqa deta hai."),
        ("Use Payoneer or direct bank transfers to receive overseas earnings.", "بیرون ملک سے کمائی منگوانے کے لیے پے اونیر یا بینک ٹرانسفر استعمال کریں۔", "Bairoon-e-mulk se aamadni ke liye Payoneer ya bank transfer istemal karein."),
        ("Keep your tax returns filed and maintain legal business records.", "اپنا ٹیکس گوشوارہ باقاعدگی سے جمع کروائیں اور ریکارڈ رکھیں۔", "Apna tax return baqaidgi se jama karwayein aur record rakhein."),
        ("Overcoming imposter syndrome requires believing in your hard-earned skills.", "اپنی محنت اور ہنر پر پورا بھروسہ رکھیں اور خوف نکال دیں۔", "Apni mehnat aur hunar par poora bharosa rakhein."),
        ("Never underprice your work; quality craftsmanship commands fair value.", "اپنے ہنر کی کم قیمت نہ لگائیں؛ اچھے کام کی قدر منصفانہ ہونی چاہیے۔", "Apne kaam ki kam qeemat na lagayein; meyaar ki qadr honi chahiye."),
        ("Set clear working hours and do not answer non-emergency calls at 2 AM.", "کام کے اوقات مقرر کریں اور رات گئے غیر ضروری پیغامات نہ دیکھیں۔", "Kaam ke auqaat muqarrar karein aur dair raat messages na dekhein."),
        ("Take regular physical stretches and eye breaks to prevent RSI strains.", "پٹھوں کے کھنچاؤ سے بچنے کے لیے کام کے دوران ورزش کریں۔", "Patthon ke khinchao se bachnay ke liye warzish karein."),
        ("Building long-term retainer client relationships provides financial stability.", "ماہانہ معاہدے والے مستقل کلائنٹس مالی استحکام دیتے ہیں۔", "Maahana muahiday walay clients maali istehkam detay hain."),
        ("Always be polite, patient, and solutions-oriented in client video calls.", "کلائنٹ کالز میں ہمیشہ شائستہ، صابر اور مددگار رہیں۔", "Client calls mein hamesha shaista aur madadgaar rahein."),
        ("Deliver your source files in organized, clearly labeled zip archives.", "فائلز کو سلیقے سے فولڈرز میں بند کر کے کلائنٹ کو بھیجیں۔", "Files ko saleeqay se folders mein band kar ke bhejein."),
        ("Freelancing is running a full business where you are CEO and marketer.", "فری لانسنگ ایک مکمل کاروبار ہے جہاں آپ خود ہی سب کچھ ہیں۔", "Freelancing aik poora karobar hai jahan aap khud maalik hain."),
        ("Keep an emergency financial cushion for slow contract seasons.", "کام کم ہونے کے دنوں کے لیے ہنگامی بچت ہمیشہ پاس رکھیں۔", "Kaam kam honay ke dinon ke liye bachat hamesha paas rakhein."),
        ("Cold outreach on LinkedIn can land lucrative enterprise software contracts.", "لنکڈ اِن پر براہ راست رابطہ بڑے پروجیکٹس دلوا سکتا ہے۔", "LinkedIn par rabta baray projects dilwa sakta hai."),
        ("Use project management boards like Trello or Notion for tracking.", "کام کی ترتیب کے لیے ٹریلو یا نوشن جیسی ایپس استعمال کریں۔", "Kaam ki tarteeb ke liye Trello ya Notion istemal karein."),
        ("Continuous communication builds deep client trust across time zones.", "مسلسل رابطہ مختلف ٹائم زونز کے کلائنٹس میں اعتماد بڑھاتا ہے۔", "Musalsal rabta mukhtalif time zones ke clients mein aitemad barhata hai."),
        ("Learn how to handle difficult client revisions with calm grace.", "کلائنٹ کی تبدیلیوں کو مسکراہٹ اور تدبر کے ساتھ مکمل کریں۔", "Client ki changes ko muskurahat aur tadabbur se karein."),
        ("Do not put all your eggs in one single client's basket.", "کبھی بھی اپنی تمام آمدنی کا انحصار صرف ایک کلائنٹ پر نہ رکھیں۔", "Kabhi bhi apni aamadni ka inhisar sirf aik client par na rakhein."),
        ("Diversify your client base across various international markets.", "مختلف ممالک سے متعدد کلائنٹس کے ساتھ کام کریں۔", "Mukhtalif mumalik ke clients ke sath kaam karein."),
        ("Master English conversational fluency to negotiate top contracts.", "بڑے پروجیکٹس کے لیے روانی سے انگریزی بولنا سیکھیں۔", "Baray projects ke liye rawani se English bolna seekhein."),
        ("Celebrate every completed milestone and give thanks for opportunities.", "ہر مکمل پروجیکٹ پر شکر ادا کریں اور خوشی منائیں۔", "Har mukammal project par shukr ada karein aur khushi manayein."),
        ("Freelancing empowers you to chart your own professional destiny.", "فری لانسنگ آپ کو اپنے مستقبل کا خود معمار بناتی ہے۔", "Freelancing aap ko apne mustaqbil ka khud me'maar banati hai."),
        ("Back up your client code repositories and design assets to GitHub.", "اپنا کوڈ اور ڈیزائن کلاؤڈ اور گٹ ہب پر روزانہ بیک اپ کریں۔", "Apna code aur design cloud aur GitHub par backup karein."),
        ("Never miss a scheduled international client Zoom video meeting.", "کلائنٹ کے ساتھ طے شدہ ویڈیو میٹنگ میں کبھی تاخیر نہ کریں۔", "Client ke sath tay shuda video meeting mein takheer na karein."),
        ("Clear, honest boundaries make for healthy long-term freelancing careers.", "واضح اصول اور حدود فری لانسنگ کو پرسکون اور کامیاب بناتے ہیں۔", "Wazeh usool aur hudood freelancing ko kamyab banatay hain."),
        ("Invest in a comfortable noise-canceling microphone for client calls.", "کلائنٹ کالز کے لیے شور سے پاک بہترین مائیکروفون خریدیں۔", "Client calls ke liye shor se paak microphone khareedein."),
        ("Sharpen your sales pitching and problem diagnosis abilities.", "کلائنٹ کی ضرورت کو سمجھ کر اس کا حل پیش کرنے کا ہنر سیکھیں۔", "Client ki zaroorat ko samajh kar hal pesh karne ka hunar seekhein."),
        ("Remote work bridges talented Pakistani youth to global opportunity.", "ریموٹ ورک پاکستانی نوجوانوں کو عالمی مواقع سے جوڑتا ہے۔", "Remote work Pakistani naujawanon ko aalmi mawaqay se jorta hai."),
        ("Dedication, honesty, and consistency guarantee freelance triumph.", "محنت، دیانت اور مسلسل لگن فری لانسنگ میں کامیابی کی ضمانت ہیں۔", "Mehnat, dyanat aur lagan freelancing mein kamyabi ki zamanat hain."),
        ("Always leave a lasting positive impression with every single client.", "ہر کلائنٹ کے دل پر اپنے اعلیٰ کام کا اچھا تاثر چھوڑیں۔", "Har client par apne achay kaam ka ta'assur chhorrein."),
        ("Thank you for choosing independent creative freedom and excellence.", "خود مختار محنت اور ہنر کا راستہ منتخب کرنے پر آپ کو سلام۔", "Khud-mukhtaar mehnat ka rasta muntakhib karne par aap ko salam."),
        ("May your freelance career flourish with boundless global success!", "اللہ تعالیٰ آپ کے فری لانس کام میں بے پناہ برکت اور وسعت عطا فرمائے!", "Allah Ta'ala aap ke freelance kaam mein barkat aur wus'at ata farmaye!")
    ]

    return [
        {"id": 36, "name": "Climate, Environment & Nature", "urduName": "ماحولیات اور قدرت", "icon": "eco", "desc": "Global warming, tree plantation, smog, pollution, and recycling.", "sentences": t36},
        {"id": 37, "name": "Festivals & Celebrations", "urduName": "تہوار اور تقریبات", "icon": "celebration", "desc": "Eid, Ramadan, weddings, birthdays, gatherings, and traditions.", "sentences": t37},
        {"id": 38, "name": "Relationships & Family", "urduName": "رشتے اور خاندان", "icon": "groups", "desc": "Parents, siblings, marriage, respect, parenting, and bonds.", "sentences": t38},
        {"id": 39, "name": "Work Ethics & Office Culture", "urduName": "کام کی اخلاقیات اور دفتری ماحول", "icon": "business_center", "desc": "Punctuality, meetings, leadership, collaboration, and deadlines.", "sentences": t39},
        {"id": 40, "name": "Freelancing & Remote Work", "urduName": "فری لانسنگ اور آن لائن کام", "icon": "laptop_chromebook", "desc": "Upwork, Fiverr, proposals, clients, remote productivity, and invoicing.", "sentences": t40}
    ]
