# -*- coding: utf-8 -*-

def get_41_to_45():
    # 41. Public Speaking & Presentations
    t41 = [
        ("Good morning respected ladies and gentlemen; thank you for being here today.", "محترم خواتین و حضرات، صبح بخیر؛ آج تشریف لانے کا بے حد شکریہ۔", "Mohtaram khawateen-o-hazraat, subah bakhair; aaj aane ka shukriya."),
        ("Today I am honored to present our visionary strategy for the upcoming year.", "آج مجھے آنے والے سال کے لیے ہماری حکمت عملی پیش کرنے کا اعزاز حاصل ہے۔", "Aaj mujhe anay walay saal ki hikmat-e-amli pesh karne ka aizaaz hai."),
        ("Let us begin by examining the core problem we aim to solve together.", "آئیں سب سے پہلے اس بنیادی مسئلے کا جائزہ لیں جسے ہم حل کرنا چاہتے ہیں۔", "Aayein sab se pehle bunyadi maslay ka jaiza lein."),
        ("As you can clearly observe on this presentation slide, our growth doubled.", "جیسا کہ آپ سلائیڈ پر دیکھ سکتے ہیں، ہماری ترقی میں دوگنا اضافہ ہوا۔", "Jaisa ke aap slide par dekh saktay hain, hamari taraqi mein izafa hua."),
        ("Maintaining steady eye contact with your audience builds instant trust.", "سامعین کے ساتھ نظریں ملا کر بات کرنا فوری اعتماد پیدا کرتا ہے۔", "Saami'een ke sath nazrein mila kar baat karna aitemad paida karta hai."),
        ("Use open and confident body gestures to reinforce your key spoken points.", "اپنے اہم نکات کو واضح کرنے کے لیے پراعتماد انداز اپنائیں۔", "Apne ahem nukat ko wazeh karne ke liye pur-aitemad andaaz apnayein."),
        ("Pause intentionally after key statements to allow ideas to sink in deeply.", "اہم بات کہنے کے بعد تھوڑا سا توقف کریں تاکہ بات دل میں اتر جائے۔", "Ahem baat kehne ke baad thora tawaqquf karein."),
        ("Let me share an inspiring real-world case study to illustrate this.", "آئیں اس بات کو سمجھنے کے لیے ایک حقیقی زندگی کی مثال دیکھتے ہیں۔", "Aayein is baat ko samajhnay ke liye aik haqeeqi misaal dekhtay hain."),
        ("Are there any questions or comments regarding this introductory phase?", "کیا اس تعارفی مرحلے کے بارے میں کسی کا کوئی سوال یا رائے ہے؟", "Kya is taarufi marhalay ke baare mein koi sawal hai?"),
        ("Preparation and rehearsal turn nervous stage fear into dynamic confidence.", "اچھی تیاری اور مشق گھبراہٹ کو زبردست اعتماد میں بدل دیتی ہے۔", "Achi tayari aur mashq ghabrahat ko aitemad mein badal deti hai."),
        ("Speak slowly, clearly, and project your voice to the back of the room.", "آہستہ، واضح اور اتنی آواز میں بولیں کہ ہال کے آخری کونے تک سنائی دے۔", "Aahista, wazeh aur aisi aawaz mein bolein jo aakhir tak jaye."),
        ("Keep your presentation slides visually clean with minimal bullet text.", "اپنی سلائیڈز کو سادہ اور کم سے کم تحریر کے ساتھ خوبصورت رکھیں۔", "Apni slides ko saada aur kam tehreer ke sath khubsurat rakhein."),
        ("A compelling personal story captivates listeners far more than raw data.", "ایک سچی کہانی اعداد و شمار سے زیادہ سامعین کے دل کو چھوتی ہے۔", "Aik sachi kahani aadaad-o-shumaar se zyada dil ko chhooti hai."),
        ("Structure your speech with a clear beginning, middle, and powerful conclusion.", "اپنی تقریر کو واضح آغاز، دلائل اور پرتاثیر اختتام کے ساتھ ترتیب دیں۔", "Apni taqreer ko aaghaz, dalaail aur pur-taseer ikhtitaam se sajayein."),
        ("Thank you for your attentive listening; I welcome your thoughtful questions.", "آپ کی توجہ کا شکریہ؛ اب میں آپ کے سوالات کا خیرمقدم کرتا ہوں۔", "Aap ki tawajjo ka shukriya; ab mein sawalat ka khair-muqadam karta hoon."),
        ("Could you please elaborate on how this impacts our project timeline?", "کیا آپ واضح کر سکتے ہیں کہ اس کا ہمارے پروجیکٹ کے وقت پر کیا اثر پڑے گا؟", "Kya aap wazeh kar saktay hain ke is ka waqt par kya asar parray ga?"),
        ("That is an excellent and insightful question; let me address it.", "یہ ایک انتہائی شاندار سوال ہے؛ آئیے میں اس کی وضاحت کرتا ہوں۔", "Yeh aik intehai shandar sawal hai; aayiye mein wazahat karta hoon."),
        ("Use storytelling techniques to make technical concepts accessible to all.", "پیچیدہ باتوں کو آسان بنانے کے لیے کہانی کا انداز اپنائیں۔", "Paicheeda baton ko aasan bananay ke liye kahani ka andaaz apnayein."),
        ("Never read word-for-word directly off the presentation screen behind you.", "پردے پر لکھی عبارت کو دیکھ کر لفظ بہ لفظ پڑھنے سے گریز کریں۔", "Parday par likhi tehreer ko dekh kar lafz ba lafz parhnay se bachein."),
        ("Deep diaphragmatic breathing calms racing heartbeat before taking stage.", "اسٹیج پر جانے سے پہلے گہرے سانس لینا دل کی دھڑکن کو پرسکون کرتا ہے۔", "Stage par jaanay se pehle gehray saans lena dil ko pursukoon karta hai."),
        ("Vary your vocal pitch and tone to keep the audience fully engaged.", "سامعین کی دلچسپی برقرار رکھنے کے لیے اپنی آواز کے اتار چڑھاؤ پر دھیان دیں۔", "Saami'een ki dilchaspi ke liye aawaz ke utaar charrhao par dhyan dein."),
        ("Arrive early to test the audiovisual projector and microphone equipment.", "پروجیکٹر اور مائیکروفون کی جانچ کے لیے وقت سے پہلے پہنچیں۔", "Projector aur mic check karne ke liye waqt se pehle pohanchein."),
        ("Always have a backup offline presentation file saved on a USB drive.", "یو ایس بی ڈرائیو میں اپنی پریزنٹیشن کی بیک اپ کاپی ضرور رکھیں۔", "USB drive mein presentation ka backup zaroor rakhein."),
        ("A confident public speaker connects human hearts before minds.", "ایک اچھا مقرر دماغوں سے پہلے انسانوں کے دلوں کو جوڑتا ہے۔", "Aik acha muqarrir dimaghon se pehle dilon ko jorta hai."),
        ("Conclude your talk with a memorable, actionable call to action.", "اپنی تقریر کا اختتام کسی یادگار اور عملی پیغام پر کریں۔", "Apni taqreer ka ikhtitaam yaadgaar aur amli paigham par karein."),
        ("Public speaking is a learnable craft perfected through regular practice.", "تقریر ایک ایسا ہنر ہے جو مسلسل مشق سے نکھرتا ہے۔", "Taqreer aik aisa hunar hai jo musalsal mashq se nikharta hai."),
        ("Stand tall with balanced weight on both feet and squared shoulders.", "دونوں پاؤں پر سیدھے اور پراعتماد انداز میں کھڑے ہوں۔", "Dono paon par seedhay aur pur-aitemad andaaz mein kharray hon."),
        ("Smile warmly when you step up to the podium to welcome listeners.", "ڈائس پر آتے ہی مسکراہٹ کے ساتھ سامعین کا استقبال کریں۔", "Podium par aatay hi muskurahat ke sath isteqbaal karein."),
        ("Engage your audience with an intriguing opening rhetorical question.", "تقریر کے آغاز میں ہی ایک سوچ پیدا کرنے والا سوال پوچھیں۔", "Taqreer ke aaghaz mein aik soch paida karne wala sawal poochein."),
        ("Audiences root for your success, so step forward with courage.", "سننے والے آپ کی کامیابی چاہتے ہیں، اس لیے پورے حوصلے سے بولیں۔", "Sunnay walay aap ki kamyabi chahtay hain, hauslay se bolein."),
        ("Use clear infographics and charts to represent statistical data.", "اعداد و شمار دکھانے کے لیے واضح چارٹس اور گراف کا استعمال کریں۔", "Aadaad-o-shumaar dikhanay ke liye graphs ka istemal karein."),
        ("Keep your slide transitions smooth and free of distracting animations.", "سلائیڈز کو سادہ رکھیں اور غیر ضروری اینیمیشنز سے گریز کریں۔", "Slides ko saada rakhein aur animations se bachein."),
        ("Know your target audience's background and speak to their interests.", "اپنے سامعین کے رجحان کو جانیں اور ان کے مطلب کی بات کریں۔", "Apne saami'een ke rujhaan ko jaanein aur un ke mutabiq bolein."),
        ("Respect the allotted time limit strictly and never run over schedule.", "دیئے گئے وقت کا مکمل احترام کریں اور مقررہ وقت پر ختم کریں۔", "Diye gaye waqt ka ihtiram karein aur waqt par khatam karein."),
        ("Summarize three primary memorable takeaways in your closing remarks.", "اپنے اختتامی کلمات میں تین بنیادی نکات کا خلاصہ پیش کریں۔", "Ikhtitaami kalmaat mein teen bunyadi nukat ka khulasa dein."),
        ("Welcome dissenting opinions during Q&A with dignity and respect.", "سوال جواب کے دوران مختلف آراء کا خندہ پیشانی سے استقبال کریں۔", "Sawal jawab ke dauran mukhtalif aara ka khanda-paishani se jawab dein."),
        ("Practice delivering your presentation in front of a mirror or friend.", "شیشے کے سامنے یا کسی دوست کے سامنے تقریر کی مشق کریں۔", "Sheeshay ke samnay ya dost ke samnay taqreer ki mashq karein."),
        ("Master the art of natural movement across the presentation stage.", "اسٹیج پر مناسب اور فطری انداز میں چلنا پھرنا سیکھیں۔", "Stage par munasib aur fitri andaaz mein chalna seekhein."),
        ("Humor used with taste breaks social tension and wins hearts.", "مناسب اور شائستہ مزاح ماحول کو ہلکا پھلکا بنا دیتا ہے۔", "Munasib aur shaista mizah mahaul ko khushgawar banata hai."),
        ("Believe deeply in your core message, and your audience will too.", "اپنے پیغام پر خود یقین رکھیں تو سننے والے بھی قائل ہوں گے۔", "Apne paigham par khud yaqeen rakhein to log bhi qayil hon ge."),
        ("Avoid verbal fillers like 'um', 'uh', and 'you know' by pausing.", "غیر ضروری آوازوں سے بچنے کے لیے خاموشی کا وقفہ لیں۔", "Ghair zaroori awazon se bachnay ke liye khamoshi ka waqfa lein."),
        ("Ensure the wireless slide presenter clicker has brand new batteries.", "پریزنٹیشن کلکر کی بیٹریاں پہلے سے چیک کر لیں۔", "Presentation clicker ki batteries pehle se check karein."),
        ("Share authentic vulnerability to build deep emotional resonance.", "اپنے سچے تجربات بیان کریں تاکہ سننے والے دل سے جڑ سکیں۔", "Apne sachay tajrubat bayan karein taakay log dil se jurein."),
        ("Speak to inspire, educate, enlighten, and uplift human spirits.", "ایسے بولیں کہ لوگوں کو نئی امید، علم اور روشنی ملے۔", "Aisay bolein ke logon ko umeed aur roshni milay."),
        ("Public eloquence is a sacred gift that can transform societies.", "فصاحت و بلاغت ایک ایسی نعمت ہے جو معاشروں کو بدل سکتی ہے۔", "Fasahat-o-balaghat aisi nemat hai jo ma'ashray ko badal sakti hai."),
        ("Always thank event organizers, technicians, and the host team.", "پروگرام کے منتظمین اور میزبانوں کا شکریہ ضرور ادا کریں۔", "Program ke muntazimeen aur mezbanon ka shukriya ada karein."),
        ("Reflect on your recorded speaking videos to continuously refine style.", "اپنی تقاریر کی ویڈیوز دیکھ کر اپنے انداز کو مزید نکھاریں۔", "Apni taqreer ki videos dekh kar apne andaaz ko nikharein."),
        ("Confidence is not the absence of nervousness; it is action despite it.", "اعتماد گھبراہٹ نہ ہونے کا نام نہیں بلکہ خوف کے باوجود بولنا ہے۔", "Aitemad ghabrahat na honay ka naam nahi balkay himmat se bolna hai."),
        ("Thank you for this wonderful platform and your incredible attention.", "اس شاندار موقع اور آپ کی بھرپور توجہ کا بے حد شکریہ۔", "Is shandar platform aur aap ki tawajjo ka bohat shukriya."),
        ("May your words always ignite wisdom, courage, and lasting impact!", "اللہ کرے آپ کی گفتگو ہمیشہ حکمت، روشنی اور اثر سے بھرپور رہے!", "Allah karay aap ki guftagu hamesha hikmat aur asar se bharpoor rahay!")
    ]

    # 42. Debates & Discussions
    t42 = [
        ("Let us conduct this debate with mutual intellectual courtesy.", "آئیں اس مباحثے کو باہمی احترام اور علمی وقار کے ساتھ آگے بڑھائیں۔", "Aayein is mubahisay ko ilmi waqaar ke sath aagay barhayein."),
        ("What empirical evidence supports your primary opening argument?", "آپ کے بنیادی موقف کی تائید میں کیا ٹھوس شواہد موجود ہیں؟", "Aap ke bunyadi mauqif ki tayeed mein kya thoos saboot hain?"),
        ("I respectfully rebut that claim using recent peer-reviewed studies.", "میں حالیہ سائنسی تحقیق کی روشنی میں اس دعوے سے اختلاف کرتا ہوں۔", "Mein tehqeeq ki roshni mein is daaway se ikhtilaaf karta hoon."),
        ("We must separate emotional rhetoric from verifiable logical facts.", "ہمیں جذباتی باتوں اور ٹھوس حقائق میں واضح فرق کرنا ہوگا۔", "Humein jazbaati baton aur thoos haqaiq mein farq karna hoga."),
        ("Allow me to present three counterarguments to your thesis.", "مجھے آپ کے موقف کے خلاف تین مدلل دلائل پیش کرنے کی اجازت دیں۔", "Mujhe aap ke mauqif ke khilaf teen dalaail pesh karne dein."),
        ("That assertion relies on a logical fallacy known as hasty generalization.", "یہ دعویٰ نامکمل معلومات کی بنیاد پر بنائی گئی خام رائے ہے۔", "Yeh daawa na-mukammal maloomat par mabni raye hai."),
        ("Let us examine the root economic causes behind this societal trend.", "آئیں اس سماجی مسئلے کی بنیادی معاشی وجوہات کا جائزہ لیں۔", "Aayein is maslay ki bunyadi maashi wujoohaat ka jaiza lein."),
        ("Can we find common ground on the foundational principles of ethics?", "کیا ہم بنیادی اخلاقی اصولوں پر کسی مشترکہ نکتے پر پہنچ سکتے ہیں؟", "Kya hum bunyadi ikhlaaqi usoolon par muttafiq ho saktay hain?"),
        ("I acknowledge the validity of your first point, but disagree with the second.", "میں آپ کی پہلی بات سے متفق ہوں، لیکن دوسری بات درست نہیں۔", "Mein aap ki pehli baat se muttafiq hoon, lekin doosri theek nahi."),
        ("Truth is discovered through rigorous, honest, and humble inquiry.", "سچائی مسلسل، مخلصانہ اور غیر جانبدارانہ تحقیق سے ملتی ہے۔", "Sachai musalsal aur ghair-jaanibdarana tehqeeq se milti hai."),
        ("What are the long-term societal ramifications of this legislation?", "اس قانون کے معاشرے پر طویل مدتی اثرات کیا مرتب ہوں گے؟", "Is qanoon ke ma'ashray par taweel muddati asraat kya hon ge?"),
        ("Correlation does not necessarily imply direct causal relationship.", "دو چیزوں کا ایک ساتھ ہونا اس بات کا ثبوت نہیں کہ ایک دوسرے کی وجہ ہے۔", "Do cheezon ka sath hona doosray ki wajah hona zaroori nahi."),
        ("Let us define the core operational terms before debating further.", "آگے بڑھنے سے پہلے آئیں اس موضوع کی بنیادی تعریفیں طے کر لیں۔", "Aagay barhnay se pehle ahem tareefein tay kar lein."),
        ("I urge the opposing panel to address the statistical data presented.", "میں مخالف پینل سے گزارش کرتا ہوں کہ وہ پیش کردہ اعداد کا جواب دیں۔", "Mein mukhalif panel se kehta hoon ke woh aadaad ka jawab dein."),
        ("Personal attacks (ad hominem) weaken an otherwise rational debate.", "ذاتی حملے کرنا کسی بھی سنجیدہ بحث کو کمزور اور بے وزن کر دیتا ہے۔", "Zaati hamlay karna sanjeeda behas ko kamzor kar deta hai."),
        ("How does your proposed model account for severe resource scarcity?", "آپ کا مجوزہ ماڈل وسائل کی کمی کے مسئلے کو کیسے حل کرے گا؟", "Aap ka model wasail ki kami ko kaisay hal karay ga?"),
        ("History offers profound cautionary lessons on this specific topic.", "تاریخ ہمیں اس خاص معاملے میں گہرے سبق اور تنبیہ فراہم کرتی ہے۔", "Tareekh humein is maamlay mein sabq deti hai."),
        ("We must balance technological innovation with human moral welfare.", "ہمیں جدید ٹیکنالوجی کو انسانی اخلاقی فلاح کے ساتھ جوڑنا ہوگا۔", "Humein technology ko insani ikhlaaqi falah se jorna hoga."),
        ("Your argument assumes ideal conditions that rarely exist in reality.", "آپ کے دلائل ان حالات پر مبنی ہیں جو حقیقی زندگی میں نہیں ملتے۔", "Aap ke dalaail aisi soorathal par hain jo dunya mein nahi milti."),
        ("Let us listen attentively to the counter-perspective before responding.", "جواب دینے سے پہلے مخالف نقطہ نظر کو پوری توجہ سے سنیں۔", "Jawab denay se pehle mukhalif nuqta-e-nazar tawajjo se sunein."),
        ("A healthy democracy thrives on vigorous and respectful discourse.", "ایک صحت مند معاشرہ شائستہ اور تعمیری مباحث سے پروان چڑھتا ہے۔", "Aik sehat-mand ma'ashra shaista mubahisay se banta hai."),
        ("Can you cite the primary academic source for that startling statistic?", "کیا آپ اس حیران کن اعداد و شمار کا اصل تحقیقی حوالہ دے سکتے ہیں؟", "Kya aap is aadaad-o-shumaar ka asal tehqeeqi hawala de saktay hain?"),
        ("We must not confuse subjective opinions with objective moral truths.", "ہمیں ذاتی آراء اور سچی حقیقتوں کے درمیان فرق رکھنا چاہیے۔", "Humein zaati aara aur haqaiq mein farq rakhna chahiye."),
        ("The motion before the house demands rigorous critical analysis.", "ایوان کے سامنے پیش کردہ قرارداد گہرے تجزیے کی متقاضی ہے۔", "Aaiwan ke samnay pesh qaraardaad gehray jaizay ki talabgaar hai."),
        ("I propose a balanced synthesis that incorporates both viewpoints.", "میں ایک ایسا متوازن حل پیش کرتا ہوں جو دونوں آراء کا احاطہ کرے۔", "Mein aik aisa motadil hal pesh karta hoon jo dono ko jorray."),
        ("Passionate conviction must always be guided by rational reason.", "پرجوش جذبات کو ہمیشہ عقل اور منطق کے تابع ہونا چاہیے۔", "Purjosh jazbaat ko aql aur mantiq ke tehat hona chahiye."),
        ("Let us conclude our arguments within the assigned two-minute rebuttal.", "آئیں اپنے دلائل دو منٹ کے دیے گئے وقت میں مکمل کریں۔", "Aayein apne dalaail do minute ke waqt mein mukammal karein."),
        ("The purpose of debate is not ego victory, but illumination of truth.", "بحث کا مقصد جیتنا نہیں بلکہ حق اور سچائی کو واضح کرنا ہے۔", "Behas ka maqsad jeetna nahi balkay sach ko wazeh karna hai."),
        ("I commend the honorable opposition for their sharp analytical points.", "میں مخالف پینل کے شاندار اور مدلل نکات کی تعریف کرتا ہوں۔", "Mein mukhalif panel ke shandar nukat ki tareef karta hoon."),
        ("Intellectual humility is the first prerequisite for genuine learning.", "علمی عاجزی ہی سچی دانائی اور سیکھنے کی پہلی شرط ہے۔", "Ilmi aajzi hi sachi danai aur seekhnay ki pehli shart hai."),
        ("What are the ethical implications of genetic engineering in medicine?", "طب میں جینیاتی تبدیلی کے اخلاقی تقاضے کیا ہیں؟", "Tibb mein genetic tabdeeli ke ikhlaaqi taqazay kya hain?"),
        ("We must protect free speech while condemning malicious slander.", "ہمیں آزادی اظہار کا دفاع کرتے ہوئے جھوٹ اور بہتان کی مذمت کرنی چاہیے۔", "Azaadi-e-izhaar ke sath bohtaan ki muzammat karein."),
        ("The evidence overwhelmingly supports the urgent need for environmental reform.", "شواہد فوری طور پر ماحولیاتی اصلاحات کی ضرورت کو ثابت کرتے ہیں۔", "Shawahid fauri tor par maholiyaati islaah ki zaroorat batatay hain."),
        ("Let us not derail the core debate into secondary trivial matters.", "آئیں بنیادی بحث کو چھوڑ کر غیر ضروری باتوں میں نہ الجھیں۔", "Aayein ahem behas chorr kar ghair zaroori baton mein na uljhein."),
        ("Clear logic and sound premise lead to inevitable conclusions.", "صاف منطق اور درست بنیاد ہمیشہ صحیح نتائج تک پہنچاتی ہے۔", "Saaf mantiq aur durust bunyad sahih nataij tak pohanchati hai."),
        ("I stand firmly in support of universal quality education for all children.", "میں ہر بچے کے لیے معیاری اور مفت تعلیم کی پرزور حمایت کرتا ہوں۔", "Mein har bachay ke liye meyaari taleem ki purzor himayat karta hoon."),
        ("Economic prosperity cannot be separated from social justice.", "معاشی خوشحالی کو سماجی انصاف سے الگ نہیں کیا جا سکتا۔", "Maashi khush-haali ko samaji insaaf se alag nahi kiya ja sakta."),
        ("Let us weigh the long-term benefits against immediate short-term costs.", "آئیں فوری اخراجات کے مقابلے میں دیرپا فوائد کا موازنہ کریں۔", "Aayein fori ikhrajat ke muqablay mein taweel fawaid dekhein."),
        ("The strength of an argument lies in its proof, not in loud volume.", "دلیل کی طاقت آواز کی بلندی میں نہیں بلکہ ثبوت کے وزن میں ہے۔", "Daleel ki taaqat aawaz mein nahi balkay saboot ke wazan mein hai."),
        ("Thoughtful disagreement sharpens the intellect and broadens wisdom.", "شائستہ اختلاف عقل کو جلا بخشتا ہے اور سوچ کو وسیع کرتا ہے۔", "Shaista ikhtilaaf aql ko tez karta hai aur soch ko wasee karta hai."),
        ("I invite the judges to critically evaluate both sides of the motion.", "میں ججز سے درخواست کرتا ہوں کہ وہ دونوں اطراف کے دلائل کا جائزہ لیں۔", "Mein judges se kehta hoon ke dono atraaf ke dalaail parkhein."),
        ("We must address structural inequalities rather than temporary symptoms.", "ہمیں عارضی علامات کے بجائے بنیادی ناانصافیوں کو ختم کرنا ہوگا۔", "Humein bunyadi na-insafiyon ko khatam karna hoga."),
        ("Respectful dialogue builds bridges across deep ideological divides.", "شائستہ مکالمہ مختلف نظریات رکھنے والوں کے درمیان پل بناتا ہے۔", "Shaista mukalma mukhtalif nazriyaat walon ko jorta hai."),
        ("Critical thinking enables citizens to discern fact from propaganda.", "تنقیدی سوچ انسان کو سچائی اور پروپیگنڈے میں فرق سکھاتی ہے۔", "Tanqeedi soch insaan ko sach aur jhoot mein farq sikhati hai."),
        ("Let justice, empathy, and logic guide our collective societal decisions.", "ہمارے تمام اجتماعی فیصلے انصاف، ہمدردی اور عقل کی بنیاد پر ہوں۔", "Hamare tamam faislay insaaf aur aql ki bunyad par hon."),
        ("I thank the adjudicators, timekeeper, and the audience for their presence.", "میں ججز، ٹائم کیپر اور حاضرین کا تہہ دل سے شکریہ ادا کرتا ہوں۔", "Mein judges aur hazireen ka teh-e-dil se shukriya ada karta hoon."),
        ("May intellectual honesty always prevail in every academic forum.", "اللہ کرے ہر علمی مجلس میں ہمیشہ سچائی اور دیانت داری کا بول بالا ہو!", "Allah karay har ilmi mehfil mein dyanat-dari ka bol baala ho!"),
        ("Divergent viewpoints, when handled respectfully, enrich human culture.", "مختلف آراء باہمی احترام کے ساتھ انسانی تہذیب کو نکھارتی ہیں۔", "Mukhtalif aara ihtiram ke sath tehzeeb ko nikharti hain."),
        ("Thank you for an enriching, challenging, and deeply inspiring debate.", "ایک شاندار، فکری اور پرتاثیر مباحثے کے لیے آپ کا بے حد شکریہ۔", "Aik shandar aur ilmi mubahisay ke liye aap ka bohat shukriya."),
        ("May our pursuit of truth guide us toward enlightenment and peace!", "اللہ کرے سچ کی تلاش ہمیں ہمیشہ علم اور امن کی راہ دکھائے!", "Allah karay sach ki talash humein roshni aur aman ki raah dikhaye!")
    ]

    # 43. Mental Health & Stress Relief
    t43 = [
        ("Mental health is just as crucial as physical bodily wellbeing.", "ذہنی صحت اتنی ہی ضروری ہے جتنی کہ جسمانی تندرستی۔", "Zehni sehat utni hi zaroori hai jitni jismani tandrusti."),
        ("Taking deep, slow diaphragmatic breaths instantly lowers cortisol levels.", "گہرے اور آہستہ سانس لینا ذہنی دباؤ کے ہارمونز کو فوراً کم کرتا ہے۔", "Gehray saans lena zehni dabao ko fori kam karta hai."),
        ("It is completely okay to seek professional therapy when feeling overwhelmed.", "جب بوجھ زیادہ لگے تو ماہر نفسیات سے مشورہ لینا بالکل درست ہے۔", "Jab bojh zyada lagay to expert se mashwara lena theek hai."),
        ("Practicing daily morning gratitude rewires the brain towards optimism.", "روزانہ صبح شکر گزاری کی عادت ذہن کو پرامید اور خوش رکھتی ہے۔", "Rozana subah shukr-guzari zehan ko pur-umeed rakhti hai."),
        ("Set healthy emotional boundaries to protect your peace of mind.", "اپنے ذہنی سکون کے تحفظ کے لیے ضروری حدیں قائم کریں۔", "Apne zehni sukoon ke tahaffuz ke liye zaroori hudood banayein."),
        ("A fifteen-minute walk in nature lowers anxiety and clears mental fog.", "قدرت میں پندرہ منٹ کی واک گھبراہٹ کو دور کر کے ذہن صاف کرتی ہے۔", "Qudrat mein 15 minute ki walk zehan ko saaf karti hai."),
        ("Do not bottle up heavy emotions; talk to a trusted friend or mentor.", "اپنے دکھ اور بوجھ کو اکیلے مت سہہیں، کسی مخلص سے بات کریں۔", "Apne dukh ko akele mat sahein, kisi mukhlis se baat karein."),
        ("Adequate, restful eight-hour sleep is medicine for the nervous system.", "آٹھ گھنٹے کی پرسکون نیند اعصابی نظام کے لیے بہترین دوا ہے۔", "Aath ghantay ki pursukoon neend a'asaab ke liye dawa hai."),
        ("Mindfulness is being present in the moment without harsh self-judgment.", "مائنڈفل نیس کا مطلب خود پر تنقید کیے بغیر حال میں جینا ہے۔", "Mindfulness ka matlab haal mein pursukoon rehna hai."),
        ("You are stronger than your anxious thoughts; this difficulty will pass.", "آپ اپنی پریشانیوں سے زیادہ طاقتور ہیں؛ یہ وقت بھی گزر جائے گا۔", "Aap apni pareshaniyon se taqatwar hain; yeh waqt guzar jaye ga."),
        ("How do you manage overwhelming workload stress during peak deadlines?", "آپ کام کے زیادہ دباؤ اور ڈیڈ لائنز کے دوران سکون کیسے رکھتے ہیں؟", "Aap kaam ke dabao mein sukoon kaisay rakhtay hain?"),
        ("Break daunting large projects into tiny, manageable daily steps.", "بڑے اور مشکل کاموں کو چھوٹے چھوٹے روزانہ کے حصوں میں بانٹ لیں۔", "Baray kamon ko chhotay chhotay hisson mein baant lein."),
        ("Avoid comparing your life journey with others' curated social media.", "اپنی زندگی کا موازنہ دوسروں کی سوشل میڈیا تصویروں سے مت کریں۔", "Apni zindagi ka mawazna social media se mat karein."),
        ("Writing your worries in a private journal takes the weight off your chest.", "اپنی پریشانیاں ڈائری میں لکھ لینا دل کا بوجھ ہلکا کر دیتا ہے۔", "Apni pareshaniyan diary mein likhna dil ka bojh halka karta hai."),
        ("Gentle stretching and yoga relieve tension stored in neck and shoulders.", "ہلکی ورزش گردن اور کندھوں کا کھنچاؤ دور کرتی ہے۔", "Halki warzish gardan aur kandhon ka khinchao door karti hai."),
        ("Listen to soothing nature sounds like flowing rivers and falling rain.", "بہتے پانی اور بارش کی پرسکون آوازیں سن کر اعصاب پرسکون کریں۔", "Behtay paani aur barish ki pursukoon aawazein sunein."),
        ("It is not a weakness to admit that you need rest and recovery.", "تھکن کا اعتراف کر کے آرام کرنا کمزوری نہیں بلکہ دانشمندی ہے۔", "Thakan ka aiteeraaf kar ke aaram karna aqalmandi hai."),
        ("Practice the 4-7-8 breathing exercise to fall asleep peacefully.", "پرسکون نیند کے لیے چار سیکنڈ سانس لیں اور آٹھ سیکنڈ میں نکالیں۔", "Pursukoon neend ke liye gehray saans ki mashq karein."),
        ("Unplug from electronic screens at least one hour before bedtime.", "سونے سے کم از کم ایک گھنٹہ پہلے تمام موبائل اسکرینیں بند کر دیں۔", "Sonay se aik ghanta pehle screens band kar dein."),
        ("Be as kind and forgiving to yourself as you would to a dear friend.", "اپنے ساتھ بھی اتنی ہی نرمی اور شفقت برتیں جتنی دوست کے ساتھ۔", "Apne sath bhi utni hi narmi bartein jitni dost ke sath."),
        ("Spiritual prayer and dhikr instill deep serenity within the troubled soul.", "نماز، دعا اور ذکرِ الٰہی بے چین روح کو حقیقی سکون بخشتے ہیں۔", "Namaz, dua aur zikr-e-Ilahi rooh ko sukoon bakhshtay hain."),
        ("Normalize talking openly about anxiety, depression, and mental health.", "ذہنی دباؤ اور ڈپریشن پر کھلی اور ہمدردانہ گفتگو کو رواج دیں۔", "Zehni dabao aur depression par khuli baat cheet ko aam karein."),
        ("Laughter with cherished family releases uplifting endorphin chemicals.", "پیاروں کے ساتھ کھلکھلا کر ہنسنا جسم میں خوشی کے ہارمونز بناتا ہے۔", "Pyaron ke sath hansna jism mein khushi ke hormones banata hai."),
        ("Drink warm herbal chamomile or mint tea to soothe nervous jitters.", "اعصابی بے چینی دور کرنے کے لیے پودینے یا بابونہ کا قہوہ پئیں۔", "Be-chaini door karne ke liye podeenay ka qahwa piyein."),
        ("Physical exercise is one of the most effective natural antidepressants.", "روزانہ کی ورزش ڈپریشن کے خلاف قدرت کی بہترین دوا ہے۔", "Rozana ki warzish depression ke khilaf behtareen dawa hai."),
        ("Celebrate minor daily victories and do not dwell on minor mistakes.", "اپنی چھوٹی چھوٹی کامیابیوں کو سراہیں اور غلطیوں کو بھول جائیں۔", "Apni chhoti kamyabiyon ko sarahein aur ghalti bhool jayein."),
        ("You do not have to carry the whole world's problems on your shoulders.", "آپ پر پوری دنیا کا بوجھ اکیلے اٹھانے کی ذمہ داری نہیں ہے۔", "Aap par poori dunya ka bojh akele uthanay ka farz nahi hai."),
        ("Give yourself permission to pause, rest, recharge, and breathe deeply.", "خود کو رکنے، سانس لینے اور توانائی بحال کرنے کا موقع دیں۔", "Khud ko ruknay, saans lenay aur aaram ka mauqa dein."),
        ("Surround yourself with compassionate, positive, and supportive souls.", "اپنے اردگرد مخلص، مثبت اور محبت کرنے والے لوگوں کو رکھیں۔", "Apne gird mukhlis aur musbat logon ko rakhein."),
        ("A calm mind creates clear thinking and effective problem-solving.", "پرسکون ذہن ہی صاف سوچ اور مسائل کا بہترین حل نکالتا ہے۔", "Pursukoon zehan hi saaf soch aur hal nikaalta hai."),
        ("Release the urge to control what is entirely outside your hands.", "ان باتوں کی فکر چھوڑ دیں جو آپ کے اختیار میں بالکل نہیں ہیں۔", "Un baton ki fikr chorr dein jo aap ke bas mein nahi hain."),
        ("Focus your precious energy only on what you can change today.", "اپنی توانائی صرف ان کاموں پر لگائیں جو آپ آج بدل سکتے ہیں۔", "Apni tawanaai sirf un kamon par lagayein jo aap badal saktay hain."),
        ("Spend time in quiet reflection away from urban noise and traffic.", "شہر کے شور سے دور کچھ وقت تنہائی اور غور و فکر میں گزاریں۔", "Shehar ke shor se door kuch waqt tanhai mein guzarein."),
        ("Self-care is not selfish; it is essential to care for others well.", "اپنا خیال رکھنا خود غرضی نہیں بلکہ دوسروں کی خدمت کے لیے لازمی ہے۔", "Apna khayal rakhna doosron ki khidmat ke liye laazmi hai."),
        ("Hydrate regularly with pure fresh water throughout the busy day.", "مصروف دن میں تازہ پانی کی مناسب مقدار پینا مت بھولیں۔", "Masroof din mein taaza paani peena mat bhoolin."),
        ("Every difficult storm eventually runs out of rain; have faith.", "ہر اندھیری رات کے بعد اجالا ضرور ہوتا ہے؛ امید قائم رکھیں۔", "Har andheri raat ke baad ujala zaroor hota hai; umeed rakhein."),
        ("Create a cozy, quiet reading corner in your bedroom for relaxation.", "گھر کے کسی کونے میں پرسکون مطالعے کی جگہ بنائیں۔", "Ghar ke kisi konay mein pursukoon mutala'a ki jagah banayein."),
        ("Learn to say no politely to commitments that drain your energy.", "ان کاموں کو شائستگی سے نہ کہنا سیکھیں جو آپ کو تھکا دیتے ہیں۔", "Un kamon ko na kehna seekhein jo aap ko thaka detay hain."),
        ("Spend time playing with pets or tending to flowering potted plants.", "پالتو جانوروں کے ساتھ وقت گزارنا یا پودے لگانا سکون دیتا ہے۔", "Paaltu janwaron ke sath waqt guzarna sukoon deta hai."),
        ("Forgive yourself for past missteps; today is a brand-new page.", "ماضی کی غلطیوں پر خود کو معاف کریں؛ آج ایک نیا دن ہے۔", "Maazi ki ghaltiyon par khud ko maaf karein; aaj naya din hai."),
        ("Mental clarity begins with accepting reality with patience and grace.", "ذہنی سکون حالات کو صبر اور وقار سے قبول کرنے سے شروع ہوتا ہے۔", "Zehni sukoon halaat ko sabr se qubool karne se shuru hota hai."),
        ("Take brief five-minute sensory breaks: notice colors, sounds, and scents.", "دن میں چند منٹ اردگرد کے خوبصورت رنگوں اور خوشبوؤں کو محسوس کریں۔", "Din mein chand minute khubsurat rangon aur khushboo ko mehsoos karein."),
        ("Listen with empathy when someone opens up about their struggles.", "جب کوئی اپنا دکھ بتائے تو پوری ہمدردی سے اس کی بات سنیں۔", "Jab koi dukh bataye to poori hamdardi se baat sunein."),
        ("Your life has immense intrinsic worth and divine unique purpose.", "آپ کی زندگی انتہائی قیمتی اور ایک خاص مقصد کے تحت ہے۔", "Aap ki zindagi intehai qeemti aur ba-maqsad hai."),
        ("Peace of heart is the ultimate luxury in a frantic modern world.", "اس تیز رفتار دنیا میں دل کا سکون سب سے بڑی نعمت ہے۔", "Is taiz dunya mein dil ka sukoon sab se barri nemat hai."),
        ("Nourish your soul with uplifting spiritual books and poetry.", "روحانی اور فکری کتابوں سے اپنے دل کو تسکین دیں۔", "Roohani kitabon se apne dil ko taskeen dein."),
        ("Remember that healing is a gradual journey, not a destination.", "یاد رکھیں کہ زخموں کا بھرنا ایک سفر ہے جس میں وقت لگتا ہے۔", "Yaad rakhein ke zakhmon ka bharna aik safar hai."),
        ("You are never truly alone; help, hope, and compassion are near.", "آپ کبھی تنہا نہیں ہیں؛ مدد، امید اور رحمت ہمیشہ قریب ہے۔", "Aap kabhi tanha nahi hain; madad aur umeed qareeb hai."),
                ("Treat yourself with immense patience as you journey toward healing and peace.", "صحت یابی اور سکون کے سفر میں اپنے ساتھ بے پناہ صبر اور محبت برتیں۔", "Sehat-yabi aur sukoon ke safar mein apne sath sabr bartein."),
        ("May your heart find serene tranquility, inner resilience, and peace!", "اللہ تعالیٰ آپ کے دل کو دائمی قرار، سکون اور اطمینان بخشے!", "Allah Ta'ala aap ke dil ko daaimi qaraar aur sukoon bakhshay!")
    ]

    # 44. Time Management & Productivity
    t44 = [
        ("Time is our most non-renewable and precious earthly resource.", "وقت ہماری زندگی کا سب سے قیمتی اور نہ لوٹنے والا سرمایہ ہے۔", "Waqt hamari zindagi ka sab se qeemti sarmaya hai."),
        ("Plan your daily schedule the previous evening before sleeping.", "اگلے دن کے کاموں کی فہرست سونے سے پہلے رات کو بنائیں۔", "Aglay din ke kamon ki fehrist sonay se pehle banayein."),
        ("Use the Pomodoro technique: work twenty-five minutes, rest five.", "پومودورو طریقہ اپنائیں: پچیس منٹ کام کریں، پانچ منٹ آرام کریں۔", "Pomodoro tareeqa apnayein: 25 minute kaam, 5 minute aaram."),
        ("Tackle your most demanding task first thing in the morning.", "سب سے مشکل اور اہم کام کو صبح سویرے سب سے پہلے نمٹائیں۔", "Sab se mushkil kaam subah sawairay sab se pehle karein."),
        ("Eliminate distractions by putting smartphones on silent focus mode.", "یکسوئی کے لیے موبائل فون کو سائلنٹ موڈ پر رکھیں۔", "Yaksooi ke liye mobile phone ko silent mode par rakhein."),
        ("Multi-tasking reduces cognitive efficiency and increases errors.", "ایک ساتھ کئی کام کرنا کارکردگی گھٹاتا ہے اور غلطیاں بڑھاتا ہے۔", "Aik sath kai kaam karna karkardagi kam karta hai."),
        ("Batch similar errands together to save commute time and gas.", "ملتے جلتے کام ایک ساتھ کریں تاکہ وقت اور پٹرول دونوں بچیں۔", "Miltay jultay kaam aik sath karein taakay bachat ho."),
        ("Set strict, clear timeboxes for checking emails and messages.", "ای میلز اور پیغامات دیکھنے کے لیے مخصوص اوقات مقرر کریں۔", "Emails aur messages ke liye makhsoos auqaat muqarrar karein."),
        ("Learn to politely decline requests that do not align with goals.", "اپنے مقاصد سے ہٹانے والے کاموں کو شائستگی سے انکار کریں۔", "Apne maqasid se hatanay walay kamon se inkaar karein."),
        ("Consistency and daily compounding effort produce massive results.", "روزانہ کی مستقل محنت وقت کے ساتھ شاندار نتائج دیتی ہے۔", "Rozana ki mustaqil mehnat waqt ke sath nataij deti hai."),
        ("How do you overcome chronic procrastination on daunting tasks?", "آپ کام کو ٹالنے کی عادت پر کیسے قابو پاتے ہیں؟", "Aap kaam ko taalnay ki aadat par kaisay qaabu paatay hain?"),
        ("Use the 2-minute rule: if it takes under two minutes, do it now.", "اگر کوئی کام دو منٹ سے کم وقت لیتا ہے تو اسے فوری نمٹا دیں۔", "Agar kaam 2 minute se kam le to fauri nibta dein."),
        ("Organize your digital files into clear, intuitive nested folders.", "کمپیوٹر کی فائلز کو سلیقے سے الگ الگ فولڈرز میں رکھیں۔", "Computer files ko saleeqay se folders mein rakhein."),
        ("Keep your physical work area uncluttered for crystal clarity.", "ذہنی یکسوئی کے لیے اپنی میز کو ہمیشہ صاف ستھرا رکھیں۔", "Zehni yaksooi ke liye apni maiz saaf rakhein."),
        ("Review your weekly accomplishments every Sunday afternoon.", "ہر اتوار کی دوپہر پورے ہفتے کی کارکردگی کا جائزہ لیں۔", "Har itwar pooray haftay ki karkardagi ka jaiza lein."),
        ("Distinguish clearly between busy activity and genuine productivity.", "محض مصروف رہنے اور حقیقی کام کرنے کے فرق کو سمجھیں۔", "Sirf masroof rehnay aur haqeeqi kaam ka farq samjhein."),
        ("Automate repetitive digital tasks using keyboard shortcuts and scripts.", "بار بار ہونے والے کاموں کو شارٹ کٹس کے ذریعے تیز بنائیں۔", "Baar baar honay walay kamon ko shortcuts se taiz karein."),
        ("Protect your peak cognitive hours for deep creative work.", "صبح کے پرسکون گھنٹوں کو اہم تخلیقی کاموں کے لیے مخصوص کریں۔", "Subah ke pursukoon ghanton ko ahem kamon ke liye rakhein."),
        ("Take real screen-free breaks to replenish your mental energy.", "تھکن دور کرنے کے لیے اسکرین سے دور رہ کر وقفہ لیں۔", "Thakan door karne ke liye screen se door waqfa lein."),
        ("A disciplined morning routine sets the tone for an effective day.", "صبح کا باقاعدہ معمول پورے دن کو کامیاب اور بااثر بناتا ہے۔", "Subah ka mamool pooray din ko kamyab banata hai."),
        ("Use visual task tracking tools like Kanban boards to see progress.", "کام کی پیش رفت دیکھنے کے لیے کانبان بورڈز کا استعمال کریں۔", "Kaam ki paish-raft dekhnay ke liye Kanban boards istemal karein."),
        ("Set realistic deadlines with a twenty percent buffer margin.", "ڈیڈ لائنز طے کرتے وقت بیس فیصد اضافی وقت ساتھ رکھیں۔", "Deadlines tay kartay waqt izafi waqt sath rakhein."),
        ("Do not let perfectionism paralyze you from completing tasks.", "بہترین کے چکر میں کام کو ادھورا مت چھوڑیں، کام مکمل کریں۔", "Behtareen ke chakkar mein kaam ko adhoora mat chhorrein."),
        ("Done is far better than perfect but perpetually unfinished.", "مکمل ہو جانا اس سے بہتر ہے کہ چیز ہمیشہ نامکمل پڑی رہے۔", "Mukammal ho jana na-mukammal rehnay se behtar hai."),
        ("Track how you spend your waking hours for three full days.", "تین دن کے لیے نوٹ کریں کہ آپ کا وقت کہاں خرچ ہوتا ہے۔", "Teen din ke liye note karein waqt kahan kharch hota hai."),
        ("Eliminate low-value habits that consume hours of daily focus.", "ان فضول عادتوں کو چھوڑیں جو روزانہ گھنٹوں ضائع کرتی ہیں۔", "Un fazool aadaton ko chhorrein jo waqt zaya karti hain."),
        ("Create standard operating checklists for recurring processes.", "روزمرہ کے معمولات کے لیے چیک لسٹ کا استعمال کریں۔", "Rozmarrah ke mamoolat ke liye checklist istemal karein."),
        ("Delegate routine administrative tasks whenever feasible.", "چھوٹے دفتری کام ٹیم کے دیگر ارکان میں تقسیم کریں۔", "Chhotay daftari kaam team mein taqseem karein."),
        ("Single-task with full presence and immerse yourself completely.", "ایک وقت میں ایک ہی کام پر پوری توجہ کے ساتھ لگ جائیں۔", "Aik waqt mein aik hi kaam par poori tawajjo dein."),
        ("Time well-invested today buys freedom and peace tomorrow.", "آج سنبھالا گیا وقت کل کی آزادی اور سکون خریدتا ہے۔", "Aaj sambhala gaya waqt kal ki azaadi aur sukoon deta hai."),
        ("Avoid checking social media notifications during focus blocks.", "کام کے دوران سوشل میڈیا کے نوٹیفیکیشنز مت دیکھیں۔", "Kaam ke dauran social media notifications mat dekhein."),
        ("Set a timer for sixty minutes and work with zero interruptions.", "ساٹھ منٹ کا ٹائمر لگائیں اور بغیر کسی مداخلت کے کام کریں۔", "60 minute ka timer lagayein aur tawajjo se kaam karein."),
        ("Keep a notepad handy to jot down sudden distracting thoughts.", "دھیان بھٹکانے والے خیالات فوراً نوٹ پیڈ پر لکھ لیں۔", "Dhyan bhatkanay walay khayalaat notepad par likh lein."),
        ("Address those thoughts only after completing your active task.", "اپنا کام مکمل کرنے کے بعد ہی ان باتوں کو دیکھیں۔", "Apna kaam mukammal karne ke baad hi unhein dekhein."),
        ("Reward yourself with a refreshing treat after major tasks.", "مشکل کام پورا ہونے پر خود کو کوئی چھوٹا سا انعام دیں۔", "Mushkil kaam poora honay par khud ko inaam dein."),
        ("Energy management is just as crucial as time management.", "وقت کی طرح جسمانی توانائی کا انتظام بھی بے حد ضروری ہے۔", "Waqt ki tarah jismani tawanaai ka intezam zaroori hai."),
        ("Stay physically active to maintain high stamina throughout the day.", "سارا دن چست رہنے کے لیے ہلکی پھلکی ورزش جاری رکھیں۔", "Sara din chust rehnay ke liye warzish jaari rakhein."),
        ("Schedule downtime and family leisure with the same seriousness.", "خاندان اور تفریح کا وقت بھی اتنی ہی سنجیدگی سے طے کریں۔", "Khandan aur tafreeh ka waqt bhi sanjeedgi se tay karein."),
        ("A well-rested mind generates creative breakthroughs effortlessly.", "تازہ دم ذہن آسانی سے نئے اور شاندار حل تلاش کرتا ہے۔", "Taaza dam zehan aasani se naye hal talash karta hai."),
        ("Focus on the vital few high-impact 20% tasks that drive 80% results.", "ان بیس فیصد اہم کاموں پر توجہ دیں جو اسی فیصد نتائج دیتے ہیں۔", "Un 20% ahem kamon par dhyan dein jo 80% nataij detay hain."),
        ("Organize your email inbox with folders and clear zero inbox.", "اپنے ای میل ان باکس کو سلیقے سے صاف رکھیں۔", "Apne email inbox ko saleeqay se saaf rakhein."),
        ("Prepare your clothes and work bag the night before.", "اگلے دن کے کپڑے اور بیگ رات کو ہی تیار رکھیں۔", "Aglay din ke kapray aur bag raat ko hi tayar rakhein."),
        ("Punctuality honors other people's time and builds immense trust.", "وقت کی پابندی دوسروں کا احترام اور اعتماد قائم کرتی ہے۔", "Waqt ki pabandi doosron ka ihtiram aur aitemad banati hai."),
        ("Never make excuses for missed deadlines; own up and deliver.", "ڈیڈ لائن نکلنے پر بہانے نہ بنائیں بلکہ کام مکمل کر کے دیں۔", "Deadline nikalnay par bahaane na banayein, kaam karein."),
        ("High performers protect their focus ruthlessly from distractions.", "کامیاب لوگ اپنی توجہ کو ہر قسم کے بگاڑ سے بچاتے ہیں۔", "Kamyab log apni tawajjo ko bachatay hain."),
        ("Master the habit of deep work in an age of constant distraction.", "ہر طرف پھیلے شور میں یکسوئی سے کام کرنے کی عادت ڈالیں۔", "Har taraf phailay shor mein yaksooi se kaam seekhein."),
        ("Small daily improvements compound into staggering achievements.", "روزانہ کی چھوٹی بہتری وقت کے ساتھ بڑی کامیابی بن جاتی ہے۔", "Rozana ki chhoti behtari barri kamyabi banti hai."),
        ("Cherish every ticking second as a golden gift from above.", "گزرتے ہوئے ہر سیکنڈ کو قدرت کا انمول تحفہ جانیں۔", "Guzartay hue har second ko qudrat ka anmol tohfa jaanein."),
        ("Thank you for choosing discipline, focus, and dedicated effort.", "نظم و ضبط، یکسوئی اور محنت کا راستہ چننے پر آپ کو سلام۔", "Nazm-o-zabt aur mehnat ka rasta chun-nay par salam."),
        ("May your daily hours be crowned with barakah and immense triumph!", "اللہ تعالیٰ آپ کے وقت میں بے پناہ برکت اور کامیابی عطا فرمائے!", "Allah Ta'ala aap ke waqt mein barkat aur kamyabi ata farmaye!")
    ]

    # 45. Traveling Abroad & Visas
    t45 = [
        ("I need to apply for a tourist visit visa at the embassy.", "مجھے سفارت خانے سے سیاحتی ویزا کے لیے درخواست دینی ہے۔", "Mujhe safarat-khanay se visit visa ke liye apply karna hai."),
        ("Ensure your passport has at least six months of remaining validity.", "دیکھ لیں کہ پاسپورٹ کی میعاد میں کم از کم چھ ماہ باقی ہوں۔", "Dekh lein ke passport ki meyaad mein 6 maah baaqi hon."),
        ("What supporting financial documents are required for the visa interview?", "ویزا انٹرویو کے لیے کون سے مالی کاغذات ساتھ لے جانے ہیں؟", "Visa interview ke liye kaun se maali kaghazat chahiyein?"),
        ("You need six months of certified bank statements and tax returns.", "چھ ماہ کا تصدیق شدہ بینک اسٹیٹمنٹ اور ٹیکس ریٹرنز درکار ہیں۔", "6 maah ka bank statement aur tax returns darkaar hain."),
        ("We booked return flight tickets with a reputable international airline.", "ہم نے ایک معتبر ایئرلائن کی دو طرفہ ٹکٹیں بک کروائیں۔", "Hum ne aik achi airline ki return tickets book karwayein."),
        ("What is the maximum baggage weight allowance per passenger?", "فی مسافر سامان کا زیادہ سے زیادہ کتنا وزن لے جانے کی اجازت ہے؟", "Fi musafir saman ka zyada se zyada kitna wazan allowed hai?"),
        ("Carry all original educational degrees, certificates, and ID cards.", "اپنی تمام اصل تعلیمی اسناد، سرٹیفکیٹس اور شناختی کارڈ ساتھ رکھیں۔", "Apni tamam asal asnaad aur card sath rakhein."),
        ("Ensure you purchase comprehensive international travel health insurance.", "بین الاقوامی سفر کے لیے ہیلتھ انشورنس ضرور خریدیں۔", "International safar ke liye travel health insurance zaroor lein."),
        ("The immigration officer stamped my passport with a multiple-entry visa.", "امیگریشن افسر نے میرے پاسپورٹ پر ملٹیپل انٹری ویزا لگا دیا۔", "Immigration officer ne passport par visa laga diya."),
        ("Travel opens your eyes to diverse human cultures and global wonders.", "سفر انسان کی آنکھیں کھولتا ہے اور دنیا کی وسعتیں دکھاتا ہے۔", "Safar insaan ki aankhein kholta hai aur dunya dikhata hai."),
        ("How long is the layover transit time between connecting flights?", "کنیکٹنگ فلائٹس کے درمیان ایئرپورٹ پر رکنے کا کتنا وقت ہے؟", "Connecting flights ke darmiyan kitna transit time hai?"),
        ("We must clear airport security and border control two hours early.", "ہمیں سیکیورٹی اور امیگریشن کے لیے دو گھنٹے پہلے پہنچنا ہوگا۔", "Humein security aur immigration ke liye 2 ghantay pehle jana hoga."),
        ("Declare any foreign currency exceeding ten thousand dollars at customs.", "دس ہزار ڈالر سے زائد غیر ملکی رقم کسٹمز پر ڈیکلیئر کریں۔", "10 hazar dollar se zyada raqam customs par declare karein."),
        ("Keep your passport, boarding passes, and wallet in a secure pouch.", "پاسپورٹ، بورڈنگ پاس اور رقم ہمیشہ محفوظ بیگ میں رکھیں۔", "Passport, boarding pass aur raqam mahfooz bag mein rakhein."),
        ("Pack essential daily medications in your cabin carry-on luggage.", "اپنی ضروری روزمرہ ادویات ہاتھ والے کیبن بیگ میں رکھیں۔", "Zaroori adwiyaat hath walay cabin bag mein rakhein."),
        ("Download offline digital maps of the destination city on your phone.", "منزل والے شہر کے آف لائن نقشے اپنے موبائل میں ڈاؤن لوڈ کریں۔", "Manzil walay shehar ke offline maps mobile mein save karein."),
        ("Exchange currency at official bank counters to get fair rates.", "کرنسی کا تبادلہ ہمیشہ بینک کے مستند کاؤنٹر سے کروائیں۔", "Currency ka tabadla hamesha bank ke counter se karwayein."),
        ("Respect the cultural norms, customs, and laws of foreign lands.", "غیر ممالک کے قوانین، آداب اور روایات کا ہمیشہ احترام کریں۔", "Ghair mumalik ke qawaneen aur aadab ka ihtiram karein."),
        ("Our flight landed smoothly on the runway despite windy weather.", "تیز ہواؤں کے باوجود ہماری پرواز بحفاظت رن وے پر اتر گئی۔", "Hawaon ke bawajood flight ba-hifazat runway par utar gayi."),
        ("Traveling as a guest builds mutual goodwill and global friendship.", "ایک اچھے سیاح کی طرح سفر کرنا قوموں میں دوستی بڑھاتا ہے۔", "Achay sayyah ki tarah safar dosti barhata hai."),
        ("Do you need a transit visa for a twelve-hour airport connection?", "کیا بارہ گھنٹے کے قیام کے لیے ٹرانزٹ ویزا درکار ہے؟", "Kya 12 ghantay ke stay ke liye transit visa chahiye?"),
        ("Check the customs duty restrictions on imported electronics.", "باہر سے لائے جانے والے الیکٹرانکس پر کسٹمز ڈیوٹی چیک کریں۔", "Electronics par customs duty ke qawaneen check karein."),
        ("Fasten your seatbelt securely whenever the seatbelt sign is illuminated.", "سیٹ بیلٹ کا نشان جلتے ہی اپنی بیلٹ فوری باندھ لیں۔", "Seatbelt ka nishan jaltay hi belt baandh lein."),
        ("The flight attendant served hot halal meals during the long journey.", "فلائٹ اٹینڈنٹ نے طویل سفر کے دوران گرم حلال کھانا پیش کیا۔", "Flight attendant ne safar mein garam halaal khana diya."),
        ("Keep a digital photograph of your passport and visa on email.", "پاسپورٹ اور ویزا کی کاپی اپنی ای میل پر ہمیشہ محفوظ رکھیں۔", "Passport aur visa ki copy email par mahfooz rakhein."),
        ("What is the local emergency ambulance and police number here?", "یہاں مقامی ایمبولینس اور پولیس کا ایمرجنسی نمبر کیا ہے؟", "Yahan emergency ambulance aur police ka number kya hai?"),
        ("Purchase a local prepaid data SIM card at the airport arrival hall.", "ایئرپورٹ پہنچتے ہی انٹرنیٹ ڈیٹا والی لوکل سم خرید لیں۔", "Airport pohanchtay hi local internet SIM khareed lein."),
        ("Learn a few basic phrases in the local language of the host nation.", "میزبان ملک کی زبان کے چند بنیادی الفاظ اور جملے سیکھیں۔", "Mezban mulk ki zaban ke ahem alfaaz seekhein."),
        ("Always keep your hotel business card with address in your pocket.", "ہوٹل کا کارڈ پتہ کے ساتھ ہمیشہ اپنی جیب میں رکھیں۔", "Hotel ka card address ke sath hamesha paas rakhein."),
        ("A pleasant smile bridges linguistic divides in any foreign city.", "ایک خوبصورت مسکراہٹ کسی بھی غیر ملک میں زبان کی دوری مٹا دیتی ہے۔", "Aik muskurahat kisi bhi mulk mein zaban ki doori mita deti hai."),
        ("Are luggage carts available free of charge in the baggage claim?", "کیا سامان اٹھانے والی ٹرالیاں ایئرپورٹ پر مفت دستیاب ہیں؟", "Kya saman ki trolleys airport par muft hain?"),
        ("Collect your checked baggage from carousel number four.", "بیلٹ نمبر چار سے اپنا بک کروایا گیا سامان وصول کریں۔", "Belt number 4 se apna saman wasool karein."),
        ("If your baggage is delayed, report to the lost luggage counter.", "اگر سامان نہ پہنچے تو گمشدہ سامان کے کاؤنٹر پر رپورٹ کریں۔", "Agar saman na pohanchay to lost luggage par report karein."),
        ("Confirm your departure terminal and boarding gate in advance.", "اپنا ٹرمینل اور بورڈنگ گیٹ پہلے سے کنفرم کر لیں۔", "Apna terminal aur boarding gate pehle se confirm karein."),
        ("Drink plenty of water on long flights to avoid jet lag fatigue.", "طویل پروازوں کے دوران تھکن سے بچنے کے لیے زیادہ پانی پئیں۔", "Lambi flights mein thakan se bachnay ke liye paani piyein."),
        ("Set your watch to the destination time zone upon boarding.", "جہاز میں بیٹھتے ہی اپنی گھڑی کا وقت منزل کے مطابق کر لیں۔", "Jahaz mein baithtay hi ghari ka waqt manzil ke mutabiq karein."),
        ("Keep your passport handy when boarding the aircraft.", "جہاز میں سوار ہوتے وقت اپنا پاسپورٹ ہاتھ میں رکھیں۔", "Jahaz mein sawaar hotay waqt passport hath mein rakhein."),
        ("Do not leave your personal bags unattended at the airport.", "ایئرپورٹ پر اپنا سامان کبھی لاوارث مت چھوڑیں۔", "Airport par apna saman kabhi la-waaris mat chhorrein."),
        ("Follow all airport signage carefully to find your connecting gate.", "اگلے گیٹ تک پہنچنے کے لیے سائن بورڈز پر نظر رکھیں۔", "Aglay gate tak pohanchnay ke liye signboards dekhein."),
        ("Traveling enriches the mind with wisdom and humility.", "سفر انسان کے ذہن کو حکمت، علم اور عاجزی عطا کرتا ہے۔", "Safar insaan ke zehan ko hikmat aur ilm deta hai."),
        ("Ensure your international credit card is enabled for foreign spend.", "دیکھ لیں کہ کارڈ بیرون ملک ادائیگیوں کے لیے کھلا ہو۔", "Dekh lein ke card bairoon-e-mulk payments ke liye khula ho."),
        ("Dress comfortably in loose layers for long overnight international flights.", "لمبی پروازوں کے لیے آرام دہ اور ڈھیلا لباس پہنیں۔", "Lambi flights ke liye aaram deh libaas pehnein."),
        ("Check the weather forecast of your destination before packing.", "سامان پیک کرنے سے پہلے منزل کے موسم کی صورتحال دیکھیں۔", "Saman pack karne se pehle manzil ka mausam dekhein."),
        ("Keep a pen in your bag to fill out customs declaration cards.", "کسٹمز فارم بھرنے کے لیے اپنے بیگ میں پین ساتھ رکھیں۔", "Customs form bharnay ke liye bag mein pen sath rakhein."),
        ("Store your passport in the hotel safety deposit locker.", "ہوٹل کے کمرے میں پاسپورٹ محفوظ لاکر میں رکھیں۔", "Hotel ke kamray mein passport safe locker mein rakhein."),
        ("Be polite and respectful to airline staff and border officers.", "ایئرپورٹ عملے اور بارڈر افسران سے ہمیشہ ادب سے پیش آئیں۔", "Airport amlay aur officers se hamesha adab se pesh aayein."),
        ("Capture beautiful memories and write down travel reflections.", "خوبصورت تصاویر لیں اور اپنے سفری تجربات کو ڈائری میں لکھیں۔", "Khubsurat photos lein aur safar ki yaadein likhein."),
        ("Safe travels and smooth journeys across skies and lands!", "اللہ تعالیٰ آپ کے تمام اسفار کو محفوظ اور آسان فرمائے!", "Allah Ta'ala aap ke safar ko mahfooz aur aasan farmaye!"),
                ("Every new destination teaches us deep appreciation for our own homeland.", "ہر نیا ملک ہمیں اپنے وطن کی قدر و قیمت کا مزید احساس دلاتا ہے۔", "Har naya mulk humein apne watan ki qadr ka ehsas dilata hai."),
        ("May your international voyage be rewarding and transformative!", "اللہ کرے آپ کا بیرون ملک سفر کامیابیوں اور علم سے بھرپور ہو!", "Allah karay aap ka safar kamyabi aur ilm se bharpoor ho!")
    ]

    return [
        {"id": 41, "name": "Public Speaking & Presentations", "urduName": "تقاریر اور پریزنٹیشنز", "icon": "record_voice_over", "desc": "Stage presence, slides, audience engagement, delivery, and confidence.", "sentences": t41},
        {"id": 42, "name": "Debates & Discussions", "urduName": "مباحثہ اور سنجیدہ گفتگو", "icon": "forum", "desc": "Critical thinking, argumentation, rebuttal, evidence, and logical discourse.", "sentences": t42},
        {"id": 43, "name": "Mental Health & Stress Relief", "urduName": "ذہنی صحت اور سکون", "icon": "spa", "desc": "Mindfulness, anxiety relief, gratitude, inner peace, and self-care.", "sentences": t43},
        {"id": 44, "name": "Time Management & Productivity", "urduName": "وقت کی پابندی اور پیداواری صلاحیت", "icon": "schedule", "desc": "Prioritization, habits, focus blocks, deep work, and discipline.", "sentences": t44},
        {"id": 45, "name": "Traveling Abroad & Visas", "urduName": "بیرون ملک سفر اور ویزا", "icon": "flight_takeoff", "desc": "Visas, embassies, airports, flights, customs, and travel tips.", "sentences": t45}
    ]
