# -*- coding: utf-8 -*-

def get_46_to_50():
    # 46. Driving & Road Safety
    t46 = [
        ("Always fasten your three-point seatbelt before turning on the engine.", "گاڑی اسٹارٹ کرنے سے پہلے سیٹ بیلٹ باندھنا لازمی عادت بنائیں۔", "Gaari start karne se pehle seatbelt baandhein."),
        ("Never use your mobile phone while driving on busy highways.", "مصروف سڑکوں پر گاڑی چلاتے وقت موبائل فون کا استعمال ہرگز نہ کریں۔", "Sarakon par gaari chalatay waqt mobile istemal na karein."),
        ("Obey traffic signals, speed limits, and pedestrian zebra crossings.", "ٹریفک سگنلز، رفتار کی حد اور زیبرا کراسنگ کا مکمل احترام کریں۔", "Traffic signals aur speed limits ka ihtiram karein."),
        ("Check your rear-view and side mirrors before changing lanes.", "لین تبدیل کرنے سے پہلے دائیں بائیں اور بیک ویو شیشے ضرور دیکھیں۔", "Lane badalnay se pehle side mirrors zaroor dekhein."),
        ("Use your turn indicators well in advance when making a turn.", "موڑ مڑنے سے کافی پہلے انڈیکیٹر کا اشارہ دیں۔", "Morr murnay se pehle indicator ka ishara dein."),
        ("Maintain a safe three-second braking distance from the car ahead.", "سامنے والی گاڑی سے کم از کم تین سیکنڈ کے فاصلے پر رہیں۔", "Samnay wali gaari se faasla barqarar rakhein."),
        ("Check your vehicle's engine oil level and tire pressure weekly.", "ہر ہفتے گاڑی کا انجن آئل اور ٹائروں میں ہوا کا پریشر چیک کریں۔", "Har haftay engine oil aur tire pressure check karein."),
        ("Slow down and drive cautiously in heavy rain and slippery mud.", "تیز بارش اور پھسلن والی سڑک پر گاڑی کی رفتار کم رکھیں۔", "Taiz barish mein gaari ki raftaar kam rakhein."),
        ("Turn on your fog lights and hazard lights during dense winter fog.", "سردیوں کی شدید دھند میں فوگ لائٹس ضرور آن کریں۔", "Sardiyon ki dhund mein fog lights on karein."),
        ("Road safety saves precious human lives and prevents tragedies.", "ٹریفک قوانین کی پابندی قیمتی انسانی جانوں کی حفاظت کرتی ہے۔", "Traffic qawaneen ki pabandi insani janon ki hifazat karti hai."),
        ("How do I parallel park smoothly in a tight crowded parking spot?", "تنگ جگہ پر گاڑی کو سلیقے سے متوازی کیسے پارک کیا جائے؟", "Tang jagah par gaari parallel park kaisay karein?"),
        ("Always give way to emergency ambulances and fire brigade trucks.", "ایمبولینس اور فائر بریگیڈ کی گاڑیوں کو ہمیشہ راستہ دیں۔", "Ambulance aur fire brigade ko hamesha rasta dein."),
        ("Do not overtake recklessly from the wrong left side on highways.", "موٹروے پر بائیں جانب سے خطرناک اوور ٹیکنگ سے پرہیز کریں۔", "Motorway par ghalt side se overtake na karein."),
        ("Carry your driving license, vehicle registration, and insurance tokens.", "اپنا ڈرائیونگ لائسنس اور گاڑی کے کاغذات ہمیشہ ساتھ رکھیں۔", "Apna driving license aur kaghazat sath rakhein."),
        ("Ensure your headlights are aligned properly and not blinding drivers.", "دیکھیں کہ ہیڈلائٹس سامنے والوں کی آنکھوں میں نہ لگ رہی ہوں۔", "Dekhein ke headlights samnay walon ko tang na karein."),
        ("Replace worn-out windshield wiper blades before rainy monsoon.", "برسات سے پہلے ونڈ اسکرین کے پرانے وائپرز تبدیل کروائیں۔", "Barsaat se pehle wipers tabdeel karwayein."),
        ("Never drive when fatigued; pull over at a rest stop for coffee.", "نیند اور تھکن میں ڈرائیونگ نہ کریں؛ سروس ایریا پر رکیں۔", "Neend aur thakan mein driving na karein; aaram karein."),
        ("Pedestrians and cyclists have the right of way in residential zones.", "رہائشی علاقوں میں پیدل چلنے والوں کو ہمیشہ پہلے راستہ دیں۔", "Rehaishi ilaaqon mein paidal chalnay walon ko rasta dein."),
        ("Avoid aggressive road rage; patience defuses volatile traffic tension.", "غصے اور تکرار سے بچیں؛ صبر ٹریفک کا غصہ ختم کرتا ہے۔", "Ghussay se bachein; sabr traffic mein laraai rokata hai."),
        ("A safe, courteous driver protects everyone sharing the open road.", "ایک شائستہ ڈرائیور سڑک پر موجود ہر شخص کا محافظ ہوتا ہے۔", "Aik shaista driver har shakhs ka muhafiz hota hai."),
        ("Inspect your vehicle's spare tire, jack, and wheel spanner.", "گاڑی کا اضافی ٹائر (اسٹپنی) اور جیک باقاعدگی سے چیک کریں۔", "Gaari ka stepney tire aur jack check karein."),
        ("Never leave young children or pets unattended inside parked cars.", "پارک کی گئی گاڑی میں بچوں کو کبھی تنہا مت چھوڑیں۔", "Gaari mein bachon ko kabhi tanha mat chhorrein."),
        ("Adhere to school zone speed limits of twenty kilometers per hour.", "اسکولوں کے قریب رفتار بیس کلومیٹر فی گھنٹہ سے زیادہ نہ رکھیں۔", "School ke qareeb raftaar 20 km/h se zyada na rakhein."),
        ("Check your brake fluid and radiator coolant levels regularly.", "بریک آئل اور ریڈی ایٹر کا کولنٹ باقاعدگی سے چیک کریں۔", "Brake oil aur coolant baqaidgi se check karein."),
        ("Never drive under the influence of medications causing drowsiness.", "غنودگی لانے والی ادویات کھا کر گاڑی ہرگز نہ چلائیں۔", "Ghanoodgi wali medicines khaa kar driving na karein."),
        ("Always stop completely behind the white line at red traffic lights.", "سرخ اشارے پر سفید لکیر کے پیچھے مکمل گاڑی روکیں۔", "Laal batii par safaid line ke peechay gaari rokein."),
        ("Motorcyclists must always wear a certified protective helmet.", "موٹر سائیکل سوار ہمیشہ معیاری ہیلمٹ پہنیں۔", "Motorcycle sawaar hamesha helmet pehnein."),
        ("Use low beam headlights when driving through heavy urban traffic.", "شہر کے اندر ہمیشہ لو بیم لائٹس استعمال کریں۔", "Shehar ke andar low beam lights istemal karein."),
        ("Keep a small fire extinguisher and first aid kit in the car trunk.", "گاڑی کی ڈگی میں فرسٹ ایڈ کٹ اور آگ بجھانے والا آلہ رکھیں۔", "Gaari ki diggi mein first aid kit aur safety aalaat rakhein."),
        ("Safe driving is a mark of high civic responsibility and character.", "محفوظ ڈرائیونگ اچھے شہری اور بلند اخلاق کی پہچان ہے۔", "Mahfooz driving achay shehri ki pehchan hai."),
        ("What should you do if your car engine overheats on motorway?", "اگر موٹروے پر گاڑی کا انجن گرم ہو جائے تو کیا کرنا چاہیے؟", "Agar motorway par gaari garam ho jaye to kya karein?"),
        ("Safely guide your vehicle to the emergency hard shoulder lane.", "گاڑی کو آرام سے سائیڈ پر ایمرجنسی لین میں کھڑا کریں۔", "Gaari ko side par emergency lane mein kharra karein."),
        ("Turn on your emergency hazard blinkers and set up warning triangles.", "ایمرجینسی لائٹس آن کریں اور دور تک تنبیہی اشارہ لگائیں۔", "Emergency lights on karein aur triangle lagayein."),
        ("Wait for highway motorway police helpline 130 to arrive safely.", "موٹروے پولیس کی ہیلپ لائن ایک سو تیس پر کال کر کے انتظار کریں۔", "Motorway police helpline 130 par call karein."),
        ("Ensure your child rides in an age-appropriate rear car seat.", "چھوٹے بچوں کے لیے کار سیٹ کا استعمال لازمی بنائیں۔", "Chhotay bachon ke liye car seat istemal karein."),
        ("Avoid sudden harsh acceleration and aggressive braking to save fuel.", "اچانک ریس دینے اور بریک لگانے سے پرہیز کریں تاکہ پٹرول بچے۔", "Achanak race aur brake se parhez karein taakay petrol bachay."),
        ("Rotate your tires every ten thousand kilometers for even wear.", "ٹائروں کی عمر بڑھانے کے لیے ہر دس ہزار کلومیٹر پر پوزیشن بدلیں۔", "Tires ki position har 10 hazar km par badlein."),
        ("Keep your windows rolled up during severe sandstorms or smog.", "گرد کے طوفان یا اسموگ میں شیشے مکمل بند رکھیں۔", "Toofan ya smog mein sheeshay band rakhein."),
        ("Pay attention to flashing yellow caution lights at intersections.", "چوراہے پر جلتی بجھتی پیلی بتی پر محتاط ہو کر نکلیں۔", "Chaurahay par peeli batti par ahtiyat karein."),
        ("Patience and humility behind the wheel prevent road accidents.", "اسٹیئرنگ وہیل کے پیچھے صبر اور عاجزی حادثات سے بچاتی ہے۔", "Steering wheel ke peechay sabr haadsaat se bachata hai."),
        ("Always lock car doors and do not leave valuables visible on seats.", "گاڑی کے دروازے لاک کریں اور سامان سیٹ پر مت چھوڑیں۔", "Darwazay lock karein aur saman seat par na chhorrein."),
        ("Check that all brake lights and reverse lights are functioning.", "تسلی کریں کہ تمام پچھلی بریک لائٹس صحیح جل رہی ہوں۔", "Dekhein ke pichli brake lights sahi kaam kar rahi hon."),
        ("Allow cyclists plenty of room when passing them on narrow roads.", "تنگ سڑکوں پر سائیکل سواروں کو مناسب فاصلہ دیں۔", "Tang sarakon par cycle walon ko faasla dein."),
        ("Drive at a calm, steady pace that keeps passengers comfortable.", "گاڑی کو پرسکون اور متوازن رفتار میں چلائیں۔", "Gaari ko pursukoon raftaar mein chalayein."),
        ("Respect the instructions of traffic wardens managing busy junctions.", "ٹریفک وارڈنز کے اشاروں اور ہدایات پر عمل کریں۔", "Traffic wardens ki hidayaat par amal karein."),
        ("Keep your windshield clean and topped with washer fluid.", "ونڈ اسکرین کو ہمیشہ صاف اور پانی سے بھرا رکھیں۔", "Windscreen ko hamesha saaf rakhein."),
        ("Never rush recklessly; reaching safely is the true priority.", "کبھی جلد بازی مت کریں؛ بحفاظت پہنچنا اصل مقصد ہے۔", "Kabhi jald-baazi mat karein; hifazat awaleen hai."),
        ("Courteous drivers create a polite, peaceful civilized society.", "شائستہ ڈرائیور ایک مہذب اور پرامن معاشرہ بناتے ہیں۔", "Shaista drivers aik mohazzab ma'ashra banatay hain."),
        ("Wishing you safe, peaceful, and pleasant journeys on every road!", "اللہ تعالیٰ آپ کے ہر سفر کو محفوظ، پرامن اور آسان بنائے!", "Allah Ta'ala aap ke har safar ko mahfooz banaye!"),
        ("May you always reach your destinations in safety, peace, and health!", "اللہ کرے آپ ہمیشہ اپنی منزلوں پر خیر و عافیت سے پہنچیں!", "Allah karay aap hamesha khairiyat se pohanchein!")
    ]

    # 47. Job Interviews & Career Growth
    t47 = [
        ("Tell me about yourself, your educational background, and experience.", "اپنے بارے میں، اپنی تعلیم اور کام کے تجربے سے آگاہ کریں۔", "Apne baare mein, taleem aur tajrubay se aagah karein."),
        ("I hold a degree in Computer Science with four years of industry work.", "میں نے کمپیوٹر سائنس میں ڈگری اور چار سال عملی کام کیا ہے۔", "Mein ne Computer Science mein degree aur 4 saal kaam kiya hai."),
        ("What do you consider your greatest professional strength and asset?", "آپ کے نزدیک آپ کی سب سے بڑی پیشہ ورانہ صلاحیت کیا ہے؟", "Aap ke nazdeek aap ki sab se barri salahiyat kya hai?"),
        ("My core strength is solving complex problems under tight deadlines.", "میری سب سے بڑی خوبی سخت ڈیڈ لائنز میں پیچیدہ مسائل حل کرنا ہے۔", "Meri khoobi deadlines mein masail hal karna hai."),
        ("How do you handle constructive criticism and performance reviews?", "آپ اصلاحی مشوروں اور کارکردگی کے جائزے کو کیسے لیتے ہیں؟", "Aap tanqeed aur performance review ko kaisay letay hain?"),
        ("I view constructive feedback as an invaluable pathway to growth.", "میں اصلاحی رائے کو اپنی ذاتی ترقی کا بہترین موقع سمجھتا ہوں۔", "Mein feedback ko apni behtari ka mauqa samajhta hoon."),
        ("Why are you passionate about joining our multinational organization?", "آپ ہمارے بین الاقوامی ادارے میں کام کرنے کے لیے کیوں پرجوش ہیں؟", "Aap hamare idaray mein kaam karne ke liye kyun purjosh hain?"),
        ("I admire your company's innovative culture and commitment to excellence.", "میں آپ کی کمپنی کی جدید سوچ اور اعلیٰ معیار کا معترف ہوں۔", "Mein company ki jadeed soch aur meyaar ka motarif hoon."),
        ("Describe a challenging project you successfully delivered as a team.", "کسی ایسے مشکل پروجیکٹ کا ذکر کریں جو آپ نے ٹیم کے ساتھ مکمل کیا۔", "Kisi aisay project ka zikr karein jo team ke sath kiya."),
        ("We unified cross-functional teams to launch the product on schedule.", "ہم نے مختلف ٹیموں کو جوڑ کر پروڈکٹ کو وقت پر لانچ کیا۔", "Hum ne teams ko mila kar product waqt par launch kiya."),
        ("What are your salary expectations for this senior managerial role?", "اس سینیئر مینیجر کے عہدے کے لیے آپ کی تنخواہ کی کیا توقعات ہیں؟", "Is ohday ke liye aap ki salary ki kya tawaqqoaat hain?"),
        ("I am seeking a competitive package aligned with industry standards.", "میں مارکیٹ کے معیار اور اپنی مہارت کے مطابق پیکیج کا خواہشمند ہوں۔", "Mein market meyaar ke mutabiq package chahta hoon."),
        ("Where do you see yourself professionally five years from now?", "آپ اگلے پانچ سالوں میں خود کو کس پیشہ ورانہ مقام پر دیکھتے ہیں؟", "Aap aglay 5 saalon mein khud ko kahan dekhtay hain?"),
        ("I aim to lead strategic engineering initiatives and mentor young talent.", "میں اہم تزویراتی منصوبوں کی قیادت اور نئے ٹیلنٹ کی رہنمائی چاہتا ہوں۔", "Mein strategic projects ki qayadat chahta hoon."),
        ("Do you have any questions for us regarding the role or company?", "کیا آپ کا اس عہدے یا کمپنی کے بارے میں ہم سے کوئی سوال ہے؟", "Kya aap ka is ohday ya company ke baare mein koi sawal hai?"),
        ("Could you describe the typical career advancement path in this team?", "کیا آپ اس ٹیم میں ترقی کے مواقع کے بارے میں بتا سکتے ہیں؟", "Kya aap team mein taraqi ke raston ke baare mein bata saktay hain?"),
        ("Dress in sharp, professional business formal attire for the interview.", "انٹرویو کے لیے صاف ستھرا اور باوقار رسمی لباس پہنیں۔", "Interview ke liye saaf suthra aur formal libaas pehnein."),
        ("Arrive fifteen minutes prior to the scheduled interview appointment.", "انٹرویو کے مقررہ وقت سے پندرہ منٹ پہلے دفتر پہنچیں۔", "Interview ke waqt se 15 minute pehle pohanchein."),
        ("Maintain confident body posture, a warm smile, and a firm handshake.", "پراعتماد انداز، مسکراہٹ اور گرمجوشی سے سلام کریں۔", "Pur-aitemad andaaz aur muskurahat se salam karein."),
        ("Send a thoughtful thank-you email within twenty-four hours after interview.", "انٹرویو کے بعد چوبیس گھنٹے کے اندر شائستہ تشکر کی ای میل بھیجیں۔", "Interview ke baad shukriya ki email bhejein."),
        ("Highlight your measurable accomplishments using specific data and metrics.", "اپنی کامیابیوں کو اعداد و شمار اور ٹھوس نتائج کے ساتھ بیان کریں۔", "Apni kamyabiyon ko aadaad-o-shumaar ke sath bayan karein."),
        ("Showcase your adaptability in embracing new technologies quickly.", "نئی ٹیکنالوجیز کو تیزی سے سیکھنے کی صلاحیت کو نمایاں کریں۔", "Nayi technologies taizi se seekhnay ki salahiyat dikhayein."),
        ("Continuous self-learning is the key to thriving in modern careers.", "مسلسل نیا علم سیکھنا جدید کیریئر میں کامیابی کی کلید ہے۔", "Musalsal seekhna jadeed career mein kamyabi ki chaabi hai."),
        ("Never speak negatively about previous employers or colleagues.", "اپنے پرانے ادارے یا ساتھیوں کے بارے میں منفی باتیں کبھی نہ کریں۔", "Puranay idaray ke baare mein manfi baatein na karein."),
        ("Demonstrate leadership by taking ownership of challenging initiatives.", "مشکل کاموں کی خود ذمہ داری لے کر اپنی قیادت کا ثبوت دیں۔", "Mushkil kamon ki zimmedari le kar qayadat dikhayein."),
        ("Research the company's recent news, products, and mission beforehand.", "انٹرویو سے پہلے کمپنی کی مصنوعات اور مشن کے بارے میں معلومات لیں۔", "Company ke mission ke baare mein pehle se jaaney."),
        ("Practice behavioral interview questions using the STAR framework.", "اسٹار تکنیک کے تحت صورتحال، عمل اور نتائج کے مطابق مشق کریں۔", "STAR framework ke mutabiq interview ki mashq karein."),
        ("Explain how your expertise directly benefits the employer's bottom line.", "بتائیں کہ آپ کا ہنر ادارے کو کس طرح براہ راست فائدہ دے گا۔", "Batayein ke aap ka hunar idaray ko kaisay faida dega."),
        ("Confidence stems from rigorous preparation and authentic self-belief.", "اعتماد بھرپور تیاری اور اپنی ذات پر سچے بھروسے سے آتا ہے۔", "Aitemad bharpoor tayari aur khud par bharosay se aata hai."),
        ("Every interview is an opportunity to learn, network, and grow.", "ہر انٹرویو سیکھنے، روابط بڑھانے اور آگے بڑھنے کا موقع ہے۔", "Har interview seekhnay aur aagay barhnay ka mauqa hai."),
        ("Negotiate employment contracts with poise, clarity, and professionalism.", "ملازمت کے معاہدے پر وقار اور پیشہ ورانہ انداز سے بات چیت کریں۔", "Job contract par waqaar aur clarity se baat karein."),
        ("Highlight certifications from accredited international institutions.", "معتبر بین الاقوامی اداروں سے حاصل کردہ سرٹیفکیٹس کا ذکر کریں۔", "Mo'tabar idaron ke certificates ka zikr karein."),
        ("Show how you foster collaboration and harmony within diverse teams.", "دکھائیں کہ آپ ٹیم میں اتحاد اور باہمی تعاون کو کیسے فروغ دیتے ہیں۔", "Dikhayein ke aap team mein ittehad kaisay banatay hain."),
        ("A growth mindset transforms workplace challenges into career leaps.", "مثبت سوچ کام کے چیلنجز کو ترقی کی سیڑھی میں بدل دیتی ہے۔", "Musbat soch challenges ko taraqi ki seerhi banati hai."),
        ("Bring printed copies of your updated resume in a neat leather folder.", "اپنے سی وی کی پرنٹ شدہ کاپیاں صاف فولڈر میں ساتھ رکھیں۔", "CV ki printed copies saaf folder mein sath rakhein."),
        ("Answer questions directly with clarity, conciseness, and conviction.", "سوالات کے سیدھے، جامع اور پر اعتماد جوابات دیں۔", "Sawalat ke seedhay, mukhtasir aur pur-aitemad jawab dein."),
        ("Speak about your failures in terms of the valuable lessons learned.", "اپنی پرانی ناکامیوں کو سیکھے گئے اہم اسباق کے طور پر پیش کریں۔", "Na-kamyabiyon ko seekhay gaye sabaq ke tor par pesh karein."),
        ("Express genuine enthusiasm for the company's long-term vision.", "کمپنی کے طویل مدتی وژن کے لیے اپنے سچے جذبے کا اظہار کریں۔", "Company ke vision ke liye apne jazbay ka izhaar karein."),
        ("Maintain professional composure even during intense stress interviews.", "دباؤ والے مشکل سوالات کے دوران بھی اپنے اعصاب پر قابو رکھیں۔", "Dabao walay sawalat mein bhi pursukoon rahein."),
        ("Your unique combination of skills, attitude, and ethics is your edge.", "آپ کا ہنر، مثبت رویہ اور اخلاق ہی آپ کی اصل طاقت ہے۔", "Aap ka hunar, rawaiya aur ikhlaaq aap ki taaqat hai."),
        ("Follow up politely if you haven't received feedback within a week.", "اگر ایک ہفتے میں جواب نہ آئے تو شائستگی سے فالو اپ لیں۔", "Agar aik haftay mein jawab na aaye to follow up lein."),
        ("Keep your resume concise, tailored, and strictly error-free.", "اپنا سی وی مختصر، متعلقہ اور غلطیوں سے پاک رکھیں۔", "Apna CV mukhtasir aur ghaltiyon se paak rakhein."),
        ("Mentorship accelerates your professional trajectory exponentially.", "کسی اچھے استاد کی رہنمائی کیریئر کو تیزی سے آگے بڑھاتی ہے۔", "Kisi ustaad ki rehnumai career ko taizi se barhati hai."),
        ("Workplace ethics and reliability earn lifelong professional loyalty.", "دیانت داری اور بھروسہ مندی کیریئر میں ہمیشہ عزت دلاتی ہے۔", "Dyanat-dari career mein hamesha izzat dilati hai."),
        ("Stay curious, hungry for knowledge, and open to continuous reinvention.", "ہمیشہ نیا علم حاصل کرنے کے لیے تیار اور متجسس رہیں۔", "Hamesha naya ilm seekhnay ke liye tayar rahein."),
        ("Celebrate every job offer with gratitude and humility.", "کسی بھی ملازمت کی پیشکش پر عاجزی اور شکر گزاری کا مظاہرہ کریں۔", "Job offer par aajzi aur shukr ka izhaar karein."),
        ("Hard work paired with high integrity guarantees ultimate triumph.", "سچی محنت اور دیانت داری ہمیشہ شاندار کامیابی دلاتی ہے۔", "Mehnat aur dyanat-dari hamesha kamyabi dilati hai."),
        ("You have what it takes to excel; step forward with unwavering courage.", "آپ میں آگے بڑھنے کی پوری صلاحیت ہے؛ ہمت کے ساتھ قدم بڑھائیں۔", "Aap mein aagay barhnay ki poori salahiyat hai."),
        ("Thank you for considering my application for this distinguished role.", "اس معزز عہدے کے لیے میری درخواست پر غور کرنے کا بہت شکریہ۔", "Is ohday ke liye meri darkhwast par ghaur karne ka shukriya."),
        ("May your career be blessed with limitless success, leadership, and joy!", "اللہ تعالیٰ آپ کے کیریئر کو غیر معمولی ترقی اور برکتوں سے نوازے!", "Allah Ta'ala aap ke career ko taraqi aur barkat ata farmaye!")
    ]

    # 48. Customer Service & Client Care
    t48 = [
        ("Thank you for contacting our customer support team; how may I help?", "ہماری کسٹمر سپورٹ ٹیم سے رابطہ کرنے کا شکریہ؛ میں کیا خدمت کروں؟", "Customer support se rabta karne ka shukriya; mein kya madad karoon?"),
        ("I deeply apologize for the inconvenience and delay you experienced.", "آپ کو پیش آنے والی زحمت اور تاخیر کے لیے میں معذرت خواہ ہوں۔", "Aap ko paish aanay wali takleef ke liye mein maazrat chahta hoon."),
        ("Please allow me a moment to review your order details on system.", "مجھے سسٹم پر آپ کے آرڈر کی تفصیلات دیکھنے کے لیے ایک لمحہ دیں۔", "Mujhe system par order ki tafseelaat dekhnay ke liye waqt dein."),
        ("I understand your frustration completely; let me resolve this immediately.", "میں آپ کی پریشانی سمجھتا ہوں؛ آئیے میں اسے فوری حل کرتا ہوں۔", "Mein aap ki pareshani samajhta hoon; fauri hal karta hoon."),
        ("We will dispatch a free replacement parcel to your address today.", "ہم آج ہی آپ کے پتے پر مفت متبادل پارسل روانہ کر دیں گے۔", "Hum aaj hi aap ke patay par naya parcel rawana kar dein ge."),
        ("Could you please provide your registered phone number or tracking ID?", "کیا آپ اپنا رجسٹرڈ فون نمبر یا ٹریکنگ آئی ڈی بتا سکتے ہیں؟", "Kya aap apna registered phone number ya tracking ID bata saktay hain?"),
        ("Your complete satisfaction is our company's highest priority.", "آپ کا مکمل اطمینان ہمارے ادارے کی اولین ترجیح ہے۔", "Aap ka mukammal itminaan hamari awaleen tarjeeh hai."),
        ("We have processed a full refund directly to your original bank card.", "ہم نے آپ کے کارڈ پر پوری رقم واپس (ریفنڈ) منتقل کر دی ہے۔", "Hum ne aap ke card par poori raqam refund kar di hai."),
        ("Thank you for your valuable feedback; it helps us improve services.", "آپ کی قیمتی رائے کا شکریہ؛ یہ ہماری خدمات کو بہتر بناتی ہے۔", "Aap ki qeemti raye ka shukriya; yeh hamari khidmaat behtar karti hai."),
        ("Treat every customer with utmost empathy, respect, and active care.", "ہر کسٹمر کے ساتھ ہمدردی، عزت اور خلوص کے ساتھ پیش آئیں۔", "Har customer ke sath hamdardi aur izzat se pesh aayein."),
        ("How can we assist you with tracking your international parcel delivery?", "ہم آپ کے بین الاقوامی پارسل کی ٹریکنگ میں کیا مدد کر سکتے ہیں؟", "Hum parcel ki tracking mein kya madad kar saktay hain?"),
        ("Our technical support helpline is available twenty-four hours daily.", "ہماری ٹیکنیکل سپورٹ ہیلپ لائن چوبیس گھنٹے حاضر ہے۔", "Hamari technical support helpline 24 ghantay hazir hai."),
        ("I have escalated your ticket to our senior engineering supervisor.", "میں نے آپ کی شکایت سینیئر سپروائزر کو فارورڈ کر دی ہے۔", "Mein ne aap ki shikayat senior supervisor ko bhej di hai."),
        ("You will receive an SMS confirmation update within two hours.", "آپ کو دو گھنٹے کے اندر تصدیقی ایس ایم ایس مل جائے گا۔", "Aap ko 2 ghantay mein SMS update mil jaye ga."),
        ("We appreciate your patience while we investigate this system issue.", "اس خرابی کی جانچ کے دوران آپ کے صبر کا بے حد شکریہ۔", "Is kharabi ki jaanch ke dauran aap ke sabr ka shukriya."),
        ("Is there anything else I can assist you with this afternoon?", "کیا میں آج دوپہر کسی اور معاملے میں بھی آپ کی مدد کر سکتا ہوں؟", "Kya mein kisi aur maamlay mein bhi aap ki madad kar sakta hoon?"),
        ("A satisfied customer is the greatest ambassador for any brand.", "ایک مطمئن گاہک ادارے کا سب سے بڑا سفیر ہوتا ہے۔", "Aik mutmain customer idaray ka sab se barra safeer hota hai."),
        ("Listening actively without interrupting calms an upset caller.", "بغیر ٹوکے بات سننا ناراض کسٹمر کا غصہ ٹھنڈا کر دیتا ہے۔", "Baghair tookay baat sunna customer ka ghussa thanda karta hai."),
        ("Never argue with a customer; focus on finding constructive solutions.", "کسٹمر سے بحث نہ کریں بلکہ مسئلے کے فوری حل پر توجہ دیں۔", "Customer se behas na karein balkay hal par tawajjo dein."),
        ("Clear, polite communication turns dissatisfied users into loyal fans.", "شائستہ بات چیت ناراض گاہک کو مستقل وفادار بنا دیتی ہے۔", "Shaista baat cheet naraz gahak ko wafadar bana deti hai."),
        ("Could you please fill out our brief 1-minute satisfaction survey?", "کیا آپ ہماری سروس کے بارے میں ایک منٹ کا فیڈ بیک دے سکتے ہیں؟", "Kya aap service ke baare mein aik minute ka feedback dein ge?"),
        ("We offer a 30-day money-back guarantee with no questions asked.", "ہم تیس دن کی بلامشروط رقم واپسی کی ضمانت دیتے ہیں۔", "Hum 30 din ki bila-mashroot raqam wapsi ki guarantee detay hain."),
        ("Your complaint has been successfully resolved; thank you for patience.", "آپ کا مسئلہ حل ہو گیا ہے؛ صبر سے کام لینے کا شکریہ۔", "Aap ka masla hal ho gaya hai; sabr ka shukriya."),
        ("We value your continuous loyalty and patronship across the years.", "برسوں سے ہمارے ساتھ جڑے رہنے پر ہم آپ کے شکر گزار ہیں۔", "Saalon se sath jurray rehnay par hum aap ke shukr-guzar hain."),
        ("Customer service is an attitude of heartfelt hospitality and care.", "کسٹمر کی خدمت دراصل دل سے کی جانے والی مہمان نوازی ہے۔", "Customer service dar-asal dil se ki jaanay wali khidmat hai."),
        ("Always follow through on the promises made during support calls.", "کال کے دوران کیے گئے تمام وعدوں کو لازمی پورا کریں۔", "Call ke dauran kiye gaye tamam wadon ko poora karein."),
        ("We have credited promotional reward points to your app wallet.", "ہم نے آپ کے والٹ میں اضافی انعامی پوائنٹس ڈال دیے ہیں۔", "Hum ne aap ke wallet mein reward points daal diye hain."),
        ("Keep your voice calm, reassuring, and professional at all times.", "اپنی آواز کو ہمیشہ پرسکون، تسلی بخش اور باوقار رکھیں۔", "Apni aawaz ko hamesha pursukoon aur shaista rakhein."),
        ("Empathetic customer service creates lifelong human connections.", "ہمدردانہ رویہ گاہکوں کے ساتھ زندگی بھر کے رشتے بناتا ہے۔", "Hamdardana rawaiya lifelong connections banata hai."),
        ("Thank you for choosing our services; have a magnificent day!", "ہماری سروس کا انتخاب کرنے کا شکریہ؛ آپ کا دن خوشگوار گزرے!", "Hamari service chun-nay ka shukriya; aap ka din acha guzray!"),
        ("How can I update my billing address on the customer portal?", "میں کسٹمر پورٹل پر اپنا بلنگ کا پتہ کیسے تبدیل کروں؟", "Mein portal par apna billing address kaisay badloon?"),
        ("Log into your user account, click profile, and edit billing address.", "اپنے اکاؤنٹ میں جائیں، پروفائل پر کلک کریں اور پتہ درست کریں۔", "Account mein jayein, profile par jayein aur pata badlein."),
        ("Our live chat agent will join this conversation in ten seconds.", "ہمارا نمائندہ دس سیکنڈ میں آپ کے ساتھ بات شروع کرے گا۔", "Hamara numainda 10 second mein chat par aaye ga."),
        ("We are dedicated to providing seamless, five-star experiences.", "ہم آپ کو بہترین اور فائیو اسٹار سروس دینے کے لیے کوشاں ہیں۔", "Hum aap ko 5-star service denay ke liye koshish kar rahe hain."),
        ("If you need further help, feel free to reopen this support ticket.", "مزید مدد درکار ہو تو آپ اس شکایت کو دوبارہ کھول سکتے ہیں۔", "Mazeed madad chahiye ho to ticket dobara open kar saktay hain."),
        ("Honesty and speed are the hallmarks of great customer care.", "سچائی اور تیزی بہترین کسٹمر سروس کی اصل پہچان ہیں۔", "Sachai aur taizi achi customer service ki pehchan hain."),
        ("We have waived the late payment fee as a courtesy gesture.", "ہم نے خیر سگالی کے طور پر لیٹ فیس معاف کر دی ہے۔", "Hum ne khair-sugali ke tor par late fee maaf kar di hai."),
        ("Customer feedback is the gold standard that guides our innovations.", "گاہکوں کی رائے ہی ہماری نئی ایجادات کا راستہ بناتی ہے۔", "Gahakon ki raye hamari behtari ka rasta banati hai."),
        ("Thank you for bringing this software bug to our engineering notice.", "سافٹ ویئر کی اس خرابی کی نشاندہی کرنے کا بے حد شکریہ۔", "Software bug ki nishan-dahi karne ka bohat shukriya."),
        ("Every single customer interaction is an opportunity to shine.", "ہر کسٹمر سے بات کرنا ادارے کے وقار کو چمکانے کا موقع ہے۔", "Har customer se baat idaray ki izzat barhanay ka mauqa hai."),
        ("We offer multilingual customer support in Urdu and English.", "ہم اردو اور انگریزی دونوں زبانوں میں رہنمائی فراہم کرتے ہیں۔", "Hum Urdu aur English dono mein customer support detay hain."),
        ("Your issue has been marked as high priority in our queue.", "آپ کے مسئلے کو ہماری فہرست میں اولین ترجیح دی گئی ہے۔", "Aap ke maslay ko high priority di gayi hai."),
        ("We are always here to listen, understand, and assist with joy.", "ہم ہمیشہ سننے، سمجھنے اور خوشی سے مدد کے لیے حاضر ہیں۔", "Hum hamesha sunnay aur madad ke liye hazir hain."),
        ("A friendly tone turns everyday customer queries into pleasant chats.", "شائستہ لہجہ عام بات چیت کو بھی خوشگوار بنا دیتا ہے۔", "Shaista lehja baat cheet ko khushgawar banata hai."),
        ("Thank you for your exceptional patience during this server outage.", "سرور کی خرابی کے دوران آپ کے تعاون اور صبر کا شکریہ۔", "Server kharab honay par aap ke ta'awun ka shukriya."),
        ("We take full accountability for this delivery mistake and apologize.", "ہم اس غلطی کی مکمل ذمہ داری لیتے ہیں اور معافی چاہتے ہیں۔", "Hum is ghalti ki zimmedari letay hain aur maazrat chahtay hain."),
        ("Our goal is to turn customer difficulties into memorable delights.", "ہمارا مقصد آپ کی ہر مشکل کو آسان اور خوشگوار بنانا ہے۔", "Hamara maqsad aap ki mushkil ko aasan banana hai."),
        ("May your experience with us always remain delightful and smooth!", "اللہ کرے ہمارے ساتھ آپ کا تجربہ ہمیشہ شاندار اور خوشگوار رہے!", "Allah karay hamare sath aap ka tajruba hamesha acha rahay!"),
        ("Thank you for being our valued partner; we cherish your trust!", "ہمارا معزز کسٹمر بننے کا شکریہ؛ ہم آپ کے اعتماد کی قدر کرتے ہیں!", "Hamara customer ban-nay ka shukriya; hum qadr kartay hain!"),
        ("Wishing you unparalleled happiness, success, and prosperity always!", "اللہ تعالیٰ آپ کو ہمیشہ غیر معمولی خوشیاں، کامیابی اور سکون دے!", "Allah Ta'ala aap ko hamesha khushiyan aur barkat ata farmaye!")
    ]

    # 49. Science & Modern Innovations
    t49 = [
        ("Scientific curiosity and research drive the advancement of civilization.", "سائنسی جستجو اور تحقیق انسانی تہذیب کی ترقی کی بنیاد ہیں۔", "Sciensi justuju aur tehqeeq insani tehzeeb ki bunyad hain."),
        ("Artificial intelligence algorithms analyze complex medical imaging scans.", "مصنوعی ذہانت کے الگورتھم پیچیدہ میڈیکل اسکینز کا تجزیہ کرتے ہیں۔", "AI algorithms paicheeda medical scans ka jaiza letay hain."),
        ("James Webb space telescope captures breathtaking galaxies billions of years old.", "جیمز ویب دوربین اربوں سال پرانی کہکشاؤں کی تصاویر دکھاتی ہے۔", "James Webb telescope arbon saal purani galaxies dikhati hai."),
        ("Renewable solar panels convert sunlight directly into clean electricity.", "سولر پینلز سورج کی روشنی کو براہ راست بجلی میں بدلتے ہیں۔", "Solar panels sooraj ki roshni ko bijli mein badaltay hain."),
        ("CRISPR gene editing technology promises cures for inherited genetic diseases.", "جین ایڈیٹنگ ٹیکنالوجی موروثی بیماریوں کے علاج میں انقلاب لا رہی ہے۔", "Gene editing technology beemariyon ke ilaaj mein inqilaab la rahi hai."),
        ("Quantum computing will solve complex calculations in fractions of seconds.", "کوانٹم کمپیوٹر سیکنڈ کے ہزارویں حصے میں بڑی گنتی حل کر لے گا۔", "Quantum computer taizi se hisab kitab hal karay ga."),
        ("Electric vehicles reduce urban carbon emissions and noise pollution.", "الیکٹرک گاڑیاں دھوئیں اور شور کی آلودگی کو ختم کرتی ہیں۔", "Electric gaariyan dhuwan aur shor khatam karti hain."),
        ("Robotic surgery enables surgeons to perform micro-procedures with precision.", "روبوٹک سرجری ڈاکٹروں کو انتہائی باریک آپریشنز میں مدد دیتی ہے۔", "Robotic surgery doctors ko bariki se operations karne deti hai."),
        ("Desalination plants transform salty ocean seawater into drinkable water.", "ڈی سیلینیشن پلانٹس سمندر کے کھارے پانی کو میٹھا بناتے ہیں۔", "Desalination plants kharay paani ko meetha banatay hain."),
        ("Science reveals the magnificent order and mathematical beauty of cosmos.", "سائنس کائنات کے شاندار نظم و ضبط اور خوبصورتی کو ظاہر کرتی ہے۔", "Science kainaat ke nazm-o-zabt aur husn ko kholti hai."),
        ("How does nuclear fusion generate clean, limitless energy like the sun?", "نیوکلیئر فیوژن سورج کی طرح لامحدود اور صاف توانائی کیسے بناتا ہے؟", "Nuclear fusion sooraj ki tarah limitless energy kaisay banata hai?"),
        ("Nanotechnology manipulates matter at the individual atomic scale.", "نینو ٹیکنالوجی ایٹم کے لیول پر مادے کی ساخت کو تبدیل کرتی ہے۔", "Nanotechnology atoms ke level par kaam karti hai."),
        ("3D bioprinting aims to fabricate living human tissues and transplant organs.", "تھری ڈی بائیو پرنٹنگ سے انسانی اعضاء تیار کرنے پر کام جاری ہے۔", "3D bioprinting se insani a'aza bananay par kaam jari hai."),
        ("Autonomous self-driving drones deliver emergency medical supplies swiftly.", "خودکار ڈرونز ایمرجنسی میں ادویات اور خون تیزی سے پہنچاتے ہیں۔", "Drones emergency mein adwiyaat taizi se pohanchatay hain."),
        ("Graphene is a single layer of carbon atoms stronger than diamond.", "گرافین ہیرے سے زیادہ مضبوط کاربن ایٹموں کی باریک تہہ ہے۔", "Graphene heeray se zyada mazboot carbon layer hai."),
        ("Space exploration expands human knowledge and secures planetary future.", "خلائی تحقیق انسانی علم کو وسعت اور مستقبل کو محفوظ بناتی ہے۔", "Space research insani ilm ko wasee banati hai."),
        ("Biotechnology engineers drought-resistant agricultural crop varieties.", "بائیو ٹیکنالوجی خشک سالی کا مقابلہ کرنے والی فصلیں بناتی ہے۔", "Biotechnology aisi faslein banati hai jo sookhay mein ug sakein."),
        ("Brain-computer interfaces restore mobility to paralyzed individuals.", "دماغی کمپیوٹر انٹرفیس فالج کے مریضوں کو حرکت میں مدد دیتا ہے۔", "Brain interfaces mareezon ko harkat mein madad detay hain."),
        ("Synthetic biology designs microbes that digest industrial plastic waste.", "سائنسدان پلاسٹک کا کچرا کھانے والے جراثیم تیار کر رہے ہیں۔", "Microbes plastic ka kachra khatam karne ke liye banaye ja rahe hain."),
        ("The universe is expanding at an accelerated rate driven by dark energy.", "ڈارک انرجی کی وجہ سے کائنات تیزی سے پھیل رہی ہے۔", "Dark energy ki wajah se kainaat phail rahi hai."),
        ("Vertical indoor aeroponic farming uses ninety-five percent less water.", "عمودی بند فارمنگ پچانوے فیصد کم پانی میں فصلیں اگاتی ہے۔", "Vertical farming 95% kam paani mein faslein ugati hai."),
        ("Solid-state batteries charge vehicles in minutes and prevent fire hazards.", "جدید سالڈ اسٹیٹ بیٹریاں گاڑیوں کو چند منٹ میں چارج کرتی ہیں۔", "Solid state batteries gaariyon ko taizi se charge karti hain."),
        ("Machine learning models predict weather patterns with high precision.", "مشین لرننگ ماڈلز موسم کی درست پیش گوئی کرتے ہیں۔", "Machine learning mausam ki sahi paish-goi karti hai."),
        ("Human curiosity to explore the unknown is our greatest superpower.", "نامعلوم کو جاننے کا انسانی تجسس ہماری سب سے بڑی طاقت ہے۔", "Na-maloom ko jaannay ka tajassus insani taaqat hai."),
        ("Gravitational waves confirm Einstein's general theory of relativity.", "کشش ثقل کی لہریں آئنسٹائن کے نظریے کی تصدیق کرتی ہیں۔", "Gravitational waves Einstein ke nazriye ko sabit karti hain."),
        ("Biodegradable mushroom mycelium packaging replaces toxic Styrofoam.", "کھمبی سے بنے پیکٹس زہریلے تھرموپول کا ماحول دوست متبادل ہیں۔", "Mushroom packaging plastic ka behtareen mutabadil hai."),
        ("Wireless power transmission will charge devices across rooms without cords.", "بغیر تاروں کے ہوا کے ذریعے برقی توانائی منتقل کرنے پر کام جاری ہے۔", "Baghair taron ke bijli muntaqil karne par kaam jari hai."),
        ("Gene therapy cures rare childhood blindness disorders permanently.", "جین تھراپی بچوں کے پیدائشی اندھے پن کا مستقل علاج کرتی ہے۔", "Gene therapy bachon ki beenai theek karti hai."),
        ("Atmospheric water generators harvest fresh drinking water from humid air.", "ہوا سے پینے کا صاف پانی بنانے والی مشینیں ایجاد ہو چکی ہیں۔", "Hawa se paani bananay wali machines ban chuki hain."),
        ("Science and ethical responsibility must walk hand in hand.", "سائنس اور اخلاقی ذمہ داری کو ہمیشہ ساتھ ساتھ چلنا چاہیے۔", "Science aur ikhlaaqi zimmedari ko sath chalna chahiye."),
        ("Mars rover roams the red planet searching for ancient microbial life.", "مریخ پر بھیجی گئی گاڑی قدیم زندگی کے آثار تلاش کر رہی ہے۔", "Mars rover qadeem zindagi ke aasaar dhoond raha hai."),
        ("Superconducting materials transmit electricity with zero resistance.", "سپر کنڈکٹرز بجلی کو بغیر کسی نقصان کے منتقل کرتے ہیں۔", "Superconductors bijli ko baghair nuqsan muntaqil kartay hain."),
        ("mRNA vaccine platforms revolutionize rapid viral immunization.", "ایم آر این اے ٹیکنالوجی ویکسینز کو تیزی سے تیار کرنے میں مدد دیتی ہے۔", "mRNA technology taizi se vaccines banati hai."),
        ("Carbon capture technology filters greenhouse gases from industrial smokestacks.", "کاربن کیپچر ٹیکنالوجی کارخانوں کے دھوئیں سے گیسیں جذب کرتی ہے۔", "Carbon capture factories ke dhuwayen ko saaf karti hai."),
        ("Smart robotic prosthetics respond directly to human nerve signals.", "جدید مصنوعی اعضاء انسانی اعصاب کے اشاروں پر کام کرتے ہیں۔", "Artificial limbs dimagh ke signals par kaam kartay hain."),
        ("Telescopes search for Earth-like habitable exoplanets orbiting distant stars.", "دوربینیں دور دراز ستاروں کے گرد زمین جیسے سیارے تلاش کر رہی ہیں۔", "Telescopes zameen jaisay planets dhoond rahi hain."),
        ("Tidal underwater turbines generate clean energy from ocean currents.", "سمندر کی لہروں کی طاقت سے صاف بجلی پیدا کی جا رہی ہے۔", "Samandar ki lehron se saaf bijli banayi ja rahi hai."),
        ("Liquid metal cooling keeps next-generation microprocessors ice cold.", "لیکوڈ کولنگ جدید کمپیوٹر چپس کو ٹھنڈا اور تیز رکھتی ہے۔", "Liquid cooling computer chips ko thanda rakhti hai."),
        ("Biomimicry creates high-efficiency aircraft inspired by bird wings.", "پرندوں کے پروں کی نقل کر کے انتہائی تیز طیارے بنائے جا رہے ہیں۔", "Parindon se seekh kar taiz hawai jahaz banaye ja rahe hain."),
        ("Knowledge is a radiant torch that dispels darkness of ignorance.", "علم ایک روشن مشعل ہے جو جہالت کے اندھیروں کو مٹاتی ہے۔", "Ilm aik roshan mash'al hai jo andheron ko mitati hai."),
        ("Microscopic nanobots will deliver chemotherapy directly to cancer cells.", "ننھے روبوٹس کینسر کے خلیات تک براہ راست دوا پہنچائیں گے۔", "Microscopic robots cancer cells tak dawa pohanchayein ge."),
        ("Hydrogen fuel cell buses emit nothing but pure drinkable water vapor.", "ہائیڈروجن فیول بسیں دھوئیں کے بجائے صرف پانی کا بخار چھوڑتی ہیں۔", "Hydrogen buses sirf paani ka steam nikaalti hain."),
        ("Augmented reality smart glasses overlay rich digital info onto reality.", "اسمارٹ چشمے حقیقی دنیا پر ڈیجیٹل معلومات دکھاتے ہیں۔", "Smart glasses haqeeqi dunya par data dikhati hain."),
        ("Deep sea submersibles explore the deepest oceanic trenches on Earth.", "گہرے سمندر کی آبدوزیں زیرِ آب نایاب حیات کی کھوج لگاتی ہیں۔", "Submarines samandar ki gehraiyon ki tehqeeq karti hain."),
        ("Solar powered desalination provides freshwater to arid desert regions.", "شمسی توانائی سے صحرائی علاقوں میں میٹھا پانی فراہم کیا جا رہا ہے۔", "Solar energy se sehrai ilaaqon mein paani diya ja raha hai."),
        ("Science teaches us wonder, humility, curiosity, and relentless learning.", "سائنس ہمیں حیرت، عاجزی اور مسلسل سیکھنے کا جذبہ سکھاتی ہے۔", "Science humein aajzi aur seekhnay ka jazba sikhati hai."),
        ("Invest in science education to empower the next generation of pioneers.", "نئی نسل کو سائنس اور ٹیکنالوجی کی تعلیم سے آراستہ کریں۔", "Nayi nasal ko science aur technology ki taleem dein."),
        ("Humanity's potential for innovation and discovery is boundless.", "انسان کی نئی ایجادات اور دریافتوں کی صلاحیت لاحصار ہے۔", "Insaan ki daryafton ki salahiyat be-misal hai."),
        ("May scientific discoveries always be utilized for human peace and healing!", "اللہ کرے تمام سائنسی دریافتیں انسانیت کے امن اور بھلائی کے لیے کام آئیں!", "Allah karay tamam sciensi daryaftein aman ke liye kaam aayein!"),
        ("Wishing you an enlightened, curious, and visionary scientific mind!", "اللہ تعالیٰ آپ کے ذہن کو علم، حکمت اور بصیرت سے منور رکھے!", "Allah Ta'ala aap ke zehan ko ilm aur baseerat se munawwar rakhay!")
    ]

    # 50. Daily Life & Moral Values
    t50 = [
        ("Honesty, integrity, and truthfulness are the crown jewels of character.", "سچائی، دیانت اور ایمانداری انسان کے کردار کا سب سے قیمتی زیور ہیں۔", "Sachai, dyanat aur imaandari kirdaar ka zewar hain."),
        ("Kindness shown to an innocent animal reflects purity of heart.", "بے زبان جانوروں کے ساتھ شفقت دل کی پاکیزگی کی علامت ہے۔", "Be-zaban janwaron par shafqat dil ki pakeezgi hai."),
        ("A gentle word and pleasant smile are acts of continuous charity.", "میٹھی گفتگو اور مسکراتا چہرہ مسلسل صدقہ اور خیر ہیں۔", "Meethi baat aur muskurahat musalsal sadqa hain."),
        ("Always fulfill promises and commitments you make to others faithfully.", "دوسروں سے کیے گئے تمام وعدوں اور عہد کو ہمیشہ وفا کریں۔", "Doosron se kiye gaye wadon ko hamesha wafa karein."),
        ("Humility elevates human dignity, while arrogance destroys the soul.", "عاجزی انسان کو بلندی دیتی ہے، جبکہ غرور تباہ کر دیتا ہے۔", "Aajzi insaan ko bulandi deti hai, ghuroor tabah karta hai."),
        ("Help neighbors and community members in times of hardship silently.", "مشکل کے وقت پڑوسیوں اور مستحقین کی خاموشی سے مدد کریں۔", "Mushkil ke waqt parosiyon ki khamoshi se madad karein."),
        ("Forgiving those who hurt you liberates your own heart from bitterness.", "تکلیف دینے والوں کو معاف کر دینا دل کو نفرت سے آزاد کرتا ہے۔", "Takleef denay walon ko maaf karna dil ko azaad karta hai."),
        ("Patience (Sabr) through trials turns bitter suffering into radiant gold.", "آزمائشوں پر صبر کرنا دکھ کو کندن اور نیکی میں بدل دیتا ہے۔", "Aazmaishon par sabr karna dukh ko bhalai mein badalta hai."),
        ("Cleanliness in personal hygiene and surroundings is half of faith.", "اپنے جسم اور ماحول کی صفائی نصف ایمان کا درجہ رکھتی ہے۔", "Apne jism aur mahaul ki safaai nisf imaan hai."),
        ("Live with purpose, serve humanity, and leave a legacy of blessings.", "بامقصد زندگی گزاریں، انسانیت کی خدمت کریں اور اچھی یادیں چھوڑ جائیں۔", "Ba-maqsad zindagi guzarein aur khidmat karein."),
        ("How do we cultivate moral resilience in our daily family lives?", "ہم اپنی روزمرہ خاندانی زندگی میں اخلاقی اقدار کیسے پیدا کریں؟", "Hum rozmarrah zindagi mein ikhlaaqi aqdaar kaisay banayein?"),
        ("Practice self-accountability before judging or blaming others.", "دوسروں پر تنقید کرنے سے پہلے اپنا محاسبہ کرنے کی عادت ڈالیں۔", "Doosron par tanqeed se pehle apna jaiza lein."),
        ("Gratitude turns ordinary daily meals into rich joyous feasts.", "شکر گزاری سادہ کھانے کو بھی پرمسرت ضیافت بنا دیتی ہے۔", "Shukr-guzari saada khanay ko nemat bana deti hai."),
        ("Never engage in backbiting, gossip, or character assassination.", "غیبت، چغلی اور کسی کی عزت اچھالنے سے ہمیشہ بچیں۔", "Gheebat, chughli aur bohtaan se hamesha bachein."),
        ("Speak truth even when it feels inconvenient or personally difficult.", "سچی بات کہیں چاہے وہ آپ کے اپنے لیے کڑوی ہی کیوں نہ ہو۔", "Sachi baat kahein chahay woh karwi hi kyun na ho."),
        ("Respect the dignity of hard labor, whether a sweeper or executive.", "محنت کش کی عزت کریں چاہے وہ جھاڑو دینے والا ہو یا افسر۔", "Mehnat-kash ki izzat karein chahay koi bhi ho."),
        ("Feed the hungry, comfort the orphan, and shelter the destitute.", "بھوکوں کو کھانا کھلائیں، یتیموں کا سہارا بنیں اور بے سہاروں کو پناہ دیں۔", "Bhookon ko khana khilayein aur yateemon ka sahara banein."),
        ("A good deed done in secret shines brighter than worldly gold.", "تنہائی میں کی گئی خاموش نیکی دنیا کی تمام دولت سے افضل ہے۔", "Tanhai mein ki gayi naiki dunya ki daulat se behtar hai."),
        ("Guard your tongue; words can either heal hearts or break souls.", "اپنی زبان کی حفاظت کریں؛ الفاظ دل جوڑتے بھی ہیں اور توڑتے بھی۔", "Apni zaban ki hifazat karein; alfaaz dil tortay bhi hain."),
        ("Peace of conscience is the sweetest pillow to sleep upon at night.", "مطمئن ضمیر رات کو سونے کے لیے دنیا کا سب سے پرسکون تکیہ ہے۔", "Mutmain zameer sonay ke liye sab se pursukoon takiya hai."),
        ("Show utmost respect to teachers and mentors who guide your mind.", "اپنے اساتذہ اور رہنمائی کرنے والوں کا دل سے ادب و احترام کریں۔", "Apne asatiza aur ustaadon ka adab karein."),
        ("Be content with what you have while striving honorably for better.", "جو میسر ہے اس پر راضی رہیں اور حلال طریقے سے بہتری کی کوشش کریں۔", "Jo mayassar hai us par raazi rahein aur halal koshish karein."),
        ("Greed is a bottomless well that never fills; contentment is wealth.", "لالچ ایک ایسا کنواں ہے جو کبھی نہیں بھرتا؛ قناعت ہی اصل دولت ہے۔", "Laalach kabhi nahi bharta; qana'at hi asal daulat hai."),
        ("Stand firmly with the oppressed against injustice everywhere.", "ہر جگہ ظلم کے خلاف اور مظلوم کے حق میں ڈٹ کر کھڑے ہوں۔", "Zulm ke khilaf aur mazloom ke haq mein kharray hon."),
        ("Kindness is a universal language that the deaf hear and blind see.", "شفقت وہ زبان ہے جو بہرے بھی سنتے ہیں اور اندھے بھی دیکھتے ہیں۔", "Shafqat aisi zaban hai jo sab samajhtay hain."),
        ("Treat your guests with generous hospitality, warmth, and joy.", "مہمانوں کی خدمت کھلے دل، مسکراہٹ اور خلوص کے ساتھ کریں۔", "Mehmanon ki khidmat khulay dil aur muskurahat se karein."),
        ("Keep your heart free from poisonous jealousy, envy, and malice.", "اپنے دل کو حسد، بغض اور کینے کے زہر سے ہمیشہ پاک رکھیں۔", "Apne dil ko hasad aur keena se paak rakhein."),
        ("Small consistent acts of charity avert difficulties and trials.", "روزانہ کا چھوٹا سا صدقہ بھی بڑی مصیبتوں کو ٹال دیتا ہے۔", "Rozana ka sadqa barri museebaton ko taalta hai."),
        ("A noble character leaves a fragrant memory that never fades.", "اعلیٰ کردار ایسی خوشبو چھوڑتا ہے جو کبھی ماند نہیں پڑتی۔", "Aala kirdaar aisi khushboo chhorta hai jo rehti hai."),
        ("Life is a brief journey; make every step count for goodness.", "زندگی ایک مختصر سفر ہے؛ ہر قدم نیکی اور بھلائی کے لیے اٹھائیں۔", "Zindagi mukhtasir safar hai; naiki ka rasta apnayein."),
        ("Give priority to resolving broken ties with estranged friends.", "ناراض دوستوں اور رشتے داروں سے صلح کرنے میں پہل کریں۔", "Naraaz doston se sulah karne mein pehal karein."),
        ("Honest earnings bring enduring tranquility and barakah to home.", "حلال کمائی گھر میں دائمی سکون اور برکت لے کر آتی ہے۔", "Halaal kamai ghar mein sukoon aur barkat laati hai."),
        ("Never look down upon anyone; circumstances can shift in an instant.", "کسی کو حقیر نہ سمجھیں؛ حالات بدلتے دیر نہیں لگتی۔", "Kisi ko haqeer na samjhein; halaat badal saktay hain."),
        ("Be a beacon of hope and encouragement to someone in despair.", "مایوس انسان کے لیے امید اور حوصلے کی کرن بنیں۔", "Mayoos insaan ke liye umeed aur hauslay ki kiran banein."),
        ("Protect the trust (Amanah) placed in you with utmost loyalty.", "آپ کو دی گئی امانت کی حفاظت پوری دیانت داری سے کریں۔", "Amanat ki hifazat poori dyanat-dari se karein."),
        ("A calm temper diffuses anger before it ignites destruction.", "ٹھنڈا مزاج غصے کی آگ کو بھڑکنے سے پہلے بجھا دیتا ہے۔", "Thanda mizaj ghussay ki aag ko bujha deta hai."),
        ("Teach children that true nobility lies in moral virtue, not status.", "بچوں کو سکھائیں کہ اصل بڑائی عہدے میں نہیں بلکہ اچھے اخلاق میں ہے۔", "Bachon ko sikhayein ke asal barrai ikhlaaq mein hai."),
        ("Every morning is a divine opportunity to begin anew with purity.", "ہر نئی صبح نیکی کی طرف لوٹنے اور نیا آغاز کرنے کا موقع ہے۔", "Har nayi subah naiki ka naya aaghaz karne ka mauqa hai."),
        ("Spread greeting of Salam (peace) to those you know and know not.", "سلامتی اور امن کا پیغام ہر جانے اور انجانے شخص کو دیں۔", "Salamti aur aman ka paigham sab ko dein."),
        ("Cultivate empathy: feel the unspoken sorrow in other people's eyes.", "دوسروں کے چہروں پر پوشیدہ دکھ کو محسوس کرنا سیکھیں۔", "Doosron ke chehron par dukh ko mehsoos karein."),
        ("Praise the creator for all countless blessings we take for granted.", "ہر اس نعمت پر خالق کا شکر کریں جس کے ہم عادی ہو چکے ہیں۔", "Har nemat par Khaliq ka shukr ada karein."),
        ("Live lightly on Earth, tread gently, and speak lovingly to all.", "زمین پر عاجزی سے چلیں اور ہر ایک سے پیار سے بات کریں۔", "Zameen par aajzi se chalein aur pyar se baat karein."),
        ("The best amongst people is the one who benefits humanity most.", "لوگوں میں سب سے بہترین وہ ہے جو انسانیت کو سب سے زیادہ نفع دے۔", "Logon mein behtareen woh hai jo sab ko faida de."),
        ("A sincere heart is the most precious sanctuary in existence.", "ایک مخلص اور صاف دل دنیا کی سب سے خوبصورت پناہ گاہ ہے۔", "Aik mukhlis aur saaf dil sab se khubsurat hai."),
        ("Patience and prayers are your strongest companions through trials.", "صبر اور دعا آزمائش کے وقت آپ کے سب سے مضبوط ساتھی ہیں۔", "Sabr aur dua aazmaish mein sab se barray saathi hain."),
        ("Fill your days with deeds that will bring peace at twilight of life.", "اپنی زندگی کو ایسے کاموں سے سجائیں جو آخری وقت سکون دیں۔", "Apni zindagi ko aisi naiki se sajayein jo sukoon de."),
        ("May your moral character shine as an inspiring beacon for all!", "اللہ کرے آپ کا کردار دوسروں کے لیے مشعلِ راہ بن جائے!", "Allah karay aap ka kirdaar doosron ke liye misaal banay!"),
        ("Thank you for walking the noble path of truth, mercy, and compassion.", "سچائی، رحمت اور محبت کا راستہ اپنانے پر آپ کو سلام۔", "Sachai aur mohabbat ka rasta apnanay par aap ko salam."),
        ("May divine grace encompass you, your loved ones, and all creation!", "اللہ تعالیٰ کا فضل اور رحمت آپ پر اور آپ کے پیاروں پر ہمیشہ سایہ فگن رہے!", "Allah Ta'ala ka fazl aur rehmat aap par hamesha rahay!"),
        ("May peace, barakah, love, and light abide with you forever!", "اللہ کرے امن، برکت، محبت اور نور ہمیشہ آپ کے ساتھ رہے!", "Allah karay aman, barkat aur noor hamesha aap ke sath rahay!")
    ]

    return [
        {"id": 46, "name": "Driving & Road Safety", "urduName": "ڈرائیونگ اور ٹریفک قوانین", "icon": "directions_car", "desc": "Signals, speed limits, parking, vehicle maintenance, and highway safety.", "sentences": t46},
        {"id": 47, "name": "Job Interviews & Career Growth", "urduName": "ملازمت کے انٹرویوز اور ترقی", "icon": "work", "desc": "Strengths, salary negotiation, leadership, career paths, and poise.", "sentences": t47},
        {"id": 48, "name": "Customer Service & Client Care", "urduName": "گاہکوں کی خدمت اور رہنمائی", "icon": "support_agent", "desc": "Assistance, refunds, empathy, issue resolution, and polite care.", "sentences": t48},
        {"id": 49, "name": "Science & Modern Innovations", "urduName": "سائنس اور جدید ایجادات", "icon": "science", "desc": "AI, space, genomics, renewable energy, and scientific discoveries.", "sentences": t49},
        {"id": 50, "name": "Daily Life & Moral Values", "urduName": "روزمرہ زندگی اور اخلاقی اقدار", "icon": "volunteer_activism", "desc": "Honesty, empathy, charity, patience, humility, and purpose.", "sentences": t50}
    ]
