# -*- coding: utf-8 -*-

def get_31_to_35():
    # 31. At the Pharmacy & Medicine
    t31 = [
        ("Good morning, I need to get this doctor's prescription filled.", "صبح بخیر، مجھے ڈاکٹر کا یہ نسخہ دیکھ کر دوائی لینی ہے۔", "Subah bakhair, mujhe doctor ka yeh nuskha dekh kar dawai leni hai."),
        ("What is the exact dosage and timing for this antibiotic syrup?", "اس اینٹی بائیوٹک شربت کی صحیح مقدار اور وقت کیا ہے؟", "Is antibiotic sharbat ki sahi miqdaar aur waqt kya hai?"),
        ("Take one tablet twice a day strictly after your meals.", "کھانے کے بعد دن میں دو بار سختی کے ساتھ ایک ایک گولی لیں۔", "Khanay ke baad din mein do baar sakhti ke sath aik aik goli lein."),
        ("Are there any potential drowsy side effects with this antihistamine?", "کیا اس الرجی کی دوا سے غنودگی یا سستی ہو سکتی ہے؟", "Kya is allergy ki dawa se ghanoodgi ya susti ho sakti hai?"),
        ("Do you have sterile adhesive bandages and antiseptic wound cream?", "کیا آپ کے پاس جراثیم سے پاک پٹیاں اور مرہم موجود ہے؟", "Kya aap ke paas jaraseem se paak pattiyan aur marham maujood hai?"),
        ("Please check the expiry date printed on the back of the blister pack.", "دوا کے پیکٹ کے پیچھے لکھی ہوئی ایکسپائری تاریخ ضرور چیک کریں۔", "Dawa ke packet ke peechay likhi expiry tareekh zaroor check karein."),
        ("I need a reliable digital thermometer to measure body temperature.", "مجھے بخار ناپنے کے لیے ایک معیاری ڈیجیٹل تھرمامیٹر چاہیے۔", "Mujhe bukhar naapnay ke liye aik meyaari digital thermometer chahiye."),
        ("Store these insulin vials inside the refrigerator between two and eight degrees.", "اس انسولین کو فریج میں دو سے آٹھ ڈگری پر محفوظ رکھیں۔", "Is insulin ko fridge mein 2 se 8 degree par mahfooz rakhein."),
        ("Do you have over-the-counter pain relief tablets for headaches?", "کیا سر درد کے لیے بغیر نسخے کے ملنے والی درد کش گولیاں ہیں؟", "Kya sar dard ke liye baghair nuskhe ke dard-kush goliyan hain?"),
        ("Always complete the full prescribed course of your antibiotics.", "اپنی اینٹی بائیوٹک ادویات کا کورس ہمیشہ پورا کریں۔", "Apni antibiotic adwiyaat ka course hamesha poora karein."),
        ("Do you sell daily multivitamin and calcium supplements?", "کیا آپ کے پاس روزانہ کھانے والی وٹامن اور کیلشیم کی گولیاں ہیں؟", "Kya aap ke paas rozana khanay wali vitamin aur calcium ki goliyan hain?"),
        ("Can I get an oral rehydration salts (ORS) packet for dehydration?", "کیا ڈی ہائیڈریشن کے لیے او آر ایس کا پیکٹ مل سکتا ہے؟", "Kya dehydration ke liye ORS ka packet mil sakta hai?"),
        ("Dissolve this effervescent Vitamin C tablet in a glass of water.", "اس وٹامن سی کی گولی کو ایک گلاس پانی میں حل کر کے پئیں۔", "Is Vitamin C ki goli ko aik glass paani mein hal kar ke piyein."),
        ("Do you have medicated throat lozenges for severe cough and soreness?", "کیا گلے کی سوزش اور شدید کھانسی کے لیے چوسنے والی گولیاں ہیں؟", "Kya galay ki sozish aur khansi ke liye choosnay wali goliyan hain?"),
        ("Please give me a small bottle of iodine antiseptic solution.", "مجھے پائیوڈین اینٹی سیپٹک محلول کی ایک چھوٹی بوتل دیں۔", "Mujhe Pyodine antiseptic solution ki aik chhoti botal dein."),
        ("Take this blood pressure medicine first thing in the morning.", "بلڈ پریشر کی یہ گولی صبح نہار منہ لینی ہے۔", "Blood pressure ki yeh goli subah nihaar munh leni hai."),
        ("Do you provide home delivery for monthly chronic prescriptions?", "کیا آپ ماہانہ ادویات کی ہوم ڈلیوری کی سہولت دیتے ہیں؟", "Kya aap maahana adwiyaat ki home delivery ki sahoolat detay hain?"),
        ("Is there an alternative generic brand available for this expensive pill?", "کیا اس مہنگی گولی کا کوئی متبادل سستا برانڈ دستیاب ہے؟", "Kya is mehngi goli ka koi mutabadil sasta brand dastiyab hai?"),
        ("Use this nasal spray twice daily to relieve sinus congestion.", "ناک کی بندش کھولنے کے لیے یہ اسپرے دن میں دو بار ڈالیں۔", "Naak ki bandish kholnay ke liye yeh spray din mein do baar daalein."),
        ("Keep all medications in a cool, dry place away from children.", "تمام ادویات ٹھنڈی اور خشک جگہ پر بچوں کی پہنچ سے دور رکھیں۔", "Tamam adwiyaat thandi aur khushk jagah par bachon se door rakhein."),
        ("Do you have a blood glucose monitoring meter with test strips?", "کیا شوگر چیک کرنے والا میٹر اور اس کی اسٹرپس دستیاب ہیں؟", "Kya sugar check karne wala meter aur us ki strips dastiyab hain?"),
        ("Apply this soothing ointment gently to the burn area three times.", "جلنے والی جگہ پر یہ مرہم دن میں تین بار احتیاط سے لگائیں۔", "Jalnay wali jagah par yeh marham din mein teen baar lagayein."),
        ("Do you sell medical face masks and disposable latex gloves?", "کیا آپ کے پاس سرجیکل ماسک اور ڈسپوزایبل دستانے ہیں؟", "Kya aap ke paas surgical mask aur disposable dastaanay hain?"),
        ("This medicine must be taken with a large glass of plain water.", "یہ دوا ایک بڑے گلاس تازہ پانی کے ساتھ نگلنی چاہیے۔", "Yeh dawa aik baray glass taaza paani ke sath nigalni chahiye."),
        ("Can I purchase an emergency asthma inhaler without a prescription?", "کیا مجھے ہنگامی دمے کا انہیلر بغیر نسخے کے مل سکتا ہے؟", "Kya mujhe hangami damay ka inhaler baghair nuskhe ke mil sakta hai?"),
        ("Never exceed the recommended daily maximum dosage limit.", "روزانہ دوا کی بتائی گئی زیادہ سے زیادہ حد سے کبھی تجاوز نہ کریں۔", "Rozana dawa ki batayi gayi hadd se kabhi tajawuz na karein."),
        ("Do you have soothing eye drops for dry and irritated eyes?", "کیا آنکھوں کی خشکی اور جلن دور کرنے والے ڈراپس موجود ہیں؟", "Kya aankhon ki khushki door karne walay drops maujood hain?"),
        ("This syrup is sugar-free and completely safe for diabetic patients.", "یہ شربت شوگر سے پاک ہے اور ذیابیطس کے مریضوں کے لیے محفوظ ہے۔", "Yeh sharbat sugar se paak hai aur diabetes ke mareezon ke liye mahfooz hai."),
        ("Could you please check my blood pressure on your monitor?", "کیا آپ برائے مہربانی اپنے مانیٹر پر میرا بلڈ پریشر چیک کر دیں گے؟", "Kya aap baraye meharbani mera blood pressure check kar dein ge?"),
        ("Always consult a qualified doctor before starting any new medication.", "کوئی بھی نئی دوا شروع کرنے سے پہلے مستند ڈاکٹر سے مشورہ کریں۔", "Koi bhi nayi dawa shuru karne se pehle mustanad doctor se mashwara karein."),
        ("Do you have elastic crepe bandages for ankle sprains?", "کیا پاؤں کی موچ کے لیے گرم اسٹریچ ایبل پٹی موجود ہے؟", "Kya paon ki moch ke liye garam stretchable patti maujood hai?"),
        ("Take this probiotic capsule to restore healthy gut bacteria.", "معدے کے اچھے بیکٹیریا کی بحالی کے لیے یہ پروبائیوٹک کیپسول لیں۔", "Maiday ke achay bacteria ke liye yeh probiotic capsule lein."),
        ("Does this medication interact negatively with grapefruit juice?", "کیا اس دوا کا چکوترا یا ترش جوس کے ساتھ کوئی برا ردعمل ہوتا ہے؟", "Kya is dawa ka grapefruit juice ke sath koi bura asar hota hai?"),
        ("Please provide a medicine organizer box with morning and night slots.", "صبح اور شام کے خانوں والا ادویات کا باکس عنایت کریں۔", "Subah aur shaam ke khanon wala adwiyaat ka box dein."),
        ("How long should I wait between applying these two eye drops?", "ان دو مختلف آئی ڈراپس کے درمیان کتنا وقفہ دینا چاہیے؟", "In do mukhtalif eye drops ke darmiyan kitna waqfa dena chahiye?"),
        ("Do you sell pediatric gripe water for colic pain in infants?", "کیا چھوٹے بچوں کے پیٹ درد کے لیے گرائپ واٹر موجود ہے؟", "Kya chhotay bachon ke pait dard ke liye gripe water hai?"),
        ("Shake the suspension liquid bottle thoroughly before every use.", "استعمال سے پہلے شربت کی شیشی کو اچھی طرح ہلائیں۔", "Istemal se pehle sharbat ki sheeshi ko achi tarah hilayein."),
        ("Is this topical pain relief spray suitable for backache?", "کیا کمر درد کے لیے یہ درد کش اسپرے موثر ہے؟", "Kya kamar dard ke liye yeh pain relief spray mo'assar hai?"),
        ("Do you have medicated shampoo for dandruff and itchy scalp?", "کیا سر کی خشکی اور خارش کے لیے میڈیکیٹڈ شیمپو دستیاب ہے؟", "Kya sar ki khushki ke liye medicated shampoo dastiyab hai?"),
        ("Never use medicines past their stamped expiration date.", "میعاد ختم ہونے کے بعد ادویات کا استعمال ہرگز نہ کریں۔", "Meyaad khatam honay ke baad adwiyaat ka istemal hargiz na karein."),
        ("Can you explain how to use this nebulizer machine at home?", "کیا آپ گھر پر نیبولائزر مشین کے استعمال کا طریقہ سمجھا سکتے ہیں؟", "Kya aap ghar par nebulizer machine ka tareeqa samjha saktay hain?"),
        ("Do you stock medical heating pads and ice packs for injuries?", "کیا چوٹ کے لیے گرم ٹکور کا پیڈ اور برف کا پیک دستیاب ہے؟", "Kya chot ke liye heating pad aur ice pack dastiyab hai?"),
        ("Please give me some cotton wool rolls and medical tape.", "مجھے میڈیکل ٹیپ اور روئی کا ایک رول دے دیں۔", "Mujhe medical tape aur rooi ka aik roll de dein."),
        ("This medicine may cause mild stomach upset if taken empty stomach.", "خالی پیٹ لینے پر یہ دوا معدے میں ہلکی جلن پیدا کر سکتی ہے۔", "Khaali pait lenay par yeh dawa maiday mein jalan paida kar sakti hai."),
        ("Is there a 24-hour emergency pharmacy branch nearby?", "کیا قریب میں کوئی چوبیس گھنٹے کھلی رہنے والی ایمرجنسی فارمیسی ہے؟", "Kya qareeb mein koi 24 ghantay khuli emergency pharmacy hai?"),
        ("Proper medical adherence ensures quick recovery and longevity.", "ادویات کی پابندی جلد صحت یابی اور لمبی عمر کی ضمانت ہے۔", "Adwiyaat ki pabandi jald sehat-yabi ki zamanat hai."),
        ("Do you have chewable antacid tablets for acute heartburn?", "کیا تیزابیت اور جلن کے لیے چبانے والی گولیاں دستیاب ہیں؟", "Kya tezaabiyat ke liye chabanay wali goliyan dastiyab hain?"),
        ("Always inform your pharmacist about any drug allergies you have.", "اپنی ادویاتی الرجی کے بارے میں فارماسسٹ کو ہمیشہ آگاہ کریں۔", "Apni dawa ki allergy ke baare mein pharmacist ko hamesha batayein."),
        ("Thank you for your detailed and professional guidance.", "آپ کی تفصیلی اور پیشہ ورانہ رہنمائی کا بے حد شکریہ۔", "Aap ki tafseeli aur paishawarana rehnumai ka bohat shukriya."),
        ("Wishing you complete health, vitality, and swift recovery!", "اللہ تعالیٰ آپ کو مکمل صحتِ کاملہ اور عاجلہ عطا فرمائے!", "Allah Ta'ala aap ko mukammal sehat-e-kaamila ata farmaye!")
    ]

    # 32. Banking & Finance
    t32 = [
        ("I would like to open a new personal savings bank account.", "میں ایک نیا ذاتی بچت (سیونگز) بینک اکاؤنٹ کھولنا چاہتا ہوں۔", "Mein aik naya zaati savings bank account kholna chahta hoon."),
        ("What documents are required for account opening verification?", "اکاؤنٹ کی تصدیق کے لیے کن دستاویزات کی ضرورت ہے؟", "Account ki tasdeeq ke liye kin dastawizaat ki zaroorat hai?"),
        ("You need your original CNIC and a verified proof of monthly income.", "آپ کو اپنا اصل شناختی کارڈ اور ماہانہ آمدنی کا ثبوت درکار ہوگا۔", "Aap ko apna asal shanakhti card aur aamadni ka saboot darkaar hoga."),
        ("What is the daily cash withdrawal limit on this debit card?", "اس ڈیبٹ کارڈ سے روزانہ رقم نکلوانے کی حد کیا ہے؟", "Is debit card se rozana raqam nikalwanay ki hadd kya hai?"),
        ("I would like to deposit this crossed pay order into my account.", "میں یہ کراس پے آرڈر اپنے اکاؤنٹ میں جمع کروانا چاہتا ہوں۔", "Mein yeh crossed pay order apne account mein jama karwana chahta hoon."),
        ("Could you please print my account bank statement for the last 6 months?", "کیا آپ گزشتہ چھ ماہ کا بینک اسٹیٹمنٹ پرنٹ کر سکتے ہیں؟", "Kya aap pichlay 6 maah ka bank statement print kar saktay hain?"),
        ("How do I activate internet banking and mobile banking app?", "میں انٹرنیٹ بینکنگ اور موبائل ایپ کیسے فعال کر سکتا ہوں؟", "Mein internet banking aur mobile app kaisay fa'al kar sakta hoon?"),
        ("The automated teller machine (ATM) retained my card by error.", "اے ٹی ایم مشین نے غلطی سے میرا کارڈ اندر روک لیا ہے۔", "ATM machine ne ghalti se mera card andar rok liya hai."),
        ("Please block my lost credit card immediately to prevent fraud.", "دھوکہ دہی سے بچنے کے لیے میرا گمشدہ کریڈٹ کارڈ فوری بلاک کریں۔", "Dhoka-dahi se bachnay ke liye mera card fauri block karein."),
        ("What is the annual percentage profit rate on term fixed deposits?", "میعادی فکسڈ ڈپازٹس پر سالانہ منافع کی شرح کیا ہے؟", "Meyaadi fixed deposits par salana munafay ki sharah kya hai?"),
        ("I need to transfer funds to an international overseas beneficiary.", "مجھے بیرون ملک ایک اکاؤنٹ میں رقم منتقل کرنی ہے۔", "Mujhe bairoon-e-mulk aik account mein raqam muntaqil karni hai."),
        ("Please provide the SWIFT code and IBAN number of this branch.", "براہ کرم اس برانچ کا سوئفٹ کوڈ اور آئی بین نمبر دیں۔", "Barah-e-karam is branch ka SWIFT code aur IBAN number dein."),
        ("Is there any maintenance fee for maintaining a zero balance?", "کیا زیرو بیلنس رکھنے پر کوئی ماہانہ کٹوتی یا فیس ہے؟", "Kya zero balance rakhnay par koi maahana fee hai?"),
        ("I would like to apply for a Shariah-compliant home finance loan.", "میں شریعت کے مطابق ہوم فنانس کے لیے درخواست دینا چاہتا ہوں۔", "Mein Shariat ke mutabiq home finance ke liye apply karna chahta hoon."),
        ("What is the processing turnaround time for a car auto loan?", "گاڑی کے آٹو لون کی منظوری میں کتنا وقت لگتا ہے؟", "Gaari ke auto loan ki manzoori mein kitna waqt lagta hai?"),
        ("Please update my registered mobile number for SMS transaction alerts.", "ایس ایم ایس الرٹس کے لیے میرا نیا موبائل نمبر رجسٹر کریں۔", "SMS alerts ke liye mera naya mobile number register karein."),
        ("I need to request a new twenty-five-leaf personalized cheque book.", "مجھے پچیس پتوں والی نئی چیک بک جاری کروانے کی درخواست دینی ہے۔", "Mujhe 25 pitton wali nayi cheque book ki darkhwast deni hai."),
        ("Ensure your signature matches the one recorded in the bank system.", "یقینی بنائیں کہ آپ کے دستخط بینک ریکارڈ سے بالکل ملتے ہوں۔", "Yaqeeni banayein ke dastakhat bank record se miltay hon."),
        ("You can set up automatic recurring utility bill payments online.", "آپ بجلی اور گیس کے بلوں کی خودکار ادائیگی آن لائن سیٹ کر سکتے ہیں۔", "Aap utility bills ki khudkaar adayigi online set kar saktay hain."),
        ("A wise budget ensures savings for unexpected future emergencies.", "ایک دانشمندانہ بجٹ غیر متوقع اخراجات کے لیے بچت فراہم کرتا ہے۔", "Aik danishmandana budget ghair mutawaqqe ikhrajat ke liye bachat deta hai."),
        ("What is the current foreign exchange currency exchange rate for US Dollar?", "امریکی ڈالر کے تبادلے کا موجودہ اوپن مارکیٹ ریٹ کیا ہے؟", "US Dollar ke tabadlay ka mojuda rate kya hai?"),
        ("I need to encash this government prize bond at the counter.", "مجھے کاؤنٹر سے یہ پرائز بانڈ کیش کروانا ہے۔", "Mujhe counter se yeh prize bond cash karwana hai."),
        ("Never share your banking OTP or secret PIN code with anyone.", "اپنا بینک او ٹی پی یا خفیہ پن کوڈ کبھی کسی سے شیئر نہ کریں۔", "Apna bank OTP ya khufia PIN code kabhi share na karein."),
        ("Beware of fraudulent phishing phone calls asking for card numbers.", "کارڈ نمبر مانگنے والی جعلی فون کالز سے ہمیشہ ہوشیار رہیں۔", "Card number maangnay wali jaali phone calls se hoshiyar rahein."),
        ("I want to set a lower transaction limit on online ecommerce.", "میں آن لائن خریداری کے لیے روزانہ کی کم حد مقرر کرنا چاہتا ہوں۔", "Mein online khareedari ke liye kam hadd muqarrar karna chahta hoon."),
        ("What are the requirements for opening an Islamic Current Account?", "اسلامک کرنٹ اکاؤنٹ کھولنے کے لیے کیا شرائط ہیں؟", "Islamic current account kholnay ke liye kya sharait hain?"),
        ("This branch offers safe deposit locker vaults for valuables.", "یہ برانچ قیمتی سامان کے لیے محفوظ لاکر کی سہولت دیتی ہے۔", "Yeh branch qeemti saman ke liye safe locker ki sahoolat deti hai."),
        ("How can I track my investment portfolio in mutual funds?", "میں میوچل فنڈز میں اپنی سرمایہ کاری کا منافع کیسے دیکھ سکتا ہوں؟", "Mein mutual funds mein apni sarmayakari kaisay dekh sakta hoon?"),
        ("Compound growth over long time horizons creates true wealth.", "طویل مدت کی بچت اور سرمایہ کاری حقیقی مالی آزادی لاتی ہے۔", "Taweel muddat ki sarmayakari haqeeqi maali azaadi laati hai."),
        ("Always balance your checkbook and monitor bank statements monthly.", "ہر ماہ اپنے اخراجات اور بینک اسٹیٹمنٹ کا بغور جائزہ لیں۔", "Har maah apne ikhrajat aur bank statement ka jaiza lein."),
        ("Can I link my international Paypal account to this local card?", "کیا میں اپنا پے پال اکاؤنٹ اس لوکل کارڈ کے ساتھ جوڑ سکتا ہوں؟", "Kya mein apna PayPal account is card ke sath jorr sakta hoon?"),
        ("The bank charges nominal fees for interbank wire transactions.", "بینک دوسرے بینکوں میں رقم بھیجنے پر معمولی فیس لیتا ہے۔", "Bank doosray bankon mein raqam bhejnay par mamooli fees leta hai."),
        ("My debit card tap-to-pay contactless feature is very convenient.", "میرے کارڈ سے بغیر پاس ورڈ فوری ادائیگی کی سہولت بہت آسان ہے۔", "Mere card se contactless adayigi ki sahoolat bohat aasan hai."),
        ("I received an instant alert for a debit card POS purchase.", "مجھے شاپنگ پر رقم کٹنے کا فوری ایس ایم ایس موصول ہو گیا۔", "Mujhe shopping par raqam katnay ka fauri SMS mil gaya."),
        ("Please issue a bank certificate confirming my account balance.", "اکاؤنٹ بیلنس کی تصدیق کے لیے بینک کا سرکاری لیٹر جاری کریں۔", "Account balance ki tasdeeq ke liye bank certificate jari karein."),
        ("How can I update my residential address in bank records?", "بینک ریکارڈ میں میں اپنا رہائشی پتہ کیسے تبدیل کروا سکتا ہوں؟", "Bank record mein apna rehaishi pata kaisay tabdeel karwa sakta hoon?"),
        ("Investing in diversified low-risk assets protects against inflation.", "مختلف جگہوں پر سرمایہ کاری مہنگائی کے اثرات سے محفوظ رکھتی ہے۔", "Mukhtalif jaghon par sarmayakari mehngai se mahfooz rakhti hai."),
        ("The teller verified my thumb impression on the biometric device.", "کاؤنٹر کیشئر نے بائیو میٹرک ڈیوائس پر میرا انگوٹھا تصدیق کیا۔", "Cashier ne biometric device par mera angootha tasdeeq kiya."),
        ("What are the interest rates for export refinancing facilities?", "برآمدی کاروبار کے لیے فنانسنگ کی شرح سود کیا ہے؟", "Bar-aamadi karobar ke liye financing ki sharah kya hai?"),
        ("Financial discipline is the bedrock of lasting prosperity.", "مالی نظم و ضبط ہی پائیدار خوشحالی کی سب سے مضبوط بنیاد ہے۔", "Maali nazm-o-zabt hi payedaar khush-haali ki bunyad hai."),
        ("Can I deposit foreign currency cash into a Roshan Digital Account?", "کیا روشن ڈیجیٹل اکاؤنٹ میں غیر ملکی کرنسی جمع ہو سکتی ہے؟", "Kya Roshan Digital Account mein foreign currency jama ho sakti hai?"),
        ("The customer service officer addressed all my queries politely.", "کسٹمر سروس افسر نے میرے تمام سوالات کے شائستہ جوابات دیے۔", "Customer service officer ne mere tamam sawalat ke jawab diye."),
        ("Always destroy expired cards by cutting through chip and magnetic stripe.", "پرانے کارڈز کو ہمیشہ چپ اور پٹی سے کاٹ کر ضائع کریں۔", "Puranay cards ko chip aur patti se kaat kar zaya karein."),
        ("You can scan the QR code at merchant checkouts to pay instantly.", "دکانوں پر کیو آر کوڈ اسکین کر کے فوری ادائیگی کی جا سکتی ہے۔", "Dukanon par QR code scan kar ke fauri payment ki ja sakti hai."),
        ("Maintain an emergency emergency rainy day fund of six months.", "کم از کم چھ ماہ کے اخراجات کے برابر ہنگامی رقم محفوظ رکھیں۔", "Kam az kam 6 maah ke ikhrajat ke barabar emergency fund rakhein."),
        ("The banker explained the difference between credit and debit.", "بینکر نے کریڈٹ اور ڈیبٹ کے فرق کی مکمل وضاحت کی۔", "Banker ne credit aur debit ke farq ki wazahat ki."),
        ("Automated bill payments ensure you never miss any due date.", "خودکار ادائیگیاں آخری تاریخ نکلنے کے جرمانے سے بچاتی ہیں۔", "Khudkaar adaiygi aakhri tareekh nikalnay ke jurmanay se bachati hai."),
        ("Always review the schedule of bank service charges annually.", "بینک کے سالانہ سروس چارجز کے شیڈول کا ضرور مطالعہ کریں۔", "Bank ke salana service charges ka mutala'a zaroor karein."),
        ("Thank you for the prompt, transparent, and secure banking service.", "فوری، شفاف اور محفوظ بینکنگ سروس فراہم کرنے کا شکریہ۔", "Fauri, shaffaaf aur mahfooz banking service ka shukriya."),
        ("May your finances and legitimate earnings prosper abundantly!", "اللہ تعالیٰ آپ کے حلال رزق اور مال و دولت میں برکت عطا فرمائے!", "Allah Ta'ala aap ke halaal rizq mein barkat ata farmaye!")
    ]

    # 33. Real Estate & Renting
    t33 = [
        ("I am looking to rent a three-bedroom family apartment.", "میں تین بیڈ رومز والا خاندانی اپارٹمنٹ کرائے پر تلاش کر رہا ہوں۔", "Mein teen bedrooms wala khandani apartment kiraye par talash kar raha hoon."),
        ("What is the monthly rental demand and required security deposit?", "ماہانہ کرایہ اور ایڈوانس سیکیورٹی ڈپازٹ کتنا ہے؟", "Maahana kiraya aur advance security deposit kitna hai?"),
        ("The lease agreement is valid for a period of eleven months.", "کرایہ نامہ گیارہ ماہ کی مدت کے لیے قابلِ عمل ہوگا۔", "Kiraya-nama 11 maah ki muddat ke liye qabil-e-amal hoga."),
        ("Are maintenance charges and water supply included in rent?", "کیا بلڈنگ کی دیکھ بھال اور پانی کے بل کرائے میں شامل ہیں؟", "Kya building ki dekh bhaal aur paani ke bill kiraye mein shamil hain?"),
        ("The property has a dedicated underground car parking space.", "اس مکان کے ساتھ تہہ خانے میں محفوظ گاڑی کی پارکنگ موجود ہے۔", "Is makaan ke sath teh-khanay mein gaari ki parking maujood hai."),
        ("Is the neighborhood secure, peaceful, and family-friendly?", "کیا یہ محلہ محفوظ، پرسکون اور خاندانی رہائش کے لیے موزوں ہے؟", "Kya yeh mohalla mahfooz, pursukoon aur rehaish ke liye theek hai?"),
        ("How far is the nearest public park, school, and grocery market?", "قریبی پارک، اسکول اور گروسری مارکیٹ کتنے فاصلے پر ہیں؟", "Qareebi park, school aur grocery market kitnay faaslay par hain?"),
        ("The landlord agreed to repaint the living room walls before move-in.", "مالک مکان شفٹ ہونے سے پہلے کمروں پر نیا رنگ کروانے پر راضی ہو گیا۔", "Maalik-e-makaan shift honay se pehle rang karwanay par raazi ho gaya."),
        ("Ensure the property has independent electricity and gas meters.", "دیکھ لیں کہ گھر کے بجلی اور گیس کے میٹر بالکل الگ ہوں۔", "Dekh lein ke ghar ke bijli aur gas ke meter bilkul alag hon."),
        ("Read all terms in the tenancy contract carefully before signing.", "دستخط کرنے سے پہلے کرایہ نامے کی تمام شرائط غور سے پڑھیں۔", "Dastakhat karne se pehle kiraya-namay ki sharait ghaur se parhein."),
        ("We would like to inspect the plumbing and electrical wiring thoroughly.", "ہم پلمبنگ اور بجلی کی وائرنگ کا اچھی طرح معائنہ کرنا چاہتے ہیں۔", "Hum plumbing aur bijli ki wiring ka achi tarah muaina karna chahtay hain."),
        ("Is there twenty-four-hour backup generator power for elevators?", "کیا لفٹ کے لیے چوبیس گھنٹے جنریٹر کا بیک اپ موجود ہے؟", "Kya lift ke liye 24 ghantay generator ka backup maujood hai?"),
        ("The house boasts a spacious green front lawn and rooftop terrace.", "مکان میں ایک کھلا سرسبز لان اور کشادہ چھت موجود ہے۔", "Makaan mein aik khula sarsabz lawn aur chhat maujood hai."),
        ("What is the notice period required before terminating tenancy?", "مکان خالی کرنے سے پہلے کتنے دن کا نوٹس دینا لازمی ہے؟", "Makaan khaali karne se pehle kitnay din ka notice dena laazmi hai?"),
        ("Both parties must sign the registered stamped legal agreement.", "دونوں فریقین کو اسٹامپ پیپر پر قانونی معاہدے پر دستخط کرنے ہوں گے۔", "Dono fareeqain ko stamp paper par dastakhat karne hon ge."),
        ("Are pets like cats or dogs permitted within this apartment complex?", "کیا اس بلڈنگ میں بلیاں یا پالتو کتے رکھنے کی اجازت ہے؟", "Kya is building mein paaltu janwar rakhnay ki ijazat hai?"),
        ("The real estate broker arranged a viewing of the house today.", "پراپرٹی ڈیلر نے آج دوپہر مکان دکھانے کا انتظام کیا ہے۔", "Property dealer ne aaj dopahar makaan dikhanay ka intezam kiya hai."),
        ("What is the commission rate charged by the property agent?", "پراپرٹی ایجنٹ کی کمیشن کی کیا شرح ہے؟", "Property agent ki commission ki kya sharah hai?"),
        ("Ensure all previous utility bills are fully paid and cleared.", "تسلی کر لیں کہ پچھلے تمام بجلی و گیس کے بل مکمل ادا شدہ ہوں۔", "Tasalli kar lein ke pichlay tamam utility bills ada shuda hon."),
        ("A peaceful and clean home is a sanctuary after a tiring workday.", "ایک پرسکون اور صاف گھر دن بھر کی تھکن کے بعد پناہ گاہ ہوتا ہے۔", "Aik pursukoon ghar din bhar ki thakan ke baad panah-gah hota hai."),
        ("The flat has plenty of natural sunlight and fresh cross ventilation.", "فلیٹ میں قدرتی دھوپ اور تازہ ہوا کی آمد و رفت بہترین ہے۔", "Flat mein qudrati dhoop aur taaza hawa ki aamad-o-raft behtareen hai."),
        ("Is the commercial shop located on the main road high footfall?", "کیا یہ تجارتی دکان مین روڈ پر زیادہ گاہکوں والی جگہ پر ہے؟", "Kya yeh tijarti dukan main road par zyada gahkon wali jagah hai?"),
        ("We need to transfer the utility meters to the new tenant's name.", "ہمیں بجلی کے بل کا نام نئے کرائے دار کے نام کروانا ہوگا۔", "Humein bijli ke bill ka naam naye kirayedaar ke naam karwana hoga."),
        ("The building has round-the-clock CCTV surveillance and security guards.", "عمارت میں چوبیس گھنٹے سی سی ٹی وی کیمرے اور سیکیورٹی گارڈز ہیں۔", "Imaarat mein 24 ghantay CCTV cameras aur security guards hain."),
        ("What is the annual rent escalation rate specified in contract?", "معاہدے میں سالانہ کرایہ بڑھانے کی کیا شرح لکھی گئی ہے؟", "Muahiday mein salana kiraya barhanay ki kya sharah likhi gayi hai?"),
        ("Can we install an air conditioner split unit in the master bedroom?", "کیا ہم ماسٹر بیڈ روم میں اسپلٹ اے سی لگا سکتے ہیں؟", "Kya hum master bedroom mein split AC laga saktay hain?"),
        ("The landlord is responsible for major structural and roof repairs.", "عمارت کی بڑی مرمت اور چھت کا کام مالک مکان کی ذمہ داری ہے۔", "Imaarat ki barri marammat maalik-e-makaan ki zimmedari hai."),
        ("Minor wear and tear like light bulbs is maintained by tenant.", "چھوٹے موٹے روزمرہ کے کام جیسے بلب وغیرہ کرائے دار کرواتا ہے۔", "Chhotay motay rozmarrah ke kaam kirayedaar karwata hai."),
        ("Ensure you collect a written payment receipt for monthly rent.", "ماہانہ کرائے کی ادائیگی پر ہمیشہ تحریری رسید ضرور حاصل کریں۔", "Maahana kiraye ki adayigi par tehreeri raseed zaroor haasil karein."),
        ("Living close to reliable public transit saves commute hours.", "پبلک ٹرانسپورٹ کے قریب رہائش سفر کے قیمتی گھنٹے بچاتی ہے۔", "Public transport ke qareeb rehaish safar ke ghantay bachati hai."),
        ("The residential society requires an entry sticker for private cars.", "سوسائٹی کے اندر داخلے کے لیے گاڑی پر اسٹیکر لگانا لازمی ہے۔", "Society ke andar dakhlay ke liye gaari par sticker lagana laazmi hai."),
        ("Is there any designated waste collection system in this block?", "کیا اس بلاک میں کوڑا اٹھانے کا کوئی باقاعدہ انتظام ہے؟", "Kya is block mein koora uthanay ka baqaida intezam hai?"),
        ("The kitchen is fully modular with built-in wooden cabinets.", "باورچی خانے میں لکڑی کی خوبصورت الماریاں اور درازیں لگی ہیں۔", "Bawarchi-khanay mein lakri ki almariyan aur daraazein lagi hain."),
        ("Always verify property title ownership documents at the land registry.", "رجسٹری آفس سے مکان کی ملکیت کے کاغذات کی تصدیق ضرور کریں۔", "Registry office se makaan ki milkiyat ke kaghazat check karein."),
        ("The commercial office space comes with high-speed fiber internet.", "دفتری جگہ میں تیز رفتار فائبر آپٹک انٹرنیٹ پہلے سے لگا ہے۔", "Daftari jagah mein taiz fiber internet pehle se laga hai."),
        ("Is there an elevator suitable for moving heavy home furniture?", "کیا فرنیچر اوپر لے جانے کے لیے بڑی کارگو لفٹ موجود ہے؟", "Kya furniture ooper le jaanay ke liye barri cargo lift hai?"),
        ("We are looking for an unfurnished corner plot townhouse.", "ہم کونے کے پلاٹ پر بنا ہوا سادہ بغیر فرنیچر مکان تلاش کر رہے ہیں۔", "Hum konay ke plot par bana ghair furnished makaan dhoond rahe hain."),
        ("The rental market tends to be more active during summer holidays.", "گرمیوں کی چھٹیوں میں کرائے کے مکانوں کی مانگ زیادہ ہوتی ہے۔", "Garmiyon ki chuttiyon mein kiraye ke makanon ki maang zyada hoti hai."),
        ("Ensure the property has no pending property tax liabilities.", "یقینی بنائیں کہ مکان پر کوئی پرانا پراپرٹی ٹیکس واجب الادا نہ ہو۔", "Yaqeeni banayein ke makaan par koi property tax baaqi na ho."),
        ("A good relationship between tenant and landlord creates peace.", "مالک اور کرائے دار کے اچھے تعلقات دونوں کے لیے باعثِ سکون ہیں۔", "Maalik aur kirayedaar ke achay taluqaat sukoon ka baais hain."),
        ("Can we inspect the water pressure on the upper penthouse floor?", "کیا ہم اوپر والی منزل پر پانی کا پریشر چیک کر سکتے ہیں؟", "Kya hum ooper wali manzil par paani ka pressure check kar saktay hain?"),
        ("The society has a mosque, community center, and sports ground.", "سوسائٹی میں خوبصورت مسجد، کمیونٹی سینٹر اور کھیل کا میدان ہے۔", "Society mein khubsurat masjid aur khel ka maidan hai."),
        ("Keep a digital photocopy of your signed lease agreement safe.", "دستخط شدہ کرایہ نامے کی تصویر اور کاپی ہمیشہ محفوظ رکھیں۔", "Kiraya-namay ki photo aur copy hamesha mahfooz rakhein."),
        ("Inform the society management office before shifting furniture.", "سامان شفٹ کرنے سے پہلے سوسائٹی کے دفتر کو مطلع کریں۔", "Saman shift karne se pehle society ke daftar ko aagah karein."),
        ("The location provides quick direct access to the main highway.", "یہ جگہ موٹروے اور مین ہائی وے کے بالکل قریب واقع ہے۔", "Yeh jagah motorway aur main highway ke bilkul qareeb waqia hai."),
        ("A warm and welcoming home is where fond memories are created.", "ایک پیار بھرا گھر وہ جگہ ہے جہاں خوبصورت یادیں جنم لیتی ہیں۔", "Aik pyar bhara ghar woh jagah hai jahan khubsurat yaadein banti hain."),
        ("Always pay your rent promptly on the agreed date of the month.", "ہر ماہ کی طے شدہ تاریخ پر کرایہ ہمیشہ وقت پر ادا کریں۔", "Har maah ki tay shuda tareekh par kiraya waqt par ada karein."),
        ("Thank you for showing us around this delightful property.", "ہمیں یہ خوبصورت مکان دکھانے کا آپ کا بہت بہت شکریہ۔", "Humein yeh khubsurat makaan dikhanay ka bohat shukriya."),
        ("We look forward to finalizing the deal and moving in soon.", "ہم جلد معاہدہ طے کر کے یہاں شفٹ ہونے کے منتظر ہیں۔", "Hum jald muahida tay kar ke yahan shift honay ke muntazir hain."),
        ("May your new home bring abundant peace, barakah, and happiness!", "اللہ تعالیٰ آپ کے نئے گھر میں ڈھیروں امن، برکت اور خوشیاں لائے!", "Allah Ta'ala aap ke naye ghar mein barkat aur khushiyan laye!")
    ]

    # 34. Technology & Smartphones
    t34 = [
        ("My smartphone battery drains very quickly; how can I optimize it?", "میرے موبائل کی بیٹری جلد ختم ہو جاتی ہے، اسے کیسے بہتر کروں؟", "Mere mobile ki battery jald khatam ho jaati hai, kaisay behtar karoon?"),
        ("Turn off background location tracking and reduce screen brightness.", "لوکیشن بند کریں اور اسکرین کی برائٹنس کم رکھیں تو بیٹری بچے گی۔", "Location band karein aur screen brightness kam rakhein to bachat hogi."),
        ("Make sure you install the latest operating system security patch.", "یقینی بنائیں کہ آپ نے سیکیورٹی کی تازہ ترین اپ ڈیٹ انسٹال کی ہے۔", "Yaqeeni banayein ke aap ne latest update install ki hai."),
        ("How do I backup all my photos and WhatsApp chats to the cloud?", "میں اپنی تصاویر اور واٹس ایپ کا کلاؤڈ بیک اپ کیسے بناؤں؟", "Mein apni tasaveer aur WhatsApp ka cloud backup kaisay banaoon?"),
        ("This smartphone features a 120Hz AMOLED fluid display.", "اس اسمارٹ فون میں ایک سو بیس ہرٹز کا انتہائی ہموار ڈسپلے ہے۔", "Is smartphone mein 120Hz ka smooth display hai."),
        ("Clear cache files regularly to free up internal storage space.", "موبائل کی میموری خالی کرنے کے لیے کیشے فائلز صاف کریں۔", "Mobile ki memory khaali karne ke liye cache files saaf karein."),
        ("Always use a strong screen lock PIN and fingerprint sensor.", "ہمیشہ مضبوط پاس ورڈ اور فنگر پرنٹ لاک کا استعمال کریں۔", "Hamesha mazboot password aur fingerprint lock istemal karein."),
        ("Why is my Wi-Fi internet connection disconnecting repeatedly?", "میرا وائی فائی انٹرنیٹ بار بار کیوں منقطع ہو رہا ہے؟", "Mera Wi-Fi internet baar baar kyun disconnect ho raha hai?"),
        ("Restart your home broadband router to refresh network signals.", "انٹرنیٹ روٹر کو ری اسٹارٹ کر کے سگنل بحال کریں۔", "Internet router ko restart kar ke signal bahal karein."),
        ("Technology should empower human connection, not distract from life.", "ٹیکنالوجی کو زندگی آسان بنانی چاہیے نہ کہ انسان کو قید کرنا۔", "Technology ko zindagi aasan banani chahiye na ke insaan ko qaid karna."),
        ("How many gigabytes of RAM and internal storage does this model have?", "اس فون میں کتنے جی بی ریم اور انٹرنل اسٹوریج موجود ہے؟", "Is phone mein kitnay GB RAM aur internal storage maujood hai?"),
        ("The primary rear camera takes stunning photos in low night light.", "اس کا مین کیمرہ رات کی مدہم روشنی میں بھی شاندار تصاویر لیتا ہے۔", "Is ka main camera raat ki madham roshni mein shandar photo leta hai."),
        ("Enable two-factor authentication (2FA) on all critical online accounts.", "تمام اہم اکاؤنٹس پر ٹو فیکٹر ویریفیکیشن ضرور آن کریں۔", "Tamam ahem accounts par Two-Factor Verification zaroor on karein."),
        ("Do not click on suspicious links sent in random SMS text messages.", "نامعلوم ایس ایم ایس میں آنے والے مشکوک لنکس پر کبھی کلک نہ کریں۔", "Na-maloom SMS mein aanay walay mashkook links par click na karein."),
        ("This fast charger can power your device to 80% in 25 minutes.", "یہ فاسٹ چارجر پچیس منٹ میں فون کو اسی فیصد چارج کر دیتا ہے۔", "Yeh fast charger 25 minute mein 80% charge kar deta hai."),
        ("Is this wireless Bluetooth earbud sweat and water-resistant?", "کیا یہ بلیوٹوتھ ہینڈز فری پسینے اور پانی سے محفوظ ہیں؟", "Kya yeh Bluetooth handsfree paseenay aur paani se mahfooz hain?"),
        ("You can scan printed documents directly into PDF using phone camera.", "آپ موبائل کیمرے سے کسی بھی کاغذ کو پی ڈی ایف بنا سکتے ہیں۔", "Aap mobile camera se kisi bhi kaghaz ko PDF bana saktay hain."),
        ("Dark mode saves OLED battery life and reduces eye strain at night.", "ڈارک موڈ بیٹری بھی بچاتا ہے اور رات کو آنکھوں کو سکون دیتا ہے۔", "Dark mode battery bhi bachata hai aur aankhon ko sukoon deta hai."),
        ("Use an ergonomic phone stand to maintain healthy neck posture.", "گردن کے درد سے بچنے کے لیے موبائل اسٹینڈ کا استعمال کریں۔", "Gardan ke dard se bachnay ke liye mobile stand ka istemal karein."),
        ("Artificial intelligence is revolutionizing daily productivity tools.", "مصنوعی ذہانت روزمرہ کے کاموں کو انتہائی تیز بنا رہی ہے۔", "Masnooi zahanat rozmarrah ke kamon ko taiz bana rahi hai."),
        ("How do I transfer data from my old Android phone to a new one?", "پرانے اینڈرائڈ فون سے نئے فون میں ڈیٹا کیسے منتقل کریں؟", "Puranay Android phone se naye phone mein data kaisay transfer karein?"),
        ("Use Google Drive or Smart Switch for seamless phone migration.", "ڈیٹا ٹرانسفر کے لیے اسمارٹ سوئچ یا گوگل ڈرائیو استعمال کریں۔", "Data transfer ke liye Smart Switch ya Google Drive istemal karein."),
        ("The processor handles heavy 3D gaming without thermal throttling.", "یہ پروسیسر گرم ہوئے بغیر بھاری گیمز آسانی سے چلاتا ہے۔", "Yeh processor garam hue baghair bhaari games chala leta hai."),
        ("Always keep a tempered glass protector on your smartphone screen.", "موبائل اسکرین پر ہمیشہ مضبوط ٹیمپرڈ گلاس پروٹیکٹر لگائیں۔", "Mobile screen par hamesha mazboot tempered glass lagayein."),
        ("Why is this application crashing every time I open it?", "یہ ایپ ہر بار کھولنے پر بند (کریش) کیوں ہو رہی ہے؟", "Yeh app har baar kholnay par band kyun ho rahi hai?"),
        ("Try clearing the app data or reinstalling the latest version.", "ایپ کا ڈیٹا کلیئر کریں یا دوبارہ انسٹال کر کے دیکھیں۔", "App ka data clear karein ya dobara install kar ke dekhein."),
        ("Voice typing in Urdu and English has become incredibly accurate.", "اردو اور انگریزی میں بول کر ٹائپ کرنا اب بہت آسان ہو گیا ہے۔", "Urdu aur English mein bol kar type karna ab aasan ho gaya hai."),
        ("Do not use your phone while it is plugged into fast charging.", "فاسٹ چارجنگ پر لگے موبائل کو استعمال کرنے سے گریز کریں۔", "Fast charging par lagay mobile ko istemal karne se gurez karein."),
        ("Set daily screen time limits to maintain a healthy digital life.", "صحت مند معمولات کے لیے اسکرین ٹائم کی حد مقرر کریں۔", "Sehat-mand mamoolat ke liye screen time ki hadd muqarrar karein."),
        ("Technology is a useful servant but a dangerous master.", "ٹیکنالوجی ایک بہترین خادم ہے لیکن ایک برا حاکم۔", "Technology aik behtareen khaadim hai lekin aik bura haakim."),
        ("Can I use two physical SIM cards and an eSIM on this device?", "کیا اس فون میں دو سمیں اور ای سم ایک ساتھ چل سکتی ہیں؟", "Kya is phone mein do SIMs aur eSIM aik sath chal sakti hain?"),
        ("Turn on flight mode to charge your battery significantly faster.", "موبائل کو تیزی سے چارج کرنے کے لیے فلائٹ موڈ آن کر دیں۔", "Mobile ko taizi se charge karne ke liye flight mode on kar dein."),
        ("Keep your private encryption keys and passwords in a password manager.", "اپنے پاس ورڈز ہمیشہ محفوظ پاس ورڈ منیجر میں رکھیں۔", "Apne passwords hamesha mahfooz password manager mein rakhein."),
        ("This laptop comes with an ultra-fast Solid State Drive (SSD).", "اس لیپ ٹاپ میں تیز رفتار ایس ایس ڈی ہارڈ ڈرائیو لگی ہے۔", "Is laptop mein taiz raftaar SSD hard drive lagi hai."),
        ("Always safely eject USB thumb drives before unplugging them.", "یو ایس بی نکالنے سے پہلے کمپیوٹر سے سیفلی ایجیکٹ کریں۔", "USB nikaalnay se pehle computer se safely eject karein."),
        ("Cloud storage lets you access your important files from anywhere.", "کلاؤڈ اسٹوریج کے ذریعے آپ کسی بھی جگہ سے فائلز کھول سکتے ہیں۔", "Cloud storage ke zariye aap kisi bhi jagah se files khol saktay hain."),
        ("This smart smartwatch tracks heartbeat, sleep stages, and daily steps.", "یہ اسمارٹ واچ دل کی دھڑکن، نیند اور قدموں کو ریکارڈ کرتی ہے۔", "Yeh smartwatch dil ki dharkan, neend aur qadam record karti hai."),
        ("Avoid charging your smartphone under your sleeping pillow.", "سوتے وقت تکیے کے نیچے موبائل چارجنگ پر مت لگائیں۔", "Sotay waqt takiye ke neechay mobile charging par mat lagayein."),
        ("Use noise-canceling headphones in loud, crowded workspaces.", "شور والی جگہوں پر نائز کینسلیشن والے ہیڈ فون استعمال کریں۔", "Shor wali jaghon par noise cancellation headphones istemal karein."),
        ("Embrace technology with purpose, balance, and human empathy.", "ٹیکنالوجی کا استعمال اعتدال، مقصد اور انسانیت کے ساتھ کریں۔", "Technology ka istemal aitadaal, maqsad aur insaniyat ke sath karein."),
        ("How do I share internet from mobile via portable personal hotspot?", "موبائل سے دوسرے فون پر ہاٹ اسپاٹ کیسے آن کریں؟", "Mobile se doosray phone par hotspot kaisay on karein?"),
        ("Go to settings, select portable hotspot, and set a strong password.", "سیٹنگز میں جائیں، ہاٹ اسپاٹ کھولیں اور پاس ورڈ لگائیں۔", "Settings mein jayein, hotspot kholein aur password lagayein."),
        ("This device supports 5G ultra-high-speed mobile cellular data.", "یہ فون تیز ترین فائیو جی نیٹ ورک کو سپورٹ کرتا ہے۔", "Yeh phone taiz tareen 5G network ko support karta hai."),
        ("Always double-check recipient email address before hitting send.", "ای میل بھیجنے سے پہلے وصول کنندہ کا پتہ ضرور چیک کریں۔", "Email bhejnay se pehle receiver ka pata zaroor check karein."),
        ("Mute non-essential app notifications to enhance your deep focus.", "یکسوئی کے لیے غیر ضروری ایپس کے نوٹیفیکیشن بند رکھیں۔", "Yaksooi ke liye ghair zaroori notifications band rakhein."),
        ("Clean your smartphone screen gently with a microfiber cloth.", "موبائل اسکرین کو مائیکرو فائبر کے نرم کپڑے سے صاف کریں۔", "Mobile screen ko microfiber ke narm kapray se saaf karein."),
        ("Keep your hardware and software up to date for smooth performance.", "بہترین کارکردگی کے لیے سافٹ ویئر ہمیشہ اپ ٹو ڈیٹ رکھیں۔", "Behtareen karkardagi ke liye software hamesha up-to-date rakhein."),
        ("Digital literacy opens unlimited opportunities for modern careers.", "ڈیجیٹل مہارتیں جدید دور میں روزگار کے لاتعداد مواقع کھولتی ہیں۔", "Digital maharatein naye daur mein rozgar ke darwazay kholti hain."),
                ("Regular software updates protect your device against newly discovered security vulnerabilities.", "سافٹ ویئر اپ ڈیٹس آپ کے فون کو نئے سیکیورٹی خطرات سے محفوظ رکھتی ہیں۔", "Software updates aap ke phone ko naye security khatraat se mahfooz rakhti hain."),
        ("May technology serve as a stepping stone to your success!", "اللہ کرے ٹیکنالوجی آپ کی ترقی اور کامیابی کا ذریعہ بنے!", "Allah karay technology aap ki taraqi aur kamyabi ka zariya banay!")
    ]

    # 35. Social Media & Internet
    t35 = [
        ("How do I protect my personal privacy on social media platforms?", "سوشل میڈیا پر میں اپنی ذاتی معلومات کیسے محفوظ رکھوں؟", "Social media par mein apni zaati maloomat kaisay mahfooz rakhoon?"),
        ("Never share your home address, phone number, or live location publicly.", "اپنا گھر کا پتہ، فون نمبر یا لائیو لوکیشن کبھی پبلک نہ کریں۔", "Apna ghar ka pata, phone number ya live location public na karein."),
        ("That educational short video went viral with millions of views.", "وہ تعلیمی مختصر ویڈیو لاکھوں ویوز کے ساتھ وائرل ہو گئی۔", "Woh taleemi short video lakhon views ke sath viral ho gayi."),
        ("Be respectful and constructive when commenting on online posts.", "آن لائن کمنٹس کرتے وقت ہمیشہ شائستگی اور اخلاق کا دھیان رکھیں۔", "Online comments kartay waqt hamesha shaistagi ka dhyan rakhein."),
        ("Always verify breaking news before sharing it in family groups.", "خاندانی گروپس میں خبر بھیجنے سے پہلے اس کی سچائی ضرور پرکھیں۔", "Khandani groups mein khabar bhejnay se pehle sachai zaroor parkhein."),
        ("Spreading unverified rumors causes unnecessary panic and harm.", "بغیر تصدیق شدہ افواہیں پھیلانا شدید پریشانی کا باعث بنتا ہے۔", "Baghair tasdeeq shuda afwahein phailana shadeed nuqsan deta hai."),
        ("You can restrict who sees your stories, posts, and profile photo.", "آپ سیٹ کر سکتے ہیں کہ آپ کی پوسٹ کون کون دیکھ سکتا ہے۔", "Aap set kar saktay hain ke aap ki post kaun kaun dekh sakta hai."),
        ("Report hateful comments and block toxic online accounts immediately.", "نفرت انگیز کمنٹس کو رپورٹ کریں اور ایسے اکاؤنٹس کو بلاک کریں۔", "Nafrat-angeez comments ko report karein aur block karein."),
        ("Create engaging and high-value content that helps your audience.", "ایسا مفید مواد بنائیں جس سے لوگوں کو حقیقی فائدہ پہنچے۔", "Aisa mufeed mawaad banayein jis se logon ko faida pohanchay."),
        ("Do not let virtual likes define your inner self-worth and confidence.", "آن لائن لائکس کو اپنی ذاتی عزت اور خود اعتمادی کا معیار مت بنائیں۔", "Online likes ko apni zaati izzat ka meyaar mat banayein."),
        ("How do I grow organic followers on my educational YouTube channel?", "میں اپنے یوٹیوب چینل پر حقیقی سبسکرائبرز کیسے بڑھاؤں؟", "Mein apne YouTube channel par Subscribers kaisay barhaoon?"),
        ("Post consistent, high-quality videos with compelling thumbnail titles.", "مسلسل معیاری ویڈیوز اور پرکشش ٹائٹلز کے ساتھ کام کریں۔", "Musalsal meyaari videos aur purkashish titles ke sath kaam karein."),
        ("Engage actively with your audience in the comments section.", "کمنٹس میں اپنے ناظرین کے ساتھ باقاعدگی سے بات چیت کریں۔", "Comments mein apne viewers ke sath baqaidgi se baat karein."),
        ("Social media algorithms reward high viewer watch retention time.", "سوشل میڈیا کا الگورتھم پوری دیکھی جانے والی ویڈیو کو فروغ دیتا ہے۔", "Algorithm poori dekhi jaanay wali video ko promote karta hai."),
        ("Avoid doomscrolling late at night to ensure restful peaceful sleep.", "رات گئے مسلسل موبائل اسکرولنگ سے بچیں تاکہ پرسکون نیند آئے۔", "Raat gaye mobile scrolling se bachein taakay sukoon ki neend aaye."),
        ("Use professional platforms like LinkedIn to build career networks.", "پیشہ ورانہ نیٹ ورک بنانے کے لیے لنکڈ اِن کا استعمال کریں۔", "Paishawarana network bananay ke liye LinkedIn ka istemal karein."),
        ("Craft an authentic and compelling personal brand profile.", "ایک سچی اور بااثر ذاتی پروفائل ترتیب دیں۔", "Aik sachi aur ba-asar zaati profile tarteeb dein."),
        ("Share your professional achievements and insightful lessons learned.", "اپنی کامیابیوں اور سیکھے گئے اسباق کو دوسروں کے ساتھ شیئر کریں۔", "Apni kamyabiyon aur seekhay gaye sabaq ko share karein."),
        ("Cyberbullying is a serious offense punishable under cyber laws.", "آن لائن کسی کو ہراساں کرنا قانوناً ایک سنگین جرم ہے۔", "Online kisi ko pareshan karna qanoonan aik jurm hai."),
        ("Digital footprints remain on the internet permanently, so act wisely.", "انٹرنیٹ پر کیا گیا کام ہمیشہ رہتا ہے، اس لیے دانشمندی دکھائیں۔", "Internet par kiya gaya kaam hamesha rehta hai, danishmandi dikhayein."),
        ("How do I monetize my Facebook content and video reels?", "میں اپنی فیس بک ویڈیوز سے آمدنی کیسے حاصل کروں؟", "Mein apni Facebook videos se aamadni kaisay haasil karoon?"),
        ("Meet the required criteria of watch hours and policy compliance.", "پالیسی کی پابندی اور مطلوبہ ویو ٹائم کا ہدف پورا کریں۔", "Policy ki pabandi aur matlooba view time ka hadaf poora karein."),
        ("Use relevant and trending hashtags to improve discoverability.", "اپنی پوسٹس میں مناسب اور متعلقہ ہیش ٹیگز کا استعمال کریں۔", "Apni posts mein munasib hashtags ka istemal karein."),
        ("Be mindful of intellectual property and do not copy others' work.", "کاپی رائٹ کا احترام کریں اور دوسروں کا کام چوری نہ کریں۔", "Copyright ka ihtiram karein aur doosron ka kaam chori na karein."),
        ("Giving credit to original creators shows professional integrity.", "اصل مصنف کو کریڈٹ دینا آپ کے اعلیٰ کردار کی علامت ہے۔", "Asal creator ko credit dena aap ke aala kirdaar ki alamat hai."),
        ("Take regular digital detox breaks on weekends to recharge.", "ذہنی سکون کے لیے ویک اینڈ پر سوشل میڈیا سے وقفہ لیں۔", "Zehni sukoon ke liye weekend par social media se waqfa lein."),
        ("Real-life face-to-face conversations foster deeper human bonds.", "روبرو بیٹھ کر بات چیت دلوں کے زیادہ گہرے رشتے بناتی ہے۔", "Ro-ba-ro baith kar baat cheet dilon ke gehray rishtay banati hai."),
        ("Do not compare your backstage life with someone's highlight reel.", "کسی کی ظاہری چمک دمک کا اپنے حالات سے موازنہ مت کریں۔", "Kisi ki chamak damak ka apne halaat se mawazna mat karein."),
        ("Everyone is facing silent battles you know nothing about.", "ہر انسان کسی نہ کسی پوشیدہ آزمائش سے گزر رہا ہوتا ہے۔", "Har insaan kisi na kisi aazmaish se guzar raha hota hai."),
        ("Kindness online can save someone having a difficult day.", "آن لائن لکھا گیا ایک اچھا جملہ کسی کی اداس دنیا بدل سکتا ہے۔", "Online likha aik acha jumla kisi ki dunya badal sakta hai."),
        ("How do I report a fake impersonation account on Instagram?", "انسٹاگرام پر اپنے نام سے بنے جعلی اکاؤنٹ کو کیسے رپورٹ کروں؟", "Instagram par farzi account ko kaisay report karoon?"),
        ("Go to the profile menu, tap report, and choose impersonating me.", "پروفائل پر جائیں، رپورٹ دبائیں اور جعلی ہونے کا آپشن منتخب کریں۔", "Profile par jayein, report dabayein aur select karein."),
        ("Use strong passwords combining letters, numbers, and symbols.", "حروف، نمبرز اور علامات ملا کر مضبوط پاس ورڈ بنائیں۔", "Letters, numbers aur symbols mila kar mazboot password banayein."),
        ("Never click remember password on public cafe computers.", "پبلک کمپیوٹرز پر کبھی پاس ورڈ محفوظ (سیو) مت کریں۔", "Public computers par kabhi password save mat karein."),
        ("Log out of all remote browser sessions after using internet cafes.", "کیفے استعمال کرنے کے بعد تمام اکاؤنٹس لاگ آؤٹ کرنا نہ بھولیں۔", "Internet cafe ke baad tamam accounts logout karna na bhoolin."),
        ("Podcast interviews offer deep discussions on meaningful topics.", "پوڈکاسٹ انٹرویوز اہم موضوعات پر گہری گفتگو فراہم کرتے ہیں۔", "Podcast interviews ahem mauzooaat par gehri guftagu detay hain."),
        ("Follow credible educators, mentors, and thought leaders.", "معتبر اساتذہ اور رہنمائی کرنے والے ماہرین کو فالو کریں۔", "Mo'tabar asatiza aur rehnumaon ko follow karein."),
        ("Curate your social media feed to feed your mind positivity.", "اپنی فیڈ کو ایسا بنائیں کہ وہ آپ کو مثبت سوچ اور علم دے۔", "Apni feed ko aisa banayein ke woh aap ko ilm aur musbat soch de."),
        ("Unfollow negative pages that breed anger, jealousy, or despair.", "نفرت اور حسد پھیلانے والے صفحات کو ان فالو کر دیں۔", "Nafrat aur hasad phailanay walay pages ko unfollow kar dein."),
        ("Spread knowledge, hope, compassion, and uplifting messages.", "علم، امید، ہمدردی اور اچھے پیغامات کو فروغ دیں۔", "Ilm, umeed aur achay paighamaat ko farogh dein."),
        ("Online communities provide great support for shared hobbies.", "آن لائن فورمز مشترکہ مشاغل کے لیے بہترین مددگار ہیں۔", "Online communities shauq poora karne ke liye achi hain."),
        ("Learn how to identify deepfakes and manipulated digital media.", "جعلی ویڈیوز اور جھوٹی تصاویر کو پہچاننا سیکھیں۔", "Jaali videos aur jhooti tasaveer ko pehchanna seekhein."),
        ("Critical thinking is the ultimate shield against online falsehood.", "غور و فکر کرنا آن لائن جھوٹ کے خلاف سب سے بڑی ڈھال ہے۔", "Ghaur-o-fikr karna online jhoot ke khilaf sab se barri dhaal hai."),
        ("Support small local businesses by leaving positive reviews.", "مقامی چھوٹے کاروباروں کی حوصلہ افزائی کے لیے اچھے ریویوز دیں۔", "Chhotay karobaron ke liye achay reviews likhein."),
        ("Digital networking opens doors to international collaborations.", "آن لائن رابطے بین الاقوامی سطح پر کام کے مواقع پیدا کرتے ہیں۔", "Online rabtay international kaam ke darwazay kholtay hain."),
        ("Always be polite and professional in your direct messages.", "ان باکس میں بات کرتے وقت ہمیشہ شائستگی اور ادب برقرار رکھیں۔", "Inbox mein baat kartay waqt hamesha shaistagi barqarar rakhein."),
        ("Use your digital voice to stand up for justice and truth.", "اپنی آواز کو ہمیشہ سچائی اور انصاف کے لیے استعمال کریں۔", "Apni aawaz ko hamesha sachai aur insaaf ke liye istemal karein."),
        ("The internet is a vast ocean; choose to swim towards wisdom.", "انٹرنیٹ ایک سمندر ہے، اس میں سے حکمت کے موتی چنیں۔", "Internet aik samandar hai, is mein se hikmat ke moti chunein."),
                ("Meaningful digital connections inspire collective progress and empathy across nations.", "مثبت ڈیجیٹل رابطے قوموں میں باہمی ہمدردی اور ترقی کو فروغ دیتے ہیں۔", "Musbat digital rabtay qaumon mein baahmi hamdardi aur taraqi ko farogh detay hain."),
        ("Wishing you an inspiring, uplifting, and safe digital experience!", "اللہ کرے آپ کا آن لائن سفر ہمیشہ محفوظ، تعمیری اور کامیاب رہے!", "Allah karay aap ka online safar hamesha mahfooz aur kamyab rahay!")
    ]

    return [
        {"id": 31, "name": "At the Pharmacy & Medicine", "urduName": "فارمیسی اور ادویات", "icon": "medical_services", "desc": "Prescriptions, dosages, side effects, and healthcare items.", "sentences": t31},
        {"id": 32, "name": "Banking & Finance", "urduName": "بینک اور مالیات", "icon": "account_balance", "desc": "Accounts, deposits, ATM usage, cards, loans, and savings.", "sentences": t32},
        {"id": 33, "name": "Real Estate & Renting", "urduName": "جائیداد اور کرایہ داری", "icon": "home", "desc": "Finding houses, rental agreements, maintenance, and landlords.", "sentences": t33},
        {"id": 34, "name": "Technology & Smartphones", "urduName": "ٹیکنالوجی اور اسمارٹ فونز", "icon": "smartphone", "desc": "Mobile settings, battery, updates, apps, and computer troubleshooting.", "sentences": t34},
        {"id": 35, "name": "Social Media & Internet", "urduName": "سوشل میڈیا اور انٹرنیٹ", "icon": "share", "desc": "Profiles, privacy, viral content, networking, and safety.", "sentences": t35}
    ]
