#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os

topics_definitions = [
    (1, "Greetings & Introductions", "خیرمقدم اور تعارف", "chat", "Daily greetings, meeting people, and polite introductions."),
    (2, "Family & Relationships", "خاندان اور تعلقات", "people", "Talk about parents, siblings, children, and relatives."),
    (3, "Food & Restaurant", "کھانا اور ریستوراں", "restaurant", "Ordering food, reserving tables, and food preferences."),
    (4, "Shopping & Store", "خریداری اور دکان", "shopping_bag", "Inquiring about prices, bargaining, and buying goods."),
    (5, "Office & Career", "دفتر اور ملازمت", "work", "Workplace conversations, meetings, and project deadlines."),
    (6, "Job Interview & Career", "ملازمت کا انٹرویو", "school", "Common questions and impressive answers during interviews."),
    (7, "Travel & Airport", "سفر اور ہوائی اڈا", "flight", "Boarding flights, check-in, customs, and luggage."),
    (8, "Hotel & Accommodation", "ہوٹل اور قیام", "home", "Booking rooms, room service, and check-out."),
    (9, "Directions & City Navigation", "راستہ اور شہر کی رہنمائی", "explore", "Asking for directions, landmarks, and finding locations."),
    (10, "Health & Doctor Clinic", "صحت اور ڈاکٹر کا کلینک", "healing", "Explaining symptoms, booking doctor visits, and checkups."),
    (11, "Pharmacy & Medicine", "فارمیسی اور ادویات", "healing", "Buying medicines, dosage inquiries, and prescriptions."),
    (12, "Education & School Life", "تعلیم اور اسکول کی زندگی", "school", "Classroom talk, teachers, homework, and study habits."),
    (13, "Weather & Seasons", "موسم اور اوقات", "wb_sunny", "Talking about rain, sunshine, winter, summer, and forecast."),
    (14, "Time & Scheduling", "وقت اور شیڈول", "schedule", "Asking the time, making appointments, and calendar dates."),
    (15, "Banking & Money", "بینکنگ اور مالیات", "payments", "Opening accounts, ATM, transfers, and currency exchange."),
    (16, "Technology & Internet", "ٹیکنالوجی اور انٹرنیٹ", "computer", "Computers, internet connection, software, and tech issues."),
    (17, "Smartphone & Social Media", "اسمارٹ فون اور سوشل میڈیا", "phone_android", "Apps, notifications, messaging, and social profiles."),
    (18, "Hobbies & Free Time", "مشاغل اور تفریح", "sports_esports", "Gaming, gardening, reading, and weekend pastimes."),
    (19, "Sports & Fitness", "کھیل اور فٹنس", "fitness_center", "Gym, workouts, cricket, football, and running."),
    (20, "Entertainment & Movies", "تفریح اور فلمیں", "movie", "Cinema, TV series, actors, and comedy shows."),
    (21, "Music & Art", "موسیقی اور فن", "palette", "Songs, instruments, painting, and cultural art."),
    (22, "Daily Routine & Habits", "روزمرہ معمولات اور عادات", "alarm", "Waking up, hygiene, breakfast, and evening routines."),
    (23, "House & Home Chores", "گھر اور گھریلو کام", "cleaning_services", "Cleaning, laundry, dusting, and home organization."),
    (24, "Cooking & Kitchen", "کھانا پکانا اور باورچی خانہ", "restaurant_menu", "Recipes, spices, ingredients, and cooking techniques."),
    (25, "Transportation & Public Transit", "ٹرانسپورٹ اور بس/ٹرین", "directions_bus", "Buses, metro trains, auto rickshaws, and tickets."),
    (26, "Car Driving & Road Safety", "کار چلانا اور ٹریفک قوانین", "drive_eta", "Seatbelts, speed limits, parking, and traffic signs."),
    (27, "Emergency & Police Help", "ہنگامی صورتحال اور پولیس", "local_police", "Calling 15/911, reporting theft, and safety alerts."),
    (28, "Fire & Disaster Safety", "آگ اور قدرتی آفات سے حفاظت", "local_fire_department", "Fire alarms, extinguishers, earthquakes, and first aid."),
    (29, "Post Office & Couriers", "ڈاک خانہ اور کوریئر", "local_post_office", "Sending parcels, tracking numbers, and mail delivery."),
    (30, "Library & Books", "لائبریری اور مطالعہ", "local_library", "Borrowing books, quiet reading, and library cards."),
    (31, "Airport Baggage & Customs", "ایئرپورٹ سامان اور کسٹم", "luggage", "Luggage weight limits, customs duty, and baggage belt."),
    (32, "Renting an Apartment", "مکان کرائے پر لینا", "apartment", "Rent agreement, security deposit, and utilities."),
    (33, "Neighborhood & Community", "محلہ اور پڑوسی", "location_city", "Good relations with neighbors and community cleanliness."),
    (34, "Parties & Celebrations", "تقریبات اور پارٹیاں", "celebration", "Birthdays, anniversaries, and invitation cards."),
    (35, "Weddings & Traditions", "شادی اور روایات", "favorite", "Mehndi, Barat, Walima, and festive traditions."),
    (36, "Festivals & Holidays (Eid)", "تہوار اور عید کی خوشیاں", "event", "Eid prayers, festive clothes, and holiday feasts."),
    (37, "Clothes & Fashion Style", "لباس اور فیشن", "checkroom", "Dressing style, matching shoes, and traditional wear."),
    (38, "Beauty & Salon Care", "خوبصورتی اور سیلون", "spa", "Haircut, styling, skincare, and salon appointments."),
    (39, "Pets & Animal Care", "پالتو جانور اور دیکھ بھال", "pets", "Cats, dogs, pet food, and veterinary visits."),
    (40, "Nature & Environment", "قدرت اور ماحولیات", "forest", "Trees, mountains, recycling, and climate change."),
    (41, "Freelancing & Remote Work", "فری لانسنگ اور آن لائن کام", "laptop_mac", "Upwork, Fiverr, client proposals, and remote gigs."),
    (42, "University & Higher Studies", "یونیورسٹی اور اعلیٰ تعلیم", "school", "Degree programs, thesis, research, and campus life."),
    (43, "Customer Support & Complaints", "کسٹمر سپورٹ اور شکایات", "support_agent", "Helpline, refunds, faulty products, and service feedback."),
    (44, "Business Negotiation & Deals", "کاروباری سودے بازی", "handshake", "Contracts, profit margins, partnership, and trade."),
    (45, "Telephonic Etiquette", "فون پر بات چیت کے آداب", "phone", "Professional phone calls, leaving voice messages."),
    (46, "Email & Written Communication", "ای میل اور تحریری مواصلات", "mail", "Formal emails, subject lines, and professional attachments."),
    (47, "Conflict Resolution & Politeness", "معاملات سلجھانا اور شائستگی", "handshake", "Resolving disputes peacefully and polite apologies."),
    (48, "Government Offices & Documentation", "سرکاری دفاتر اور دستاویزات", "verified", "CNIC, passport renewal, driving license, and official forms."),
    (49, "Life Advice & Moral Wisdom", "نصیحت اور دانشمندی", "psychology", "Timeless principles, patience, humility, and positive values."),
    (50, "Fluency Practice & Motivation", "روانی اور تحریک", "whatshot", "Daily speaking habits, mastering confidence, and milestone celebration.")
]

print(f"Total topics: {len(topics_definitions)}")
