# -*- coding: utf-8 -*-

def add_9_and_10(topics):
    # 9. Directions & City Navigation
    t9 = [
        ("Excuse me, how can I get to the central train station?", "معاف کیجئے گا، میں ریلوے اسٹیشن کیسے پہنچ سکتا ہوں؟", "Maaf kijiye ga, mein railway station kaisay pohanch sakta hoon?"),
        ("Go straight ahead and take the second turn on your right.", "سیدھا آگے جائیں اور دائیں ہاتھ پر دوسرا موڑ لیں۔", "Seedha aagay jayein aur daayein haath par doosra morr lein."),
        ("Is it within walking distance or should I take a cab?", "کیا یہ پیدل فاصلے پر ہے یا مجھے ٹیکسی لینی چاہیے؟", "Kya yeh paidal faaslay par hai ya mujhe taxi leni chahiye?"),
        ("It is just a five-minute walk around the street corner.", "یہ گلی کے کونے پر صرف پانچ منٹ کے پیدل فاصلے پر ہے۔", "Yeh gali ke konay par sirf paanch minute ke paidal faaslay par hai."),
        ("You will see a large commercial bank on your left side.", "آپ کو بائیں ہاتھ پر ایک بڑا کمرشل بینک نظر آئے گا۔", "Aap ko baayein haath par aik barra commercial bank nazar aaye ga."),
        ("I think we are lost, let us check Google Maps.", "میرے خیال میں ہم راستہ بھول گئے ہیں، گوگل میپس دیکھتے ہیں۔", "Mere khayal mein hum rasta bhool gaye hain, Google Maps dekhtay hain."),
        ("Which bus goes to Liberty Market from here?", "یہاں سے لبرٹی مارکیٹ کے لیے کون سی بس جاتی ہے؟", "Yahan se Liberty Market ke liye kaun si bus jaati hai?"),
        ("Turn left at the traffic signal opposite the hospital.", "ہسپتال کے سامنے ٹریفک سگنل سے بائیں طرف مڑیں۔", "Hospital ke samnay traffic signal se baayein taraf murrein."),
        ("How far is the international airport from this location?", "اس جگہ سے بین الاقوامی ہوائی اڈا کتنی دور ہے؟", "Is jagah se bain-ul-aqwami hawai adda kitni door hai?"),
        ("Thank you very much for guiding me with clear directions.", "مجھے سیدھا راستہ دکھانے کا آپ کا بہت بہت شکریہ۔", "Mujhe seedha rasta dikhanay ka aap ka bohat bohat shukriya."),
        ("Where is the nearest petrol pump or charging station?", "قریب ترین پیٹرول پمپ کہاں ہے؟", "Qareeb tareen petrol pump kahan hai?"),
        ("Drive two kilometers down this main boulevard road.", "اس مین بلیوارڈ روڈ پر دو کلومیٹر آگے تک گاڑی چلائیں۔", "Is main boulevard road par do kilometer aagay tak gaari chalayein."),
        ("Is there a pedestrian overhead bridge to cross the highway?", "کیا سڑک پار کرنے کے لیے پیدل پل موجود ہے؟", "Kya sarak paar karne ke liye paidal pull maujood hai?"),
        ("Yes, the zebra crossing is right in front of the mall.", "جی ہاں، زیبرا کراسنگ بالکل شاپنگ مال کے سامنے ہے۔", "Jee haan, zebra crossing bilkul shopping mall ke samnay hai."),
        ("Can you show me this exact address on the map?", "کیا آپ نقشے پر یہ صحیح پتہ دکھا سکتے ہیں؟", "Kya aap naqshay par yeh sahi pata dikha saktay hain?"),
        ("Take the flyover bridge and stay in the right lane.", "فلائی اوور پر چڑھیں اور دائیں لین میں گاڑی رکھیں۔", "Flyover par charrhein aur daayein lane mein gaari rakhein."),
        ("Where is the metro subway station entrance?", "میٹرو اسٹیشن کا داخلی دروازہ کس طرف ہے؟", "Metro station ka dakhli darwaza kis taraf hai?"),
        ("Walk through the pedestrian underpass to reach the platform.", "پلیٹ فارم تک پہنچنے کے لیے زیر زمین راستے سے جائیں۔", "Platform tak pohanchnay ke liye zair-e-zameen rastay se jayein."),
        ("Is there heavy traffic congestion on the highway today?", "کیا آج موٹروے پر ٹریفک کا شدید رش ہے؟", "Kya aaj motorway par traffic ka shadeed rush hai?"),
        ("Traffic is moving smoothly with no major bottlenecks.", "ٹریفک بغیر کسی رکاوٹ کے بالکل روانی سے چل رہی ہے۔", "Traffic baghair kisi rukawat ke bilkul rawani se chal rahi hai."),
        ("Which exit should I take on the roundabout junction?", "گول چکر (چوراہے) سے مجھے کون سا موڑ لینا چاہیے؟", "Gol chakkar (chaurahay) se mujhe kaun sa morr lena chahiye?"),
        ("Take the third exit toward the university campus.", "یونیورسٹی کیمپس کی طرف تیسرا راستہ لیں۔", "University campus ki taraf teesra rasta lein."),
        ("Is this a one-way street or a two-way road?", "کیا یہ یکطرفہ سڑک ہے یا دونوں طرف سے ٹریفک ہے؟", "Kya yeh yak-tarfa sarak hai ya dono taraf se traffic hai?"),
        ("Be careful, this street is strictly one-way traffic.", "دھیان رہے، یہ گلی مکمل طور پر یکطرفہ ٹریفک کے لیے ہے۔", "Dhiyan rahay, yeh gali mukammal tor par yak-tarfa traffic ke liye hai."),
        ("Where can I find paid underground parking nearby?", "قریب ہی زیر زمین پارکنگ کہاں مل سکتی ہے؟", "Qareeb hi zair-e-zameen parking kahan mil sakti hai?"),
        ("There is a large public plaza parking behind the tower.", "ٹاور کے پیچھے پلازہ کی بڑی پارکنگ موجود ہے۔", "Tower ke peechay plaza ki barri parking maujood hai."),
        ("What is the name of this famous historical landmark?", "اس مشہور تاریخی عمارت یا چوک کا کیا نام ہے؟", "Is mashhoor tareekhi imarat ya chowk ka kya naam hai?"),
        ("This landmark is the famous Badshahi Mosque square.", "یہ مشہور بادشاہی مسجد کا تاریخی چوک ہے۔", "Yeh mashhoor Badshahi Masjid ka tareekhi chowk hai."),
        ("How long does it take to reach downtown by taxi?", "ٹیکسی کے ذریعے شہر کے مرکز تک کتنا وقت لگتا ہے؟", "Taxi ke zariye shehar ke markaz tak kitna waqt lagta hai?"),
        ("It takes around twenty minutes during non-peak hours.", "عام اوقات میں تقریباً بیس منٹ کا وقت لگتا ہے۔", "Aam auqaat mein taqreeban bees minute ka waqt lagta hai."),
        ("Where is the nearest ATM machine to withdraw cash?", "کیش نکالنے کے لیے قریب ترین اے ٹی ایم کہاں ہے؟", "Cash nikaalnay ke liye qareeb tareen ATM kahan hai?"),
        ("There is an ATM right beside the convenience store.", "کریانہ اسٹور کے بالکل ساتھ ایک اے ٹی ایم موجود ہے۔", "Kiryana store ke bilkul sath aik ATM maujood hai."),
        ("You need to take a U-turn at the next traffic light.", "آپ کو اگلے ٹریفک سگنل سے یو ٹرن لینا پڑے گا۔", "Aap ko aglay traffic signal se U-turn lena parray ga."),
        ("Continue driving straight until you reach the clock tower.", "گھنٹہ گھر پہنچنے تک سیدھے چلتے جائیں۔", "Ghanta ghar pohanchnay tak seedhay chaltay jayein."),
        ("The post office is situated behind the central park.", "ڈاک خانہ سینٹرل پارک کے بالکل پیچھے واقع ہے۔", "Daak khana Central Park ke bilkul peechay waqia hai."),
        ("Is it safe to walk around this neighborhood at night?", "کیا رات کے وقت اس علاقے میں پیدل چلنا محفوظ ہے؟", "Kya raat ke waqt is ilaqay mein paidal chalna mahfooz hai?"),
        ("Yes, this residential area is well-lit and secure.", "جی ہاں، یہ رہائشی علاقہ پرامن اور روشن ہے۔", "Jee haan, yeh rehaishi ilaqa pursukoon aur roshan hai."),
        ("Can you point me toward the bus terminal waiting bay?", "کیا آپ بس ٹرمینل کے انتظار گاہ کی طرف اشارہ کر سکتے ہیں؟", "Kya aap bus terminal ke intezar-gah ki taraf ishara kar saktay hain?"),
        ("Follow the blue line painted on the ground pavement.", "فرش پر بنی نیلی لائن کے ساتھ ساتھ چلتے جائیں۔", "Farsh par bani neeli line ke sath sath chaltay jayein."),
        ("Where can I rent a bicycle or electric scooter?", "سائیکل یا الیکٹرک اسکوٹر کرائے پر کہاں سے ملے گا؟", "Cycle ya electric scooter kiraye par kahan se milay ga?"),
        ("There is a rental dock right outside the metro station.", "میٹرو اسٹیشن کے باہر ہی رینٹل اسٹینڈ ہے۔", "Metro station ke bahar hi rental stand hai."),
        ("How do I navigate through the old city alleyways?", "پرانے شہر کی تنگ گلیوں میں راستہ کیسے تلاش کریں؟", "Puranay shehar ki tang galiyon mein rasta kaisay talash karein?"),
        ("Stay on the main bazaar street to avoid getting lost.", "راستہ بھولنے سے بچنے کے لیے مین بازار کے راستے پر رہیں۔", "Rasta bhoolnay se bachnay ke liye main bazaar ke rastay par rahein."),
        ("Is there a tourist information help desk nearby?", "کیا قریب ہی سیاحتی معلومات کا ڈیسک موجود ہے؟", "Kya qareeb hi sayahti maloomat ka desk maujood hai?"),
        ("The tourist information office is inside the municipal hall.", "سیاحتی دفتر میونسپل ہال کی عمارت کے اندر ہے۔", "Sayahti daftar municipal hall ki imarat ke andar hai."),
        ("Keep walking past the library and you will arrive there.", "لائبریری سے آگے بڑھیں تو آپ اپنی منزل پر پہنچ جائیں گے۔", "Library se aagay barhein to aap apni manzil par pohanch jayein ge."),
        ("The destination will be on your immediate right hand.", "آپ کی مطلوبہ جگہ فوراً دائیں ہاتھ پر ہوگی۔", "Aap ki matlooba jagah fauran daayein haath par hogi."),
        ("I really appreciate your kind assistance and help.", "میں آپ کی رہنمائی اور مدد کا دلی شکر گزار ہوں۔", "Mein aap ki rehnumai aur madad ka dili shukarguzar hoon."),
        ("Have a pleasant journey exploring our beautiful city!", "ہمارے خوبصورت شہر کی سیر کا سفر پرلطف گزرے!", "Hamare khubsurat shehar ki sair ka safar pur-lutf guzray!"),
        ("Thank you and take care on the road!", "بہت شکریہ اور راستے میں اپنا خیال رکھیں!", "Bohat shukriya aur rastay mein apna khayal rakhein!")
    ]
    assert len(t9) == 50
    topics.append({
        "id": 9, "name": "Directions & City Navigation", "urduName": "راستہ اور شہر کی رہنمائی", "icon": "explore",
        "desc": "Asking for directions, landmarks, and finding locations.", "sentences": t9
    })

    # 10. Health & Doctor Clinic
    t10 = [
        ("I have had a severe headache and fever since yesterday.", "مجھے کل سے شدید سر درد اور تیز بخار ہے۔", "Mujhe kal se shadeed sar dard aur taiz bukhar hai."),
        ("I would like to book an appointment with Dr. Khan.", "میں ڈاکٹر خان کے ساتھ اپوائنٹمنٹ بک کروانا چاہتا ہوں۔", "Mein Dr. Khan ke sath appointment book karwana chahta hoon."),
        ("How often should I take this antibiotic medicine?", "مجھے یہ اینٹی بائیوٹک دوا کتنی بار لینی چاہیے؟", "Mujhe yeh antibiotic dawa kitni baar leni chahiye?"),
        ("Take one tablet twice a day after meals.", "کھانے کے بعد دن میں دو بار ایک ایک گولی لیں۔", "Khanay ke baad din mein do baar aik aik goli lein."),
        ("Do you experience any pain or swelling in your throat?", "کیا آپ کے گلے میں درد یا سوجن محسوس ہو رہی ہے؟", "Kya aap ke galay mein dard ya sojan mehsoos ho rahi hai?"),
        ("Please lie down on the examination couch.", "برائے مہربانی معائنے والے بیڈ پر لیٹ جائیے۔", "Baraye meharbani muainay walay bed par lait jayiye."),
        ("I will measure your blood pressure and heart rate.", "میں آپ کا بلڈ پریشر اور دل کی دھڑکن چیک کروں گا۔", "Mein aap ka blood pressure aur dil ki dharkan check karunga."),
        ("Are you allergic to any specific medications or food?", "کیا آپ کو کسی خاص دوا یا کھانے سے الرجی ہے؟", "Kya aap ko kisi khaas dawa ya khanay se allergy hai?"),
        ("You need to get a complete blood count test done.", "آپ کو مکمل خون کا ٹیسٹ (سی بی سی) کروانا پڑے گا۔", "Aap ko mukammal khoon ka test (CBC) karwana parray ga."),
        ("Take adequate rest, drink warm fluids, and recover quickly.", "مکمل آرام کریں، گرم مشروبات پئیں، اور جلد صحت یاب ہوں۔", "Mukammal aaram karein, garam mashroobaat piyein, aur jald sehat yaab hon."),
        ("My stomach has been hurting since early morning.", "صبح سے میرے پیٹ میں شدید مروڑ اور درد ہے۔", "Subah se mere pait mein shadeed marorr aur dard hai."),
        ("How long have you been suffering from this cough?", "آپ کو یہ کھانسی کتنے دنوں سے لاحق ہے؟", "Aap ko yeh khansi kitnay dinon se laahaq hai?"),
        ("It started three days ago with mild chest congestion.", "یہ تین دن پہلے ہلکے سینے کے جکڑاؤ سے شروع ہوئی۔", "Yeh teen din pehle halkay seenay ke jakrrao se shuru hui."),
        ("Please open your mouth wide and say 'Aaah'.", "براہ کرم اپنا منہ کھولیں اور 'آہ' کی آواز نکالیں۔", "Barah-e-karam apna munh kholein aur 'Aaah' ki aawaz nikaalein."),
        ("Your throat looks inflamed and infected.", "آپ کا گلا سوجا ہوا اور انفیکشن زدہ معلوم ہوتا ہے۔", "Aap ka gala sooja hua aur infection zada maloom hota hai."),
        ("Do you feel dizzy when you stand up suddenly?", "کیا اچانک کھڑے ہونے پر آپ کو چکر آتے ہیں؟", "Kya achanak kharay honay par aap ko chakkar aatay hain?"),
        ("Drink plenty of water and oral rehydration salts.", "خوب پانی اور او آر ایس (نمکول) کا استعمال کریں۔", "Khoob paani aur ORS (namkol) ka istemal karein."),
        ("Avoid cold drinks, fried items, and oily food.", "ٹھنڈے مشروبات، تلی ہوئی اور چکنائی والی چیزوں سے پرہیز کریں۔", "Thanday mashroobaat, tali hui aur chiknaai wali cheezon se parhez karein."),
        ("I will write a medical prescription for five days.", "میں پانچ دن کی ادویات کا نسخہ لکھ دیتا ہوں۔", "Mein paanch din ki adviyaat ka nuskha likh deta hoon."),
        ("Come back for a follow-up visit on Monday morning.", "پیر کی صبح دوبارہ معائنے کے لیے تشریف لائیں۔", "Peer ki subah dobara muainay ke liye tashreef laayein."),
        ("My back aches whenever I lift heavy objects.", "جب بھی وزنی چیز اٹھاؤں میری کمر میں درد ہوتا ہے۔", "Jab bhi wazni cheez uthaoon meri kamar mein dard hota hai."),
        ("You should maintain proper posture while sitting at a desk.", "کرسی پر بیٹھتے وقت کمر بالکل سیدھی رکھیں۔", "Kursi par baithtay waqt kamar bilkul seedhi rakhein."),
        ("Can you recommend an effective pain relief ointment?", "کیا آپ درد دور کرنے والی کوئی اچھی مرہم تجویز کر سکتے ہیں؟", "Kya aap dard door karne wali koi achi marham tajweez kar saktay hain?"),
        ("Apply this soothing balm gently on the affected area.", "متاثرہ جگہ پر یہ آرام دہ بام ہلکے ہاتھ سے لگائیں۔", "Mutaasira jagah par yeh aaram deh balm halkay haath se lagayein."),
        ("Is the doctor available for emergency consultation right now?", "کیا ڈاکٹر ایمرجنسی میں فوری دیکھنے کے لیے دستیاب ہیں؟", "Kya doctor emergency mein fauri dekhnay ke liye dastiyab hain?"),
        ("The doctor will see you in the emergency room immediately.", "ڈاکٹر آپ کو ایمرجنسی روم میں فوراً دیکھیں گے۔", "Doctor aap ko emergency room mein fauran dekhein ge."),
        ("Please step onto the weighing scale to check weight.", "وزن چیک کرنے کے لیے ترازو پر کھڑے ہو جائیں۔", "Wazan check karne ke liye tarazoo par kharay ho jayein."),
        ("Your body temperature is 101 degrees Fahrenheit.", "آپ کے جسم کا درجہ حرارت 101 فارن ہائیٹ ہے۔", "Aap ke jism ka darja hararat 101 Fahrenheit hai."),
        ("Here is a paracetamol syrup to reduce the high fever.", "بخار کم کرنے کے لیے یہ پیراسیٹامول کا شربت ہے۔", "Bukhar kam karne ke liye yeh paracetamol ka sharbat hai."),
        ("Make sure to finish the full antibiotic course.", "اینٹی بائیوٹک کا پورا کورس مکمل کرنا لازمی ہے۔", "Antibiotic ka poora course mukammal karna laazmi hai."),
        ("Do not stop taking tablets early even if you feel better.", "طبیعت بہتر لگنے پر بھی دوائیں بیچ میں مت چھوڑیں۔", "Tabiat behtar lagnay par bhi dawayein beech mein mat chhorrein."),
        ("I have been feeling constantly exhausted and weak.", "مجھے مسلسل شدید تھکن اور کمزوری محسوس ہو رہی ہے۔", "Mujhe musalsal shadeed thakan aur kamzori mehsoos ho rahi hai."),
        ("You might have a minor vitamin D or iron deficiency.", "آپ میں وٹامن ڈی یا آئرن کی ہلکی سی کمی ہو سکتی ہے۔", "Aap mein Vitamin D ya iron ki halki si kami ho sakti hai."),
        ("Eat fresh green vegetables, fruits, and wholesome milk.", "تازہ ہری سبزیاں، پھل اور خالص دودھ کا استعمال کریں۔", "Taaza hari sabziyan, phal aur khalis doodh ka istemal karein."),
        ("Is fasting required before taking this morning blood test?", "کیا خون کے ٹیسٹ سے پہلے نہار منہ رہنا ضروری ہے؟", "Kya khoon ke test se pehle nihaar munh rehna zaroori hai?"),
        ("Yes, fast for ten to twelve hours before the test.", "جی ہاں، ٹیسٹ سے پہلے دس سے بارہ گھنٹے بھوکے رہیں۔", "Jee haan, test se pehle das se barah ghantay bhookay rahein."),
        ("The lab test report will be ready by tomorrow evening.", "لیبارٹری کی رپورٹ کل شام تک تیار ہو جائے گی۔", "Laboratory ki report kal shaam tak tayar ho jaye gi."),
        ("Your eyesight has changed slightly, you need new glasses.", "آپ کی نظر میں ہلکا فرق آیا ہے، نئی عینک درکار ہے۔", "Aap ki nazar mein halka farq aaya hai, nayi ainak darkaar hai."),
        ("Do regular light exercise and walk thirty minutes daily.", "روزانہ تیس منٹ ہلکی ورزش اور چہل قدمی کریں۔", "Rozana tees minute halki warzish aur chehal-qadmi karein."),
        ("Deep breathing reduces psychological stress and anxiety.", "گہرے سانس لینے سے ذہنی تناؤ اور بے چینی کم ہوتی ہے۔", "Gehray saans lenay se zehni tanao aur bechaini kam hoti hai."),
        ("Please wash and sanitize your hands frequently.", "اپنے ہاتھ بار بار صابن سے دھوئیں اور سینیٹائز کریں۔", "Apne haath baar baar saban se dhoein aur sanitize karein."),
        ("Is it safe for pregnant women to take this capsule?", "کیا حاملہ خواتین کے لیے یہ کیپسول لینا محفوظ ہے؟", "Kya haamla khawateen ke liye yeh capsule lena mahfooz hai?"),
        ("Consult the gynecologist before taking any new pill.", "کوئی بھی نئی دوا لینے سے پہلے لیڈی ڈاکٹر سے رجوع کریں۔", "Koi bhi nayi dawa lenay se pehle lady doctor se rujoo karein."),
        ("The clinic opens at 9 AM and closes at 8 PM.", "کلینک صبح نو بجے کھلتا ہے اور رات آٹھ بجے بند ہوتا ہے۔", "Clinic subah nau bajay khulta hai aur raat aath bajay band hota hai."),
        ("We accept all major health insurance medical cards.", "ہم تمام بڑے ہیلتھ انشورنس کارڈز قبول کرتے ہیں۔", "Hum tamam baray health insurance cards qabool kartay hain."),
        ("My sprained ankle feels much better after the bandage.", "پٹی بندھنے کے بعد ٹخنے کی موچ کا درد کافی کم ہے۔", "Patti bandhnay ke baad takhnay ki moch ka dard kaafi kam hai."),
        ("Keep your foot elevated on a cushion while resting.", "آرام کرتے وقت پاؤں کے نیچے تکیہ رکھ کر اونچا رکھیں۔", "Aaram kartay waqt paon ke neechay takiya rakh kar ooncha rakhein."),
        ("Prevention is always better and cheaper than cure.", "پرہیز اور احتیاط علاج سے ہمیشہ بہتر اور سستا ہے۔", "Parhez aur ahtiyat ilaaj se hamesha behtar aur sasta hai."),
        ("Thank you, doctor, for your caring treatment.", "ڈاکٹر صاحب، آپ کے شفیق اور اچھے علاج کا شکریہ۔", "Doctor sahab, aap ke shafeeq aur achay ilaaj ka shukriya."),
        ("Wishing you good health, vitality, and long life!", "اللہ آپ کو صحت، تندرستی اور لمبی عمر عطا فرمائے!", "Allah aap ko sehat, tandrusti aur lambi umar ata farmaye!")
    ]
    assert len(t10) == 50
    topics.append({
        "id": 10, "name": "Health & Doctor Clinic", "urduName": "صحت اور ڈاکٹر کا کلینک", "icon": "healing",
        "desc": "Explaining symptoms, booking doctor visits, and checkups.", "sentences": t10
    })

print("Part 1 9 and 10 loaded.")
