# -*- coding: utf-8 -*-

def add_28_to_30(topics):
    # 28. Home & Housework
    t28 = [
        ("Keeping the living room organized brings daily tranquility.", "دیوان خانے کو صاف ستھرا رکھنا روزمرہ کے سکون کا باعث بنتا ہے۔", "Deewan-khanay ko saaf suthra rakhna sukoon ka baais banta hai."),
        ("Could you please sweep and mop the tiled floors today?", "کیا آپ برائے مہربانی آج فرش پر جھاڑو اور پونچھا لگا سکتے ہیں؟", "Kya aap baraye meharbani aaj farsh par jhaaroo aur ponchha laga saktay hain?"),
        ("I need to change the bedsheets and pillow covers this morning.", "مجھے آج صبح بستر کی چادریں اور تکیوں کے غلاف تبدیل کرنے ہیں۔", "Mujhe aaj subah bistar ki chaadrein aur takiyon ke ghilaaf tabdeel karne hain."),
        ("The kitchen sink drain is blocked, we must call a plumber.", "باورچی خانے کا نل بند ہو گیا ہے، پلمبر کو بلانا پڑے گا۔", "Bawarchi-khanay ka nal band ho gaya hai, plumber ko bulana parray ga."),
        ("Please hang the wet laundry outside on the rooftop clothesline.", "براہ کرم گیلے کپڑے چھت پر دھوپ میں تار پر ڈال دیں۔", "Barah-e-karam geelay kapray chhat par dhoop mein taar par daal dein."),
        ("Dusting the bookshelves and window blinds prevents allergies.", "کتابوں اور کھڑکیوں کی مٹی صاف کرنے سے الرجی سے بچاؤ رہتا ہے۔", "Kitabon aur khirkiyon ki mitti saaf karne se allergy se bachao rehta hai."),
        ("We should declutter the attic and donate unused clothes.", "ہمیں اسٹور روم کی فالتو چیزیں اور پرانے کپڑے خیرات کرنے چاہییں۔", "Humein store room ki faaltu cheezon aur kapray khairat karne chahiyein."),
        ("The ceiling fan needs cleaning before the summer season arrives.", "گرمیوں کی آمد سے پہلے چھت کے پنکھوں کی صفائی ضروری ہے۔", "Garmiyon ki aamad se pehle chhat ke pankhon ki safaai zaroori hai."),
        ("Remember to turn off all electrical switches before leaving home.", "گھر سے نکلتے وقت تمام بجلی کے بٹن بند کرنا یاد رکھیں۔", "Ghar se nikaltay waqt bijli ke tamam button band karna yaad rakhein."),
        ("A clean and fragrant home welcomes angelic blessings and peace.", "صاف ستھرا اور خوشبودار گھر برکتوں اور سکون کا گہوارہ ہوتا ہے۔", "Saaf suthra aur khushbodaar ghar barkaton aur sukoon ka gehwara hota hai."),
        ("Where did you place the vacuum cleaner and spare bags?", "آپ نے ویکیوم کلینر اور اس کے فالتو بیگز کہاں رکھے ہیں؟", "Aap ne vacuum cleaner aur us ke faaltu bags kahan rakhay hain?"),
        ("I will vacuum the living room carpets thoroughly this afternoon.", "میں آج دوپہر کو دیوان خانے کے قالینوں کو ویکیوم کروں گا۔", "Mein aaj dopahar ko deewan-khanay ke qaleenon ko vacuum karunga."),
        ("Please wipe down the dining table after finishing lunch.", "دوپہر کے کھانے کے بعد کھانے کی میز کو کپڑے سے صاف کر دیں۔", "Dopahar ke khanay ke baad khanay ki maiz ko saaf kar dein."),
        ("The bathroom mirror has water stains; use glass cleaner.", "باتھ روم کے شیشے پر داغ ہیں، شیشہ صاف کرنے والا اسپرے استعمال کریں۔", "Bathroom ke sheeshay par daagh hain, glass cleaner spray istemal karein."),
        ("We need to replace the burnt-out LED bulb in the hallway.", "راہداری میں فیوز ہوا ایل ای ڈی بلب تبدیل کرنے کی ضرورت ہے۔", "Rahdari mein fuse hua LED bulb tabdeel karne ki zaroorat hai."),
        ("Empty the kitchen waste bin and tie the garbage bag securely.", "باورچی خانے کا کوڑے دان خالی کر کے کچرے کے تھیلے کو گرہ لگائیں۔", "Bawarchi-khanay ka kooradan khaali kar ke thelay ko girah lagayein."),
        ("Keep toxic cleaning chemicals locked away from small children.", "صفائی والے کیمیکلز کو چھوٹے بچوں کی پہنچ سے ہمیشہ دور رکھیں۔", "Safaai walay chemicals ko bachon ki pohanch se hamesha door rakhein."),
        ("The front garden lawn needs mowing and fresh watering.", "سامنے والے لان کی گھاس کاٹنے اور پودوں کو پانی دینے کی ضرورت ہے۔", "Samnay walay lawn ki ghaas kaatnay aur paani denay ki zaroorat hai."),
        ("Please water the potted plants on the balcony every evening.", "شام کے وقت بالکونی کے گملوں کو روزانہ پانی دیں۔", "Shaam ke waqt balcony ke gamlon ko rozana paani dein."),
        ("Organizing your wardrobe by color makes finding clothes effortless.", "الماری میں کپڑوں کو رنگ کے لحاظ سے ترتیب دینا آسان بنا دیتا ہے۔", "Almari mein kapron ko rang ke lehaaz se tarteeb dena aasan banata hai."),
        ("The washing machine finished the spin cycle; hang the clothes.", "واشنگ مشین نے اسپن کا مرحلہ مکمل کر لیا ہے، کپڑے لٹکا دیں۔", "Washing machine ne spin mukammal kar liya hai, kapray latka dein."),
        ("Iron the school uniforms and hang them in the kids' closet.", "اسکول کی وردیوں کو استری کر کے بچوں کی الماری میں لٹکا دیں۔", "School ki wardiyon ko istri kar ke bachon ki almari mein latka dein."),
        ("We should inspect the rooftop for any rainwater leakage signs.", "ہمیں بارش کے پانی کے رساؤ کی جانچ کے لیے چھت چیک کرنی چاہیے۔", "Humein barish ke paani ke rasao ke liye chhat check karni chahiye."),
        ("Fixing minor home repairs early prevents major costly damages.", "گھر کے چھوٹے نقائص جلد ٹھیک کرنا بڑے نقصانات سے بچاتا ہے۔", "Ghar ke chhotay nuqais jald theek karna baray nuqsan se bachata hai."),
        ("Please scrub the kitchen stove burners with soapy water.", "چولہے کے برنرز کو صابن والے گرم پانی سے اچھی طرح رگڑیں۔", "Choolhay ke burners ko saban walay paani se achi tarah ragrein."),
        ("The refrigerator needs defrosting and a thorough wipe down.", "فریج کو ڈی فراسٹ کر کے اندر سے مکمل صاف کرنے کی ضرورت ہے۔", "Fridge ko defrost kar ke andar se mukammal saaf karne ki zaroorat hai."),
        ("Check the pantry for expired spices and canned goods.", "اسٹور میں پرانے مصالحہ جات اور ایکسپائرڈ ڈبوں کی جانچ کریں۔", "Store mein puranay masalajat aur expired dabbon ki jaanch karein."),
        ("Air out the bedrooms by opening windows for fresh air.", "کمروں کی کھڑکیاں کھول کر تازہ ہوا کو اندر آنے دیں۔", "Kamron ki khirkiyan khol kar taaza hawa ko andar aanay dein."),
        ("Use baking soda and vinegar to clear mild sink blockages.", "سنک کی ہلکی بندش دور کرنے کے لیے بیکنگ سوڈا اور سرکہ ڈالیں۔", "Sink ki bandish door karne ke liye baking soda aur sirka daalein."),
        ("A well-kept house brings health, happiness, and peace of mind.", "سلیقے سے سنبھالا ہوا گھر صحت، خوشی اور ذہنی سکون لاتا ہے۔", "Saleeqay se sambhala hua ghar sehat aur zehni sukoon laata hai."),
        ("Can you help me assemble this new wooden shoe rack?", "کیا آپ جوتوں کا یہ نیا لکڑی کا ریک جوڑنے میں میری مدد کریں گے؟", "Kya aap jooton ka yeh naya lakri ka rack jorrnay mein madad karein ge?"),
        ("Tighten the loose screw on the bedroom door handle.", "کمرے کے دروازے کے ہینڈل کا ڈھیلا پیچ کس دیں۔", "Kamray ke darwazay ke handle ka dheela paich kas dein."),
        ("Please organize the shoe cabinet near the front entrance.", "مین گیٹ کے پاس جوتوں کی الماری کو سلیقے سے ترتیب دیں۔", "Main gate ke paas jooton ki almari ko saleeqay se tarteeb dein."),
        ("We should wash the window curtains before the festive Eid holiday.", "عید سے پہلے ہمیں کھڑکیوں کے پردے دھو لینے چاہییں۔", "Eid se pehle humein khirkiyon ke parday dho lenay chahiyein."),
        ("Keep fire safety blankets and first aid boxes easily accessible.", "فرسٹ ایڈ بکس کو ایسی جگہ رکھیں جہاں سے باآسانی مل سکے۔", "First aid box ko aisi jagah rakhein jahan se ba-aasani mil sakay."),
        ("The water motor tank is full; turn off the main pump.", "پانی کی ٹینکی بھر گئی ہے، موٹر کا سوئچ بند کر دیں۔", "Paani ki tanki bhar gayi hai, motor ka switch band kar dein."),
        ("Clean the air filter meshes of the split AC units monthly.", "اسپلٹ اے سی کی جالیاں ہر مہینے صاف کرنا لازمی ہے۔", "Split AC ki jaaliyan har maheenay saaf karna laazmi hai."),
        ("Sweep the front porch driveway to remove fallen autumn leaves.", "خزاں کے گرے ہوئے سوکھے پتے ہٹانے کے لیے صحن میں جھاڑو دیں۔", "Khizan ke giray hue pattay hatanay ke liye sehan mein jhaaroo dein."),
        ("Check the smoke detectors and replace batteries when chirping.", "دھواں جانچنے والے آلات کی بیٹریاں باقاعدگی سے چیک کریں۔", "Dhuwan jaanchne walay aalaat ki batteries check karein."),
        ("Sharing household chores equally creates family harmony.", "گھر کے کام مل بانٹ کر کرنے سے محبت اور یگانگت بڑھتی ہے۔", "Ghar ke kaam mil baant kar karne se mohabbat barhti hai."),
        ("Please fold the clean dry laundry and put it in wardrobes.", "خشک کپڑوں کی تہہ لگا کر انہیں الماریوں میں رکھ دیں۔", "Khushk kapron ki teh laga kar unhein almariyon mein rakh dein."),
        ("Wipe the microwave interior with lemon steam to remove odors.", "مائیکروویو سے بو ختم کرنے کے لیے لیموں کے پانی کی بھاپ دیں۔", "Microwave se boo khatam karne ke liye neembu ke paani ki bhaap dein."),
        ("Scrub the bathroom floor tiles with disinfectant cleaner.", "باتھ روم کے فرش کی ٹائلوں کو جراثیم کش دوا سے دھوئیں ہے۔", "Bathroom ke farsh ki tiles ko jaraseem-kush dawa se dhoein."),
        ("Check that the main gas cylinder valve is tightly shut at night.", "رات کو چیک کریں کہ گیس کا مین والو اچھی طرح بند ہو۔", "Raat ko check karein ke gas ka main valve achi tarah band ho."),
        ("Keep spare keys in a secure, designated key box.", "اضافی چابیاں ہمیشہ ایک محفوظ اور طے شدہ ڈبے میں رکھیں۔", "Izafi chaabiyan hamesha aik mahfooz dabbay mein rakhein."),
        ("Polishing wooden furniture restores its natural rich luster.", "لکڑی کے فرنیچر کو پالش کرنے سے اس کی چمک لوٹ آتی ہے۔", "Lakri ke furniture ko polish karne se us ki chamak laut aati hai."),
        ("Teach children to put away their toys after playtime.", "کھیل کے بعد بچوں کو کھلونے سنبھال کر رکھنے کی عادت ڈالیں۔", "Khel ke baad bachon ko khilaunay sambhal kar rakhnay ki aadat daalein."),
        ("A tidy physical environment fosters a calm, focused mind.", "صاف ستھرا ماحول انسان کے ذہن کو پرسکون اور یکسو رکھتا ہے۔", "Saaf suthra mahaul insaan ke zehan ko pursukoon rakhta hai."),
        ("Thank you for your tireless dedication to maintaining our home.", "ہمارے گھر کو سنوارنے اور سنبھالنے پر آپ کا تہہ دل سے شکریہ۔", "Hamare ghar ko sanwarnay par aap ka teh-e-dil se shukriya."),
        ("May our home always remain a haven of peace, love, and light!", "اللہ کرے ہمارا گھر ہمیشہ امن، محبت اور سکون کا گہوارہ رہے!", "Allah karay hamara ghar hamesha aman aur sukoon ka gehwara rahay!")
    ]
    topics.append({
        "id": 28, "name": "Home & Housework", "urduName": "گھر اور گھریلو امور", "icon": "home",
        "desc": "Cleaning, household chores, organization, and repairs.", "sentences": t28
    })

    # 29. Kitchen & Cooking
    t29 = [
        ("What ingredients do we need for preparing traditional Biryani?", "روایتی بریانی بنانے کے لیے ہمیں کن اجزاء کی ضرورت ہے؟", "Riwayati biryani bananay ke liye humein kin ajza ki zaroorat hai?"),
        ("Finely slice three medium onions and sauté until golden brown.", "تین پیاز باریک کاٹیں اور سنہری ہونے تک تیل میں تلیں۔", "Teen pyaaz bareek kaatein aur sunehri honay tak tail mein talein."),
        ("Add freshly crushed ginger and garlic paste to the hot oil.", "گرم تیل میں تازہ پسا ہوا ادرک اور لہسن کا پیسٹ شامل کریں۔", "Garam tail mein taaza pisa hua adrak aur lehsan ka paste shamil karein."),
        ("Let the spicy chicken gravy simmer gently on low flame.", "چکن کے مصالحے والے سالن کو ہلکی آنچ پر دم پر پکنے دیں۔", "Chicken ke masalay walay salan ko halki aanch par dam par paknay dein."),
        ("Boil the fragrant Basmati rice until it is ninety percent cooked.", "خوشبودار باسمتی چاولوں کو نوے فیصد گلنے تک ابالیں۔", "Khushbodaar basmati chawal ko 90 feesad galnay tak ubaalein."),
        ("Layer the rice over the meat sauce and garnish with fresh mint.", "گوشت کے سالن پر چاول کی تہہ لگائیں اور پودینہ چھڑکیں۔", "Gosht ke salan par chawal ki teh lagayein aur podeena chhirrkein."),
        ("Cover the pot with a tight lid and steam for fifteen minutes.", "پتیلی کو ڈھکن سے ڈھانپ کر پندرہ منٹ کے لیے دم پر رکھیں۔", "Pateli ko dhakkan se dhaanp kar 15 minute ke liye dam par rakhein."),
        ("The aroma of cardamom, cloves, and saffron fills the whole house.", "الائچی، لونگ اور زعفران کی خوشبو پورے گھر میں مہک اٹھی۔", "Elaichi, laung aur zafran ki khushboo pooray ghar mein mehak uthi."),
        ("Always wash and drain vegetables thoroughly before chopping.", "سبزیوں کو کاٹنے سے پہلے ہمیشہ اچھی طرح دھو کر خشک کریں۔", "Sabziyon ko kaatnay se pehle hamesha achi tarah dho kar khushk karein."),
        ("Home cooking made with genuine love nourishes body and soul.", "محبت اور خلوص سے پکا ہوا گھریلو کھانا جسم و جاں کو تقویت دیتا ہے۔", "Mohabbat se paka hua gharelu khana jism-o-jaan ko taqwiyat deta hai."),
        ("How many teaspoons of sea salt should I add to the dough?", "آٹے میں سمندری نمک کے کتنے چمچ ڈالنے چاہییں؟", "Aatay mein samandari namak ke kitnay chamach daalnay chahiyein?"),
        ("Knead the wheat flour dough until it becomes soft and pliable.", "گندم کے آٹے کو اس وقت تک گوندھیں جب تک وہ نرم و ملائم نہ ہو جائے۔", "Gandum ke aatay ko narm-o-mulaem honay tak goondhein."),
        ("Use a heavy cast-iron tawa to make crispy puffed rotis.", "پھولی ہوئی کرسپی روٹیوں کے لیے بھاری لوہے کا توا استعمال کریں۔", "Phooli hui rotiyon ke liye bhaari lohay ka tawa istemal karein."),
        ("Soak kidney beans and chickpeas overnight before pressure cooking.", "لوبیا اور چنوں کو پریشر ککر میں پکانے سے پہلے رات بھر بھگوئیں۔", "Lobia aur chanon ko cooker mein pakanay se pehle raat bhar bhigoein."),
        ("Be very cautious when opening the steam valve on pressure cooker.", "پریشر ککر کا سیفٹی والو کھولتے وقت انتہائی احتیاط برتیں۔", "Pressure cooker ka safety valve kholtay waqt ahtiyat bartein."),
        ("Sharpen your stainless steel chef knives regularly for safety.", "حفاظت اور آسانی کے لیے چھریوں کی دھار باقاعدگی سے تیز رکھیں۔", "Hifazat ke liye chhuriyon ki dhaar baqaidgi se taiz rakhein."),
        ("Marinate mutton chops with raw papaya paste for tender texture.", "گوشت کو نرم کرنے کے لیے کچے پپیتے کے پیسٹ سے میرینیٹ کریں۔", "Gosht ko narm karne ke liye kachay papeetay se marinate karein."),
        ("Grind whole spices like cumin, coriander, and black pepper fresh.", "ثابت زیرہ، دھنیا اور کالی مرچ تازہ پیس کر استعمال کریں۔", "Saabit zeera, dhania aur kaali mirch taaza pees kar istemal karein."),
        ("Freshly ground spices impart an incomparable depth of flavor.", "تازہ پسے ہوئے مصالحہ جات کھانے کے ذائقے کو چار چاند لگا دیتے ہیں۔", "Taaza pisay hue masalajaat khanay ke zaiqay ko chaar chaand laga detay hain."),
        ("Store dry pantry lentils and grains in airtight glass jars.", "دالوں اور اناج کو ہوا بند شیشے کے جار میں محفوظ رکھیں۔", "Daalon aur anaaj ko hawa-band shishay ke jar mein rakhein."),
        ("Can you whisk the eggs and milk together for morning omelets?", "کیا آپ ناشتے کے آملیٹ کے لیے انڈے اور دودھ پھینٹ سکتے ہیں؟", "Kya aap nashtay ke omelette ke liye anday aur doodh phaint saktay hain?"),
        ("Gently caramelize red onions in clarified pure desi ghee.", "خالص دیسی گھی میں سرخ پیاز کو ہلکی آنچ پر سنہری کریں۔", "Khalis desi ghee mein surkh pyaaz ko halki aanch par sunehri karein."),
        ("Simmer fresh whole milk on low heat to prepare creamy Kheer.", "گاڑھی کھیر بنانے کے لیے خالص دودھ کو ہلکی آنچ پر کڑھائیں۔", "Gaarhi kheer bananay ke liye khalis doodh ko halki aanch par karhayein."),
        ("Garnish the sweet halwa with sliced almonds and pistachios.", "حلوے کو کٹے ہوئے باداموں اور پستے سے خوبصورتی سے سجائیں۔", "Halway ko katay hue badaamon aur pistay se sajayein."),
        ("Do not overheat extra virgin olive oil to preserve antioxidants.", "زیتون کے تیل کو زیادہ تیز آنچ پر مت جلائیں۔", "Zaitoon ke tail ko zyada taiz aanch par mat jalayein."),
        ("Use a wooden spatula to avoid scratching non-stick frying pans.", "نان اسٹک برتنوں میں خراشوں سے بچنے کے لیے لکڑی کا چمچ چلائیں۔", "Non-stick bartanon mein lakri ka chamach chalayein."),
        ("Bake the moist sponge cake at 180 degrees Celsius for 30 minutes.", "کیک کو ایک سو اسی ڈگری پر تیس منٹ کے لیے بیک کریں۔", "Cake ko 180 degree par 30 minute ke liye bake karein."),
        ("Check cake doneness by inserting a clean wooden toothpick.", "کیک کی تیاری چیک کرنے کے لیے صاف خلال اندر داخل کر کے دیکھیں۔", "Cake ki tayari check karne ke liye saaf khilal daal kar dekhein."),
        ("Let the freshly baked bread cool completely on a wire rack.", "تازہ پکی ہوئی روٹی یا کیک کو جالی والے اسٹینڈ پر ٹھنڈا ہونے دیں۔", "Taaza paki bread ya cake ko jaali par thanda honay dein."),
        ("A pinch of turmeric adds vibrant golden color and immunity.", "ایک چٹکی ہلدی کھانے کو دلکش رنگ اور قوت مدافعت دیتی ہے۔", "Aik chutki haldi khanay ko dilkash rang aur sehat bakhshti hai."),
        ("Roast raw peanuts and sesame seeds in a dry pan until fragrant.", "مونگ پھلی اور تلوں کو خشک پین میں ہلکا سا بھون لیں۔", "Moong phalli aur tilon ko khushk pan mein halka sa bhoon lein."),
        ("Grind fresh green chilies, mint leaves, and coriander for chutney.", "ہری مرچ، پودینہ اور ہرا دھنیا پیس کر لذیذ چٹنی تیار کریں۔", "Hari mirch, podeena aur hara dhania pees kar chutney banayein."),
        ("Squeeze fresh tart lemon juice over grilled fish and tikka.", "بھنی ہوئی مچھلی اور چکن تکہ پر تازہ لیموں کا رس نچوڑیں۔", "Bhuni hui machhli aur chicken tikka par taaza neembu nachorrein."),
        ("Store leftover food in glass containers inside the refrigerator.", "بچا ہوا کھانا شیشے کے ڈبوں میں بند کر کے فریج میں رکھیں۔", "Bacha hua khana shishay ke dabbon mein band kar ke fridge mein rakhein."),
        ("Never leave raw chicken and fresh salad on the same cutting board.", "کچا گوشت اور سلاد کبھی بھی ایک ہی تختے پر مت کاٹیں۔", "Kacha gosht aur salad kabhi aik hi takhtay par mat kaatein."),
        ("Maintain highest standards of kitchen hygiene and handwashing.", "باورچی خانے کی صفائی اور ہاتھ دھونے کا ہمیشہ اعلیٰ معیار رکھیں۔", "Bawarchi-khanay ki safaai aur haath dhonay ka aala meyaar rakhein."),
        ("Make sure all kitchen appliance plugs are safely insulated.", "تمام برقی آلات کی تاروں کے محفوظ ہونے کی تسلی کر لیں۔", "Tamam barqi aalaat ki taaron ke mahfooz honay ki tasalli karein."),
        ("A warm bowl of homemade chicken corn soup cures cold.", "گھر کا بنا گرم چکن کارن سوپ نزلہ زکام کا بہترین علاج ہے۔", "Ghar ka bana garam chicken corn soup nazlay ka behtareen ilaaj hai."),
        ("Making round, thin rotis takes regular practice and patience.", "گول اور پتلی روٹیاں بنانا مسلسل مشق اور توجہ مانگتا ہے۔", "Gol aur patli rotiyan banana musalsal mashq maangta hai."),
        ("Cooking brings families together around the dinner table.", "کھانا پکانا پورے خاندان کو دسترخوان پر ایک ساتھ جوڑتا ہے۔", "Khana pakana pooray khandan ko dastarkhwan par jorta hai."),
        ("Can you peel and grate four large carrots for Gajar Halwa?", "کیا آپ گاجر کے حلوے کے لیے چار گاجریں چھیل کر کدوکش کر دیں گے؟", "Kya aap gajar ke halway ke liye gajrein cheel kar kadookash karein ge?"),
        ("Sauté garlic until fragrant before adding fresh spinach leaves.", "پالک شامل کرنے سے پہلے لہسن کو خوشبو آنے تک ہلکا سا تلیں۔", "Palak shamil karne se pehle lehsan ko halka sa talein."),
        ("Keep your kitchen countertops wiped clean and grease-free.", "باورچی خانے کے سلیب کو ہمیشہ صاف اور چکنائی سے پاک رکھیں۔", "Bawarchi-khanay ke slab ko hamesha chiknaai se paak rakhein."),
        ("Use potholders or silicone oven mitts when touching hot pans.", "گرم برتن چھوتے وقت کپڑے یا اوون دستانے کا استعمال کریں۔", "Garam bartan chhootay waqt oven dastaanay ka istemal karein."),
        ("Allow the meat stew to rest for ten minutes before serving.", "کھانا پیش کرنے سے پہلے سالن کو دس منٹ کے لیے ڈھانپ کر رکھیں۔", "Khana pesh karne se pehle salan ko 10 minute dhaanp kar rakhein."),
        ("Cooking is both an exacting science and a heartfelt art.", "کھانا پکانا ایک سائنسی مہارت بھی ہے اور دل سے کیا جانے والا فن بھی۔", "Khana pakana aik sciensi maharat bhi hai aur dil ka fann bhi."),
        ("Experimenting with new regional recipes broadens culinary skills.", "نئے کھانوں کے تجربات آپ کے کوکنگ کے ہنر کو نکھارتے ہیں۔", "Naye khanon ke tajrubat aap ke cooking ke hunar ko nikhartay hain."),
        ("Nothing compares to the comforting taste of mother's recipes.", "ماں کے ہاتھ کے پکے کھانوں کے ذائقے کا کوئی نعم البدل نہیں۔", "Maa ke haath ke pakay khanon ke zaiqay ka koi saani nahi."),
        ("May your kitchen always overflow with sustenance, warmth, and joy!", "اللہ کرے آپ کا باورچی خانہ ہمیشہ رزقِ حلال اور برکتوں سے بھرا رہے!", "Allah karay aap ka bawarchi-khana hamesha rizq aur barkat se bhara rahay!")
    ]
    topics.append({
        "id": 29, "name": "Kitchen & Cooking", "urduName": "باورچی خانہ اور کھانا پکانا", "icon": "restaurant",
        "desc": "Cooking methods, spices, cookware, and recipes.", "sentences": t29
    })

    # 30. Groceries & Supermarket
    t30 = [
        ("Where can I find organic fresh fruits and crisp vegetables?", "مجھے تازہ پھل اور ہری سبزیاں کس طرف ملیں گی؟", "Mujhe taaza phal aur hari sabziyan kis taraf milein gi?"),
        ("Are these farm-fresh eggs free-range or organic?", "کیا یہ دیسی انڈے قدرتی اور نامیاتی فارم کے ہیں؟", "Kya yeh desi anday qudrati aur namiyati farm ke hain?"),
        ("I need a five-kilogram sack of whole wheat flour.", "مجھے چکی کے پسے ہوئے آٹے کا پانچ کلو کا تھیلا چاہیے۔", "Mujhe chakki ke pisay aatay ka 5 kilo ka thela chahiye."),
        ("Where is the dairy aisle for yogurt, butter, and cheese?", "دہی، مکھن اور پنیر کا ڈیری سیکشن کہاں واقع ہے؟", "Dahi, makkhan aur paneer ka dairy section kahan waqia hai?"),
        ("Please weigh two kilograms of sweet Sindhri mangoes.", "سندھڑی آم کے دو کلو وزن کر کے تول دیں۔", "Sindhri aam ke do kilo wazan kar ke tol dein."),
        ("Is there a special promotional discount on cooking oil today?", "کیا آج کھانا پکانے کے تیل پر کوئی خصوصی رعایت ہے؟", "Kya aaj cooking oil par koi khusoosi riayat hai?"),
        ("Could you please tell me which aisle has whole spices?", "کیا آپ بتا سکتے ہیں کہ ثابت مصالحہ جات کس قطار میں ہیں؟", "Kya aap bata saktay hain ke saabit masalajat kis qitaar mein hain?"),
        ("Check the production and expiration dates printed on carton.", "ڈبے پر لکھی تیاری اور ایکسپائری کی تاریخیں ضرور چیک کریں۔", "Dabbay par likhi tayari aur expiry ki tareekhein zaroor check karein."),
        ("I will take three liters of full cream pasteurized milk.", "میں تین لیٹر خالص پاسچرائزڈ فل کریم دودھ لوں گا۔", "Mein teen liter khalis pasteurized full cream doodh loonga."),
        ("Always prepare a written shopping checklist before visiting store.", "اسٹور جانے سے پہلے خریداری کی فہرست ہمیشہ پہلے تیار کریں۔", "Store jaanay se pehle khareedari ki fehrist hamesha pehle tayar karein."),
        ("Do you sell organic unprocessed raw blossom honey?", "کیا آپ کے پاس خالص جنگلی پھولوں کا کچا شہد موجود ہے؟", "Kya aap ke paas khalis jungli phoolon ka kacha shehad hai?"),
        ("Where are the hygiene items, dishwashing soap, and detergents?", "صابن، سرف اور برتن دھونے کا سامان کس قطار میں ہے؟", "Saban, surf aur bartan dhonay ka saman kis qitaar mein hai?"),
        ("Are these imported breakfast cereals sugar-free and gluten-free?", "کیا یہ امپورٹڈ سیریل چینی اور گلوٹین سے پاک ہیں؟", "Kya yeh imported cereals cheeni aur gluten se paak hain?"),
        ("Please give me half a kilogram of fresh minced beef.", "براہ کرم مجھے آدھا کلو تازہ گائے کا قیمہ بنا کر دیں۔", "Barah-e-karam mujhe aadha kilo taaza gaye ka qeema bana kar dein."),
        ("Can you slice this whole block of cheddar cheese thinly?", "کیا آپ چیز کے اس ٹکڑے کے باریک سلائس کاٹ سکتے ہیں؟", "Kya aap cheese ke is tukray ke bareek slice kaat saktay hain?"),
        ("Where can I find biodegradable, eco-friendly shopping bags?", "ماحول دوست کاغذی تھیلے کہاں سے مل سکتے ہیں؟", "Mahool dost kaghazi thelay kahan se mil saktay hain?"),
        ("This shopping trolley has a jammed wheel; let me swap it.", "اس شاپنگ ٹرالی کا پہیہ پھنس رہا ہے، میں دوسری لے لیتا ہوں۔", "Is shopping trolley ka pahiya phans raha hai, mein doosri le leta hoon."),
        ("Do you have pure olive oil suitable for deep salad dressing?", "کیا سلاد پر ڈالنے کے لیے ایکسٹرا ورجن زیتون کا تیل ہے؟", "Kya salad par daalnay ke liye extra virgin zaitoon ka tail hai?"),
        ("The produce in this section is sourced directly from local farms.", "اس سیکشن کی تمام سبزیاں مقامی فارموں سے تازہ منگوائی گئی ہیں۔", "Is section ki sabziyan maqami farmon se taaza mangwayi gayi hain."),
        ("Is there any express cash counter for five items or fewer?", "کیا پانچ یا اس سے کم اشیاء کے لیے الگ ایکسپریس کاؤنٹر ہے؟", "Kya 5 ya us se kam ashya ke liye alag express counter hai?"),
        ("Please put the fragile glass bottles in a separate carrier bag.", "شیشے کی نازک بوتلیں الگ تھیلے میں ڈال کر دیں۔", "Sheeshay ki naazuk botalain alag thelay mein daal kar dein."),
        ("Do you accept digital wallet payments via smartphone apps?", "کیا آپ موبائل ایپس اور ڈیجیٹل والٹ سے ادائیگی لیتے ہیں؟", "Kya aap mobile apps aur digital wallet se payment letay hain?"),
        ("The cash register gave me an itemized printed receipt.", "کیش کاؤنٹر نے مجھے تمام اشیاء کی تفصیل والی رسید دی۔", "Cash counter ne mujhe tamam ashya ki tafseel wali raseed di."),
        ("Keep your receipt in case you need to return any sealed items.", "اگر کوئی چیز تبدیل کروانی ہو تو رسید سنبھال کر رکھیں۔", "Agar koi cheez tabdeel karwani ho to raseed sambhal kar rakhein."),
        ("Where is the bakery counter for freshly baked bread and buns?", "تازہ بیکری کی ڈبل روٹی اور بنز کا کاؤنٹر کس طرف ہے؟", "Taaza bakery ki double roti aur buns ka counter kis taraf hai?"),
        ("These fresh strawberries and apples smell wonderfully sweet.", "یہ تازہ اسٹرابری اور سیب بہت خوشبودار اور میٹھے ہیں۔", "Yeh taaza strawberry aur saib bohat meethay hain."),
        ("Do you sell green tea leaves and herbal chamomile tea?", "کیا آپ کے پاس کھلی سبز چائے کی پتی اور قہوہ موجود ہے؟", "Kya aap ke paas sabz chaye ki patti aur qahwa hai?"),
        ("Buying seasonal vegetables saves money and guarantees top nutrition.", "موسمی سبزیاں خریدنا سستا بھی ہوتا ہے اور غذائیت سے بھرپور بھی۔", "Mausami sabziyan khareedna sasta bhi hota hai aur sehat-bakhsh bhi."),
        ("Check the seal on the cooking oil bottle before placing in cart.", "تیل کی بوتل ٹرالی میں رکھنے سے پہلے اس کی مہر ضرور دیکھ لیں۔", "Tail ki botal trolley mein rakhnay se pehle seal zaroor dekh lein."),
        ("Plan your weekly meals to minimize household food wastage.", "کھانے کا ضیاع روکنے کے لیے پورے ہفتے کے کھانوں کی منصوبہ بندی کریں۔", "Khanay ka ziyaa roknay ke liye haftay ke khanon ka plan banayein."),
        ("Where can I find frozen seafood, fish fillets, and prawns?", "فروزن مچھلی اور جھینگے کس فریزر میں رکھے ہیں؟", "Frozen machhli aur jheengay kis freezer mein rakhay hain?"),
        ("This store offers a five percent loyalty reward to members.", "یہ اسٹور کارڈ ممبرز کو پانچ فیصد کی خصوصی رعایت دیتا ہے۔", "Yeh store card members ko 5 feesad ki riayat deta hai."),
        ("Please bring me a head of fresh broccoli and a bunch of spinach.", "ایک تازہ بند گوبھی یا بروکولی اور پالک کی گٹھی لا دیں۔", "Aik taaza band gobhi ya broccoli aur palak ki gutthi laa dein."),
        ("Are these canned kidney beans already boiled and salted?", "کیا کین میں بند لوبیا پہلے سے ابلا ہوا ہے؟", "Kya can mein band lobia pehle se ubla hua hai?"),
        ("Rinse canned beans under tap water before adding to salads.", "سلاد میں شامل کرنے سے پہلے ڈبے والے دانوں کو پانی سے دھو لیں۔", "Salad mein daalnay se pehle dabbi walay danon ko dho lein."),
        ("Do you have crushed whole oats for healthy breakfast porridge?", "کیا ناشتے کے لیے بغیر چینی والا دلیہ (اوٹس) موجود ہے؟", "Kya nashtay ke liye baghair cheeni wala daliya (oats) hai?"),
        ("Where can I find pure almond milk and soya bean milk?", "بادام کا دودھ اور سویا ملک کہاں رکھا ہوا ہے؟", "Badaam ka doodh aur soya milk kahan rakha hua hai?"),
        ("Please ensure the egg carton has no cracked or damaged eggs.", "دیکھ لیں کہ انڈوں کے ڈبے میں کوئی انڈا ٹوٹا ہوا نہ ہو۔", "Dekh lein ke andon ke dabbay mein koi anda toota hua na ho."),
        ("We should buy pantry staples in bulk to take advantage of sales.", "بچت کے لیے دالیں اور آٹا سیل کے دوران اکٹھا خریدنا چاہیے۔", "Bachat ke liye daalein aur aata sale ke dauran ikattha khareedna chahiye."),
        ("The store staff was courteous and assisted in finding items.", "اسٹور کا عملہ بہت شائستہ تھا اور چیزیں تلاش کرنے میں مدد کی۔", "Store ka amla bohat shaista tha aur cheezon mein madad ki."),
        ("Can you help me reach that cereal box on the top shelf?", "کیا اوپر والے خانے سے وہ سیریل کا ڈبہ اتارنے میں مدد کریں گے؟", "Kya ooper walay khanay se woh serial ka dabba utaarein ge?"),
        ("Place the heavy melon and oil cans at the bottom of the cart.", "بھاری خربوزہ اور تیل کے کین ٹرالی کے نچلے حصے میں رکھیں۔", "Bhaari kharbooza aur tail ke can trolley ke neechay rakhein."),
        ("This supermarket provides covered parking with easy ramp access.", "اس سپر مارکیٹ میں گاڑیوں کی محفوظ اور کشادہ پارکنگ ہے۔", "Is supermarket mein gaariyon ki mahfooz parking hai."),
        ("Remember to bring your reusable canvas tote bags from home.", "گھر سے کپڑے کے بنے شاپنگ بیگز ساتھ لانا مت بھولیں۔", "Ghar se kapray ke banay shopping bags sath lana mat bhoolin."),
        ("Freshly ground black peppercorns have an intoxicating aroma.", "تازہ پسی کالی مرچ کی خوشبو انتہائی شاندار ہوتی ہے۔", "Taaza pisi kaali mirch ki khushboo shandar hoti hai."),
        ("Do you stock raw cashews, walnuts, and dried Turkish figs?", "کیا آپ کے پاس کاجو، اخروٹ اور خشک انجیر موجود ہیں؟", "Kya aap ke paas kaju, akhrot aur khushk injeer hain?"),
        ("The checkout queue is moving swiftly thanks to extra counters.", "اضافی کاؤنٹرز کی وجہ سے کیش کی لائن بہت تیزی سے چل رہی ہے۔", "Izafi counters ki wajah se cash ki line taizi se chal rahi hai."),
        ("Thank you for shopping at our supermarket; see you again!", "ہمارے سپر اسٹور سے خریداری کا شکریہ، دوبارہ تشریف لائیں!", "Hamare super store se khareedari ka shukriya, dobara aayiye ga!"),
        ("May your pantry always be stocked with wholesome sustenance!", "اللہ تعالیٰ آپ کے گھر کو ہمیشہ پاکیزہ رزق اور فراوانی عطا کرے!", "Allah Ta'ala aap ke ghar ko hamesha pakeeza rizq ata karay!")
    ]
    topics.append({
        "id": 30, "name": "Groceries & Supermarket", "urduName": "گروسری اور سپر مارکیٹ", "icon": "shopping_bag",
        "desc": "Fresh produce, pantry items, dairy, and aisles.", "sentences": t30
    })

print("Part 3 28-30 loaded.")
